import type { OnlineExam } from '@/types/online-exam';

// MEB Türkiye Yüzyılı Maarif Modeli (9. Sınıf) Konu & Ünite Pekiştirme Testleri
// Tüm sorular MEB TTKB resmi kazanımlarına ve ortak yazılı soru kalıplarına tam uyumludur.

export const LISE1_UNIT_TESTS: OnlineExam[] = [
  // 1. MATEMATİK (1. Tema: Sayılar)
  {
    id: 'exam-lise1-unit-mat-1',
    slug: 'meb-9-matematik-tema-1-sayilar-testi',
    title: '9. Sınıf Matematik 1. Tema: Sayılar Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Gerçek sayıların üslü/köklü gösterimleri, sayı aralıkları ve özdeşlikler pekiştirme sınavı.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'matematik',
    courseName: 'Matematik (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 20,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Tema: Sayılar',
    questions: [
      {
        id: 'l1-u-mat-q1',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - Gerçek Sayıların Üslü ve Köklü Gösterimleri',
        questionNumber: 1,
        questionText: '2^(x + 1) = 32 olduğuna göre, 3^(x - 1) ifadesinin değeri kaçtır?',
        options: {
          A: '3',
          B: '9',
          C: '27',
          D: '81',
          E: '243',
        },
        correctAnswer: 'C',
        explanation: '1. Adım: 32 sayısını 2\'nin kuvveti olarak yazalım: 32 = 2⁵.\n2^(x + 1) = 2⁵ ⇒ x + 1 = 5 ⇒ x = 4 bulunur.\n\n2. Adım: x = 4 değerini istenen ifadede yerine koyalım:\n3^(x - 1) = 3^(4 - 1) = 3³ = 27 bulunur.\nDoğru seçenek C\'dir.',
        hintForSocratic: '32 sayısını 2\'nin kaçıncı kuvveti olarak yazabilirsin? Tabanlar eşitse üsler de birbirine eşit olmalıdır.',
      },
      {
        id: 'l1-u-mat-q2',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - Köklü İfadelerde Dört İşlem',
        questionNumber: 2,
        questionText: '√108 - √48 + √27 işleminin sonucu aşağıdakilerden hangisidir?',
        options: {
          A: '3√3',
          B: '4√3',
          C: '5√3',
          D: '6√3',
          E: '7√3',
        },
        correctAnswer: 'C',
        explanation: '1. Adım: Kök içindeki sayıları a√b biçiminde yazalım:\n√108 = √(36 · 3) = 6√3\n√48 = √(16 · 3) = 4√3\n√27 = √(9 · 3) = 3√3\n\n2. Adım: Katsayıları toplayıp çıkaralım:\n(6 - 4 + 3)√3 = 5√3 bulunur.\nDoğru seçenek C\'dir.',
        hintForSocratic: '108, 48 ve 27 sayılarını içinde tam kare olan çarpanlarına (36, 16, 9) ayırarak kök dışına çıkarmayı dene.',
      },
      {
        id: 'l1-u-mat-q3',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - Tam Kare ve Mutlak Değer Bağıntısı',
        questionNumber: 3,
        questionText: 'x ve y birer tam sayı olmak üzere,\n(x - 3)² + |y + 5| = 0\n\neşitliği verildiğine göre, x · y çarpımı kaçtır?',
        options: {
          A: '-15',
          B: '-8',
          C: '0',
          D: '8',
          E: '15',
        },
        correctAnswer: 'A',
        explanation: 'Gerçek sayılarda bir sayının karesi ve mutlak değeri hiçbir zaman negatif olamaz (≥ 0).\nİki negatif olmayan sayının toplamının sıfır olması ancak her ikisinin de sıfır olmasıyla mümkündür:\n(x - 3)² = 0 ⇒ x - 3 = 0 ⇒ x = 3\n|y + 5| = 0 ⇒ y + 5 = 0 ⇒ y = -5\n\nx · y = 3 · (-5) = -15 bulunur. Doğru seçenek A\'dır.',
        hintForSocratic: 'Bir tam kare ifade ve bir mutlak değer en az kaç olabilir? Toplamın 0 çıkması için ikisinin de kaç olması gerekir?',
      },
      {
        id: 'l1-u-mat-q4',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - Gerçek Sayı Aralıkları ve Kesişim',
        questionNumber: 4,
        questionText: 'A = [-4, 6) ve B = (-1, 9] aralıkları tanımlanıyor.\n\nBuna göre, (A ∩ B) aralığında yer alan tam sayıların toplamı kaçtır?',
        options: {
          A: '10',
          B: '12',
          C: '14',
          D: '15',
          E: '18',
        },
        correctAnswer: 'D',
        explanation: '1. Adım: A ∩ B kesişim kümesini bulalım. Sol sınırların büyüğü: max(-4, -1) = -1 (açık), sağ sınırların küçüğü: min(6, 9) = 6 (açık).\nA ∩ B = (-1, 6) açık aralığıdır.\n\n2. Adım: Bu aralıktaki tam sayılar: {0, 1, 2, 3, 4, 5}.\nToplam = 0 + 1 + 2 + 3 + 4 + 5 = 15 bulunur.\nDoğru seçenek D\'dir.',
        hintForSocratic: 'İki aralığın kesişiminde sınır noktalarına dikkat et: -1 ve 6 noktaları dahil midir, aradaki tam sayılar nelerdir?',
      },
      {
        id: 'l1-u-mat-q5',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - İki Kare Farkı ve Tam Kare Özdeşlikleri',
        questionNumber: 5,
        questionText: 'a ve b pozitif gerçek sayılar olmak üzere,\na + b = 7 ve a · b = 10\n\nolduğuna göre, a² + b² ifadesinin değeri kaçtır?',
        options: {
          A: '25',
          B: '29',
          C: '39',
          D: '49',
          E: '59',
        },
        correctAnswer: 'B',
        explanation: 'Tam kare açılımı kuralına göre:\n(a + b)² = a² + 2ab + b²\nBuradan a² + b² = (a + b)² - 2ab yazılır.\n\nVerilen değerleri yerine koyalım:\na² + b² = 7² - 2 · 10 = 49 - 20 = 29 bulunur.\nDoğru seçenek B\'dir.',
        hintForSocratic: '(a + b)² açılımını yaz. İçindeki a · b ve a² + b² terimlerini nasıl gruplayabilirsin?',
      },
    ],
  },

  // 2. FİZİK (1. ve 2. Ünite: Fizik Bilimi, Büyüklükler ve Hareket)
  {
    id: 'exam-lise1-unit-fiz-1',
    slug: 'meb-9-fizik-unite-1-ve-2-testi',
    title: '9. Sınıf Fizik 1. ve 2. Ünite: Fizik Bilimi & Hareket Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Fiziğin doğası, temel/türetilmiş büyüklükler, vektörler ve bir boyutta doğrusal hareket soruları.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'fizik',
    courseName: 'Fizik (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. ve 2. Ünite: Fizik Bilimi & Hareket',
    questions: [
      {
        id: 'l1-u-fiz-q1',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '2. Ünite: Kuvvet ve Hareket - Temel ve Türetilmiş Büyüklükler',
        questionNumber: 1,
        questionText: 'Aşağıda verilen fiziksel büyüklüklerden hangisi SI birim sisteminde TEMEL bir büyüklüktür?',
        options: {
          A: 'Kuvvet (Newton)',
          B: 'Hız (m/s)',
          C: 'Termodinamik Sıcaklık (Kelvin)',
          D: 'İvme (m/s²)',
          E: 'İş ve Enerji (Joule)',
        },
        correctAnswer: 'C',
        explanation: 'Fizikte 7 temel büyüklük "KISA MUZ" kodlamasıyla hatırlanır: Kütle, Işık şiddeti, Sıcaklık (Kelvin), Akım şiddeti, Madde miktarı, Uzunluk, Zaman. Kuvvet, hız, ivme ve enerji ise diğer büyüklüklerden türetilmiştir. Doğru seçenek C\'dir.',
        hintForSocratic: 'KISA MUZ kısaltmasını hatırla. Sıcaklık tek başına doğrudan mı ölçülür yoksa başka formüllerle mi türetilir?',
      },
      {
        id: 'l1-u-fiz-q2',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '2. Ünite: Kuvvet ve Hareket - Doğrusal Hareket ve Yer Değiştirme',
        questionNumber: 2,
        questionText: 'Doğrusal bir yolda sabit 20 m/s hızla ilerleyen bir otomobil, 15 saniye boyunca bu hareketini sürdürmektedir.\n\nBuna göre otomobilin bu süre zarfındaki yer değiştirmesi kaç metredir?',
        options: {
          A: '150',
          B: '200',
          C: '250',
          D: '300',
          E: '350',
        },
        correctAnswer: 'D',
        explanation: 'Sabit hızlı doğrusal harekette yer değiştirme bağıntısı:\nΔx = v · t\nΔx = 20 m/s · 15 s = 300 metre bulunur.\nDoğru seçenek D\'dir.',
        hintForSocratic: 'Sabit hızda yer değiştirme = Hız × Zaman formülünü uygula.',
      },
      {
        id: 'l1-u-fiz-q3',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '1. Ünite: Fizik Bilimi ve Kariyer Keşfi - Fiziğin Alt Dalları',
        questionNumber: 3,
        questionText: 'Fiber optik kablolarla ışığın tam yansıması prensibine dayalı yüksek hızlı internet iletişimi ve göz kusurlarını düzelten lazer ameliyatları, fiziğin hangi alt dalının inceleme alanına girer?',
        options: {
          A: 'Mekanik',
          B: 'Termodinamik',
          C: 'Optik',
          D: 'Manyetizma',
          E: 'Nükleer Fizik',
        },
        correctAnswer: 'C',
        explanation: 'Işığın yapısını, yayılmasını, yansıma ve kırılma gibi olaylarını inceleyen fizik alt dalı Optik\'tir. Fiber optik ve lazer teknolojisi doğrudan optiğin konusudur. Doğru seçenek C\'dir.',
        hintForSocratic: 'Işık, mercekler, yansıma ve kırılma ile ilgilenen fizik alt dalı hangisidir?',
      },
      {
        id: 'l1-u-fiz-q4',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '2. Ünite: Kuvvet ve Hareket - Kartezyen Koordinatlarda Vektörler',
        questionNumber: 4,
        questionText: 'Aynı noktaya etki eden iki kuvvetten F1 doğu yönünde 6 N, F2 ise kuzey yönünde 8 N büyüklüğündedir.\n\nBuna göre bu iki kuvvetin bileşkesinin (R) büyüklüğü kaç Newton\'dur?',
        options: {
          A: '10',
          B: '12',
          C: '14',
          D: '48',
          E: '100',
        },
        correctAnswer: 'A',
        explanation: 'Doğu ve kuzey yönleri birbirine diktir (aralarındaki açı 90°\'dir).\nPisagor bağıntısından bileşke:\nR = √(F1² + F2²) = √(6² + 8²) = √(36 + 64) = √100 = 10 N bulunur.\nDoğru seçenek A\'dır.',
        hintForSocratic: 'Aralarında 90 derece açı bulunan dik iki vektörün bileşkesini bulmak için Pisagor bağıntısını (3-4-5 üçgeninin katları) hatırla.',
      },
      {
        id: 'l1-u-fiz-q5',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '2. Ünite: Kuvvet ve Hareket - Doğadaki Temel Kuvvetler',
        questionNumber: 5,
        questionText: 'Doğadaki dört temel kuvvetten biri olan, etki menzili sonsuz kabul edilen ve gezegenlerin Güneş etrafında belirli bir yörüngede kalmasını sağlayan kuvvet aşağıdakilerden hangisidir?',
        options: {
          A: 'Güçlü Nükleer Kuvvet',
          B: 'Zayıf Nükleer Kuvvet',
          C: 'Kütle Çekim Kuvveti',
          D: 'Elektromanyetik Kuvvet',
          E: 'Sürtünme Kuvveti',
        },
        correctAnswer: 'C',
        explanation: 'Kütlesi olan tüm cisimlerin birbirine uyguladığı çekim kuvveti Kütle Çekim Kuvveti\'dir. Menzili sonsuzdur ve gezegenlerin, uyduların yörüngede kalmasını sağlar. Doğru seçenek C\'dir.',
        hintForSocratic: 'Gök cisimlerinin kütleleri nedeniyle birbirini çekmesini sağlayan temel doğa kuvveti hangisidir?',
      },
    ],
  },

  // 3. KİMYA (1. Tema: Etkileşim - Kimya Bilimi, Atom Modelleri ve Periyodik Tablo)
  {
    id: 'exam-lise1-unit-kim-1',
    slug: 'meb-9-kimya-tema-1-etkilesim-testi',
    title: '9. Sınıf Kimya 1. Tema: Etkileşim & Atomun Yapısı Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Laboratuvar güvenliği, atom teorileri, elektron dağılımı ve periyodik sistem özellikleri testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'kimya',
    courseName: 'Kimya (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Tema: Etkileşim',
    questions: [
      {
        id: 'l1-u-kim-q1',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Laboratuvar Güvenlik Kuralları ve Piktogramlar',
        questionNumber: 1,
        questionText: 'Bir kimyasal madde şişesi üzerinde "alev simgesi" (üzerinde alev deseni bulunan tehlike piktogramı) bulunmaktadır.\n\nBu uyarı işareti kimyasal maddenin hangi özelliğe sahip olduğunu belirtir?',
        options: {
          A: 'Aşındırıcı (Korozif) Madde',
          B: 'Yanıcı Madde',
          C: 'Radyoaktif Madde',
          D: 'Patlayıcı Madde',
          E: 'Çevreye Zararlı Madde',
        },
        correctAnswer: 'B',
        explanation: 'Doğrudan alev deseni içeren piktogram maddenin "Yanıcı" (flammable) olduğunu, kolay tutuşabileceğini ve ateş kaynaklarından uzak tutulması gerektiğini gösterir. Doğru seçenek B\'dir.',
        hintForSocratic: 'Alev şekli yangın ve kolay tutuşma ile ilgilidir. Bu piktogram hangi özelliği simgeler?',
      },
      {
        id: 'l1-u-kim-q2',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Elektron Dizilimi ve Periyodik Tablo',
        questionNumber: 2,
        questionText: 'Nötr bir X atomunun katman elektron dizilimi 2 - 8 - 7 şeklindedir.\n\nBuna göre X elementi periyodik sistemde hangi periyot ve grupta yer alır?',
        options: {
          A: '2. Periyot 7A Grubu',
          B: '3. Periyot 7A Grubu',
          C: '3. Periyot 8A Grubu',
          D: '7. Periyot 3A Grubu',
          E: '2. Periyot 8A Grubu',
        },
        correctAnswer: 'B',
        explanation: 'Katman sayısı periyot numarasını, son katmandaki değerlik elektron sayısı ise A grubunu verir.\n3 katman vardır ⇒ 3. Periyot.\nSon katmanda 7 elektron vardır ⇒ 7A Grubu (Halojen).\nDoğru seçenek B\'dir.',
        hintForSocratic: 'Katman sayısı periyodu, son katmandaki elektron sayısı grubu verir. Kaç katman ve son katmanda kaç elektron var?',
      },
      {
        id: 'l1-u-kim-q3',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Periyodik Özelliklerin Değişimi',
        questionNumber: 3,
        questionText: 'Periyodik tabloda aynı periyotta soldan sağa doğru gidildikçe genel olarak aşağıdakilerden hangisi gerçekleşir?',
        options: {
          A: 'Atom yarıçapı artar.',
          B: 'Katman sayısı artar.',
          C: 'Metalik aktiflik artar.',
          D: 'Elektronegatiflik ve ametalik özellik artar.',
          E: 'Çekirdeğin proton sayısı azalır.',
        },
        correctAnswer: 'D',
        explanation: 'Aynı periyotta soldan sağa gidildikçe çekirdek yükü (proton sayısı) artar, katman sayısı değişmez. Çekim gücü arttığından atom yarıçapı küçülür, elektron ilgisi, iyonlaşma enerjisi, elektronegatiflik ve ametalik özellik artar. Doğru seçenek D\'dir.',
        hintForSocratic: 'Sağ tarafta ametaller ve halojenler yer alır. Soldan sağa giderken ametallere mi metallere mi yaklaşırız?',
      },
      {
        id: 'l1-u-kim-q4',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Atom Modelleri ve Tarihsel Gelişim',
        questionNumber: 4,
        questionText: 'Dalton atom modelinde yer alan;\nI. Atomlar bölünemez, parçalanamaz en küçük yapı taşlarıdır.\nII. Bir elementin bütün atomları kütlece birbirinin tıpatıp aynısıdır.\nIII. Farklı element atomları birbirinden farklıdır.\n\nyargılarından hangileri günümüz modern atom teorisine göre GEÇERLİLİĞİNİ YİTİRMİŞTİR?',
        options: {
          A: 'Yalnız I',
          B: 'Yalnız II',
          C: 'I ve II',
          D: 'II ve III',
          E: 'I, II ve III',
        },
        correctAnswer: 'C',
        explanation: 'Günümüzde atomlar nükleer reaksiyonlarla bölünebilir (I yanlış). İzotop atomların keşfiyle aynı elementin farklı nötron sayılı/kütleli atomları olduğu kanıtlanmıştır (II yanlış). Farklı elementlerin atomları ise birbirinden farklıdır (III hâlâ geçerlidir). Dolayısıyla I ve II geçerliliğini yitirmiştir. Doğru seçenek C\'dir.',
        hintForSocratic: 'Nükleer fisyon atomun bölünebildiğini, izotop kavramı ise aynı elementin farklı kütleli atomları olduğunu gösterir.',
      },
      {
        id: 'l1-u-kim-q5',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Kimya Disiplinleri ve Çalışma Alanları',
        questionNumber: 5,
        questionText: 'Bir su arıtma tesisinde suyun içindeki ağır metallerin (kurşun, cıva vb.) türünü ve miktarını hassas cihazlarla analiz eden kimya alt disiplini aşağıdakilerden hangisidir?',
        options: {
          A: 'Organik Kimya',
          B: 'Analitik Kimya',
          C: 'Biyokimya',
          D: 'Fizikokimya',
          E: 'Polimer Kimyası',
        },
        correctAnswer: 'B',
        explanation: 'Maddelerin bileşenlerini, ne olduklarını (nitel) ve ne kadar olduklarını (nicel) analiz eden temel kimya disiplini Analitik Kimya\'dır. Doğru seçenek B\'dir.',
        hintForSocratic: 'Tür (nitel) ve miktar (nicel) analizi yapan kimya disiplininin adı nedir?',
      },
    ],
  },

  // 4. BİYOLOJİ (1. Tema: Yaşam - Biyomoleküller ve Enzimler)
  {
    id: 'exam-lise1-unit-biyo-1',
    slug: 'meb-9-biyoloji-tema-1-yasam-testi',
    title: '9. Sınıf Biyoloji 1. Tema: Yaşam & Canlıların Bileşenleri Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Canlıların ortak özellikleri, inorganik/organik bileşikler ve enzimler konu pekiştirme testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'biyoloji',
    courseName: 'Biyoloji (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Tema: Yaşam',
    questions: [
      {
        id: 'l1-u-biy-q1',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - Canlıların Ortak Özellikleri',
        questionNumber: 1,
        questionText: 'Aşağıda verilen hücresel özelliklerden hangisi dünyadaki TÜM canlılarda ortak olarak gerçekleşir?',
        options: {
          A: 'Fotosentez yaparak kendi besinini üretme',
          B: 'Oksijenli solunum ile ATP üretme',
          C: 'Ribozom organelinde protein sentezleme',
          D: 'Mitoz bölünme ile çoğalma',
          E: 'Çekirdek zarı içerisinde DNA taşıma',
        },
        correctAnswer: 'C',
        explanation: 'Ribozom organeli prokaryot ve ökaryot tüm hücresel canlılarda bulunan tek zarsız organeldir ve tüm canlılar kendi proteinlerini ribozomda sentezler. Fotosentez, oksijenli solunum veya çekirdek zarı ise sadece belirli canlı gruplarında bulunur. Doğru seçenek C\'dir.',
        hintForSocratic: 'Zarsız olan ve hem bakteride hem insanda bulunan evrensel protein üretim merkezi hangi organeldir?',
      },
      {
        id: 'l1-u-biy-q2',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - Organik Bileşikler: Proteinler ve Dehidrasyon',
        questionNumber: 2,
        questionText: '100 adet amino asidin dehidrasyon senteziyle birbirine bağlanması sonucu doğrusal bir polipeptit zinciri oluşmaktadır.\n\nBu tepkime sürecinde kurulan peptit bağı sayısı ve açığa çıkan su (H2O) molekülü sayısı aşağıdakilerden hangisinde doğru verilmiştir?',
        options: {
          A: '100 bağ / 100 su',
          B: '99 bağ / 99 su',
          C: '100 bağ / 99 su',
          D: '99 bağ / 100 su',
          E: '50 bağ / 50 su',
        },
        correctAnswer: 'B',
        explanation: 'n sayıda monomerin birleştiği doğrusal polimerizasyonda:\nBağ sayısı = n - 1 = 100 - 1 = 99\nAçığa çıkan su sayısı = Kurulan bağ sayısı = 99 moleküldür.\nDoğru seçenek B\'dir.',
        hintForSocratic: 'n sayıda amino asitten oluşan doğrusal bir zincirde bağ sayısı ve açığa çıkan su sayısı n - 1 kuralına eşittir.',
      },
      {
        id: 'l1-u-biy-q3',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - Biyolojik Katalizörler: Enzimler',
        questionNumber: 3,
        questionText: 'Bir enzimatik reaksiyonun gerçekleştiği ortamın sıcaklığı 37°C\'den 65°C\'ye çıkarılmış ve ardından tekrar 37°C\'ye düşürülmüştür.\n\nSıcaklık 37°C\'ye geri düşürüldüğünde tepkimenin yeniden başlamamasının temel nedeni aşağıdakilerden hangisidir?',
        options: {
          A: 'Substratın ortamdan tamamen tükenmesi',
          B: 'Yüksek sıcaklıkta enzimin üç boyutlu protein yapısının geri dönüşümsüz bozulması (denatürasyon)',
          C: 'Enzimin aktivasyon enerjisini aşırı artırması',
          D: 'Ortamdaki su oranının sıfıra inmesi',
          E: 'Enzimin koenzim kısmının substratla yarışması',
        },
        correctAnswer: 'B',
        explanation: 'Enzimler protein yapılıdır. 55-60°C üzerindeki sıcaklıklarda proteinlerin tersiyer/üç boyutlu yapısı bozulur (denatürasyon). Bu bozulma geri dönüşümsüz olduğu için sıcaklık normale dönse bile enzim işlevini kaybeder. Doğru seçenek B\'dir.',
        hintForSocratic: 'Yumurtayı haşladıktan sonra soğutsan bile eski çiğ haline dönebilir mi? Proteinlerin yüksek sıcaklıkta yapısının bozulmasına ne denir?',
      },
      {
        id: 'l1-u-biy-q4',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - İnorganik Bileşikler',
        questionNumber: 4,
        questionText: 'Canlıların yapısında bulunan inorganik bileşikler (su, mineraller, asitler, bazlar) ile ilgili aşağıdakilerden hangisi YANLIŞTIR?',
        options: {
          A: 'Canlılar tarafından sentezlenemez, dışarıdan hazır alınırlar.',
          B: 'Hücre zarından sindirilmeden doğrudan geçebilirler.',
          C: 'Hücresel solunumda enerji verici (ATP üretimi için) birinci derece yakıt olarak kullanılırlar.',
          D: 'Enzimlerin yapısına kofaktör olarak katılarak düzenleyici rol oynarlar.',
          E: 'Vücudun asit-baz dengesini ve ozmotik basıncını ayarlarlar.',
        },
        correctAnswer: 'C',
        explanation: 'İnorganik bileşikler (su, mineraller vb.) hiçbir canlı tarafından hücresel solunumda PARÇALANARAK ENERJİ (ATP) ÜRETMEK AMACIYLA KULLANILMAZ. Enerji verici moleküller sadece organik moleküllerdir (karbonhidrat, yağ, protein). Doğru seçenek C\'dir.',
        hintForSocratic: 'Su veya tuz içtiğimizde kalori/enerji alır mıyız? İnorganik maddeler enerji verir mi?',
      },
      {
        id: 'l1-u-biy-q5',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - Nükleik Asitler (DNA ve RNA)',
        questionNumber: 5,
        questionText: 'DNA ve RNA molekülleri karşılaştırıldığında;\nI. Adenin, Guanin ve Sitozin bazlarını taşıma\nII. Deoksiriboz beş karbonlu şekerine sahip olma\nIII. Çift sarmallı heliks yapı gösterme\n\nözelliklerinden hangileri HER İKİ nükleik asit için de ORTAKTIR?',
        options: {
          A: 'Yalnız I',
          B: 'Yalnız II',
          C: 'I ve II',
          D: 'I ve III',
          E: 'I, II ve III',
        },
        correctAnswer: 'A',
        explanation: 'Adenin, Guanin ve Sitozin bazları hem DNA hem RNA\'da ortaktır (I doğru). Deoksiriboz şekeri ve çift zincirli sarmal yapı sadece DNA\'ya aittir; RNA riboz şekeri taşır ve tek zincirlidir. Yalnız I ortaktır. Doğru seçenek A\'dır.',
        hintForSocratic: 'DNA ve RNA\'nın şekerleri aynı mıdır (Deoksiriboz vs Riboz)? Hangi organik bazlar her ikisinde de bulunur?',
      },
    ],
  },

  // 5. İNGİLİZCE (Theme 1: School Life)
  {
    id: 'exam-lise1-unit-ing-1',
    slug: 'meb-9-ingilizce-theme-1-school-life-testi',
    title: '9. Sınıf İngilizce Theme 1: School Life Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli İngilizce Theme 1: School Life ünitesi için özel hazırlanmış 5 soruluk hızlı pekiştirme testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'ingilizce',
    courseName: 'İngilizce (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'Orta',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: 'Theme 1: School Life',
    questions: [
      {
        id: 'l1-u-ing-q1',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 1: School Life - Countries, Nationalities & Capitals',
        questionNumber: 1,
        questionText:
          'Match the student with their country and language:\n\n"Pierre is from France. His native language is ------, and the capital of his country is ------."\n\nWhich pair completes the sentence?',
        options: {
          A: 'French / Paris',
          B: 'France / Lyon',
          C: 'German / Berlin',
          D: 'Spanish / Madrid',
          E: 'Italian / Rome',
        },
        correctAnswer: 'A',
        explanation: 'Fransa\'dan (France) olan birinin ana dili Fransızca (French), başkenti ise Paris\'tir. Doğru seçenek A\'dır.',
        hintForSocratic: 'Fransa\'nın ana dili ve başkenti hangisidir?',
      },
      {
        id: 'l1-u-ing-q2',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 1: School Life - School Timetable and Subjects',
        questionNumber: 2,
        questionText:
          'Teacher: "Which subject do you have right after the chemistry class on Wednesdays?"\nStudent: "We have ------. We learn about computers, algorithms and flowcharts."\n\nWhich school subject is the student talking about?',
        options: {
          A: 'History',
          B: 'Computer Science',
          C: 'Geography',
          D: 'Physical Education',
          E: 'Visual Arts',
        },
        correctAnswer: 'B',
        explanation: 'Bilgisayar, algoritma ve akış şemalarının öğrenildiği ders Bilgisayar Bilimi\'dir (Computer Science). Doğru seçenek B\'dir.',
        hintForSocratic: 'Computers, algorithms ve flowcharts hangi ders ile ilgilidir?',
      },
      {
        id: 'l1-u-ing-q3',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 2: Classroom Life - Friendships & Social Interactions',
        questionNumber: 3,
        questionText:
          'Selim: "Could you lend me your dictionary for the English vocabulary exercise?"\nCan: "------. Here you are!"\n\nWhich of the following polite expressions completes Can\'s answer?',
        options: {
          A: 'Certainly, of course',
          B: 'I completely disagree',
          C: 'I am afraid I can\'t',
          D: 'Never mind, forget it',
          E: 'No way, I hate sharing',
        },
        correctAnswer: 'A',
        explanation: '"Here you are" (Buyur, al) diyerek sözlüğü veren Can, olumlu ve kibar bir kabul ifadesi kullanmıştır: "Certainly, of course" (Kesinlikle, elbette). Doğru seçenek A\'dır.',
        hintForSocratic: 'Olumlu bir rica cevabı arıyoruz; "Here you are" dediğine göre kabul etmiştir.',
      },
      {
        id: 'l1-u-ing-q4',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 3: Personal Life - Personality Adjectives',
        questionNumber: 4,
        questionText:
          'Choose the ODD one out in terms of personality traits:',
        options: {
          A: 'Generous',
          B: 'Honest',
          C: 'Reliable',
          D: 'Curly',
          E: 'Friendly',
        },
        correctAnswer: 'D',
        explanation: 'Generous (cömert), Honest (dürüst), Reliable (güvenilir) ve Friendly (arkadaş canlısı) kişilik sıfatlarıdır (personality). Curly (kıvırcık) ise fiziksel görünüş sıfatıdır (physical appearance). Doğru seçenek D\'dir.',
        hintForSocratic: 'Kişilik (iç özellik) ile dış görünüşü ayırt et: Saçın kıvırcık olması kişilik midir?',
      },
      {
        id: 'l1-u-ing-q5',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 4: Family Life - Daily Routines',
        questionNumber: 5,
        questionText:
          '"My father is a surgeon. He works at a central hospital and he usually performs critical operations early in the morning."\n\nWhat does the speaker\'s father do for a living?',
        options: {
          A: 'He is a medical doctor / surgeon.',
          B: 'He is a high school teacher.',
          C: 'He is a civil engineer.',
          D: 'He is a graphic designer.',
          E: 'He is a lawyer in a courthouse.',
        },
        correctAnswer: 'A',
        explanation: 'Surgeon (cerrah) hastanede ameliyat yapan bir tıp doktorudur (medical doctor / surgeon). Doğru seçenek A\'dır.',
        hintForSocratic: 'Surgeon ve operations kelimeleri hangi mesleği işaret eder?',
      },
    ],
  },

  // 6. TÜRK DİLİ VE EDEBİYATI (1. Tema: Sözün İnceliği)
  {
    id: 'exam-lise1-unit-edb-1',
    slug: 'meb-9-edebiyat-tema-1-sozun-inceligi-testi',
    title: '9. Sınıf Türk Dili ve Edebiyatı 1. Tema: Sözün İnceliği Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Şiirde ahenk unsurları, kafiye-redif, hikâye türü ve sözcük türleri pekiştirme testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'edebiyat',
    courseName: 'Türk Dili ve Edebiyatı',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Tema: Sözün İnceliği',
    questions: [
      {
        id: 'l1-u-edb-q1',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: '1. Tema: Sözün İnceliği - Şiir Sanatı ve Ahenk Unsurları',
        questionNumber: 1,
        questionText:
          '"Kandilli yüzerken uykularda\nMehtâbı sürükledik sularda"\n\nBu dizelerdeki kafiye (uyak) türü ve redif aşağıdakilerin hangisinde doğru verilmiştir?',
        options: {
          A: 'Tam kafiye / -da redif',
          B: 'Zengin kafiye / -larda redif',
          C: 'Yarım kafiye / -larda redif',
          D: 'Tunç kafiye / redif yoktur',
          E: 'Cinaslı kafiye / -lar redif',
        },
        correctAnswer: 'C',
        explanation: 'Dize sonlarındaki kelimeler: "uyku-lar-da" ve "su-lar-da".\n1. Adım: "-lar" çokluk eki ve "-da" bulunma durum eki görev ve anlamca aynı olduğundan "-larda" kısmı REDİF\'tir.\n2. Adım: Geriye kalan köklerde ("uyku" ve "su") ortak olan tek ses "-u" sesidir. Tek ses benzerliği YARIM KAFİYE oluşturur.\nDolayısıyla: Yarım kafiye / -larda redif. Doğru seçenek C\'dir.',
        hintForSocratic: 'Dize sonlarındaki aynı görevdeki ekleri (-lar ve -da) ayırarak redifi belirle, ardından kökte kalan ses benzerliğini incele.',
      },
      {
        id: 'l1-u-edb-q2',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: '2. Tema: Anlam Arayışı - Olay ve Durum Hikâyeleri',
        questionNumber: 2,
        questionText:
          'Serim, düğüm ve çözüm bölümlerine sıkı sıkıya bağlı kalmayan, merak ögesini ve heyecanı ikinci plana iterek hayatın bir kesitini duygu ve psikolojik atmosfer eşliğinde anlatan hikâye türü ve öncüsü aşağıdakilerden hangisidir?',
        options: {
          A: 'Olay Hikâyesi - Guy de Maupassant',
          B: 'Durum (Kesit) Hikâyesi - Anton Çehov',
          C: 'Tarihî Hikâye - Walter Scott',
          D: 'Ben Merkezli Hikâye - Franz Kafka',
          E: 'Epik Hikâye - Bertolt Brecht',
        },
        correctAnswer: 'B',
        explanation: 'Klasik olay örgüsü (serim-düğüm-çözüm) yerine günlük yaşamdan bir kesiti işleyen hikâye türü Durum (Kesit) Hikâyesi\'dir ve dünya edebiyatındaki öncüsü Rus yazar Anton Çehov\'dur (Türk edebiyatında Memduh Şevket Esendal ve Sait Faik Abasıyanık). Doğru seçenek B\'dir.',
        hintForSocratic: 'Merak ve heyecanın yerine günlük yaşamdan bir enstantaneyi/kesiti koyan Rus yazarın adıyla anılan hikâye tarzı hangisidir?',
      },
      {
        id: 'l1-u-edb-q3',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: '1. Tema: Sözün İnceliği - Güzel Sanatlar ve Edebiyat',
        questionNumber: 3,
        questionText:
          'Güzel sanatlar kullanılan malzemenin türüne göre fonetik (işitsel), plastik (görsel) ve ritmik (dramatik) sanatlar olarak üçe ayrılır.\n\nBuna göre edebiyat, malzemesi dil ve ses olduğu için hangi sanat dalı içerisinde yer alır?',
        options: {
          A: 'Plastik (Görsel) Sanatlar',
          B: 'Fonetik (İşitsel) Sanatlar',
          C: 'Dramatik (Ritmik) Sanatlar',
          D: 'Karma (Pratik) Sanatlar',
          E: 'Endüstriyel (Zanaat) Sanatlar',
        },
        correctAnswer: 'B',
        explanation: 'Edebiyat ve müzik, malzemesi ses ve söz olduğu için Fonetik (İşitsel) sanatlar grubunda yer alır. Resim ve heykel plastik; tiyatro ve sinema ise dramatik sanatlardandır. Doğru seçenek B\'dir.',
        hintForSocratic: 'Edebiyatın ana malzemesi dildir. Dille ve sesle icra edilen sanatlara ne ad verilir?',
      },
      {
        id: 'l1-u-edb-q4',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: '4. Tema: Dilin Zenginliği - Edebî Sanatlar',
        questionNumber: 4,
        questionText:
          '"Yalnız duyan yaşar, sözü derler ki doğrudur;\nYalnız duyan çeker bu teessür macerasını."\n\nBu beyitteki "yalnız" sözcüğü aşağıdaki görevlerden hangisiyle kullanılmıştır?',
        options: {
          A: 'Niteleme Sıfatı',
          B: 'Durum Zarfı',
          C: '"Sadece" anlamında Edat',
          D: '"Ama/Fakat" anlamında Bağlaç',
          E: 'Kişi Zamiri',
        },
        correctAnswer: 'C',
        explanation: '"Yalnız" sözcüğü cümlede "sadece/yalnızca" anlamında kullanıldığında edat (ilgeç) görevindedir. Dizede "Sadece duyan yaşar" anlamında kullanılmıştır. Doğru seçenek C\'dir.',
        hintForSocratic: '"Yalnız" sözcüğünün yerine "sadece" koyabiliyorsan hangi sözcük türü olur?',
      },
      {
        id: 'l1-u-edb-q5',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Dil Bilgisi: Noktalama İşaretleri',
        questionNumber: 5,
        questionText:
          'Aşağıdaki cümlelerin hangisinde noktalı virgül (;) yerinde ve doğru kullanılmıştır?',
        options: {
          A: 'Pazardan elma; portakal ve muz aldık.',
          B: 'Türkiye, Azerbaycan, Kazakistan; Ankara, Bakü, Astana.',
          C: 'Akşam oldu; herkes evine çekildi.',
          D: 'Genç adam; durakta uzun süre bekledi.',
          E: 'Kitabı açtı; sayfaları hızla çevirdi.',
        },
        correctAnswer: 'B',
        explanation: 'Noktalı virgülün temel görevlerinden biri cümle içinde virgüllerle ayrılmış tür veya takımları birbirinden ayırmaktır. Ülkeler (Türkiye, Azerbaycan, Kazakistan) ile başkentleri (Ankara, Bakü, Astana) iki farklı takım oluşturduğundan aralarına noktalı virgül getirilmesi kurala uygundur. Doğru seçenek B\'dir.',
        hintForSocratic: 'Noktalı virgülün farklı tür veya grupları birbirinden ayırma görevini düşün (örn: ülkeler ile başkentler).',
      },
    ],
  },

  // 7. TARİH (1. Ünite: Geçmişin İnşa Sürecinde Tarih)
  {
    id: 'exam-lise1-unit-tarih-1',
    slug: 'meb-9-tarih-unite-1-gecmisin-insasi-testi',
    title: '9. Sınıf Tarih 1. Ünite: Geçmişin İnşa Sürecinde Tarih Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Tarih bilimi, kaynak tenkidi, takvim sistemleri ve dijital tarih araştırmaları testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'tarih',
    courseName: 'Tarih (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Ünite: Geçmişin İnşa Sürecinde Tarih',
    questions: [
      {
        id: 'l1-u-tar-q1',
        courseKey: 'tarih',
        courseName: 'Tarih',
        topicName: '1. Ünite: Geçmişin İnşa Sürecinde Tarih - Tarihsel Kaynaklar',
        questionNumber: 1,
        questionText:
          'Tarih araştırmalarında olayın geçtiği döneme ait olan; kitabeler, sikkeler (paralar), mühürler, antlaşma metinleri ve fermanlar hangi kaynak türüne girer?',
        options: {
          A: 'Birinci Elden (Ana) Kaynaklar',
          B: 'İkinci Elden Kaynaklar',
          C: 'Sözlü Efsaneler',
          D: 'Dönem Sonrası Romanlar',
          E: 'Tarihî Yorumlar',
        },
        correctAnswer: 'A',
        explanation: 'Olayın yaşandığı döneme ait olan doğrudan belge, para, kitabe veya fermanlara "Birinci Elden (Kaynak)" denir. O dönemin kaynaklarından yararlanılarak sonradan yazılan eserler ise ikinci elden kaynaktır. Doğru seçenek A\'dır.',
        hintForSocratic: 'Olay anında yaşayan veya o dönemden günümüze doğrudan kalan belgelere ne ad verilir?',
      },
      {
        id: 'l1-u-tar-q2',
        courseKey: 'tarih',
        courseName: 'Tarih',
        topicName: '1. Ünite: Geçmişin İnşa Sürecinde Tarih - Takvim Sistemleri',
        questionNumber: 2,
        questionText:
          'Türklerin tarih boyunca kullandığı takvimlerden hangisi Güneş yılı değil, AY YILI (kamerî yıl - 354 gün) esasına dayanır?',
        options: {
          A: '12 Hayvanlı Türk Takvimi',
          B: 'Celâli Takvimi',
          C: 'Hicri Takvim',
          D: 'Rumi Takvim',
          E: 'Miladi Takvim',
        },
        correctAnswer: 'C',
        explanation: 'Türklerin kullandığı takvimlerden yalnızca Hicri Takvim ay yılını (354 gün) esas alır. 12 Hayvanlı, Celali, Rumi ve Miladi takvimlerin tamamı Güneş yılı (365 gün 6 saat) esasına dayanır. Doğru seçenek C\'dir.',
        hintForSocratic: 'Ramazan ayının ve dinî günlerin her yıl 10-11 gün öne gelmesine neden olan ay yılı takvimi hangisidir?',
      },
      {
        id: 'l1-u-tar-q3',
        courseKey: 'tarih',
        courseName: 'Tarih',
        topicName: '1. Ünite: Geçmişin İnşa Sürecinde Tarih - Tarihe Yardımcı Bilimler',
        questionNumber: 3,
        questionText:
          'Tarihî kazılarda bulunan eski paraları (sikkeleri) inceleyerek basıldığı devletin ekonomik gücü, hükümdarı ve dönemi hakkında bilgi veren yardımcı bilim dalı hangisidir?',
        options: {
          A: 'Epigrafi (Kitabe Bilimi)',
          B: 'Paleografya (Yazı Bilimi)',
          C: 'Nümizmatik (Meskukat / Para Bilimi)',
          D: 'Filoloji (Dil Bilimi)',
          E: 'Heraldik (Arma Bilimi)',
        },
        correctAnswer: 'C',
        explanation: 'Eski madenî paraları ve sikkeleri inceleyen bilim dalına Nümizmatik (Meskukat) denir. Epigrafi anıtları, Paleografya eski yazıları, Heraldik armaları inceler. Doğru seçenek C\'dir.',
        hintForSocratic: 'Sikke ve eski madenî paraları inceleyen bilim dalının adı nedir?',
      },
      {
        id: 'l1-u-tar-q4',
        courseKey: 'tarih',
        courseName: 'Tarih',
        topicName: '1. Ünite: Geçmişin İnşa Sürecinde Tarih - Tarihsel Bilginin Doğası',
        questionNumber: 4,
        questionText:
          'Tarih bilimini doğa bilimlerinden (fizik, kimya vb.) ayıran EN TEMEL yöntem farkı aşağıdakilerden hangisidir?',
        options: {
          A: 'Tarihte neden-sonuç ilişkisinin bulunmaması',
          B: 'Tarihsel olayların deney ve gözlem yoluyla laboratuvarda tekrarlanamaması',
          C: 'Tarihte belgelere ve kanıtlara dayalı araştırma yapılamaması',
          D: 'Tarihin sadece kralların hayatını incelemesi',
          E: 'Tarihsel bilginin hiçbir zaman değişmemesi',
        },
        correctAnswer: 'B',
        explanation: 'Tarihsel olaylar geçmişte yaşanmış, bitmiş ve tekil olaylardır; bu nedenle fizikteki veya kimyadaki gibi laboratuvar ortamında deney ve gözlemle tekrarlanamaz. Doğru seçenek B\'dir.',
        hintForSocratic: 'Geçmişte yaşanmış bir savaşı veya antlaşmayı bugün laboratuvarda deney yaparak tekrarlayabilir miyiz?',
      },
      {
        id: 'l1-u-tar-q5',
        courseKey: 'tarih',
        courseName: 'Tarih',
        topicName: '1. Ünite: Geçmişin İnşa Sürecinde Tarih - Dijitalleşme ve Yapay Zekâ',
        questionNumber: 5,
        questionText:
          'Türkiye Yüzyılı Maarif Modeli kapsamında tarih araştırmalarında yapay zekâ ve dijital teknolojilerin kullanılmasının sağladığı EN ÖNEMLİ kazanım aşağıdakilerden hangisidir?',
        options: {
          A: 'Tarihçilere olan ihtiyacı tamamen ortadan kaldırması',
          B: 'Milyonlarca sayfalık arşiv belgesi ve el yazmasını OCR ile saniyeler içinde tarayıp araştırmacının erişimine sunması',
          C: 'Tarihsel olayları gelecekte kesin olarak tahmin edebilmesi',
          D: 'Tüm tarihî belgelerin güvenilirliğini sorgulamadan doğru kabul etmesi',
          E: 'Tarih bilimini tamamen sanal bir kurgu haline getirmesi',
        },
        correctAnswer: 'B',
        explanation: 'Yapay zekâ ve dijital arşiv teknolojileri, Osmanlı Arşivi ve Süleymaniye gibi kütüphanelerdeki milyonlarca el yazması ve fermanı optik karakter tanıma (OCR) ve veri madenciliği ile hızla işleyerek araştırmacıların analizine sunar. Doğru seçenek B\'dir.',
        hintForSocratic: 'Dijitalleşmenin ve yapay zekânın arşiv belgelerine erişim hızına ve veri analizine katkısını düşün.',
      },
    ],
  },

  // 8. COĞRAFYA (1. ve 2. Ünite: Doğanın Doğası ve Harita Okuryazarlığı)
  {
    id: 'exam-lise1-unit-cog-1',
    slug: 'meb-9-cografya-unite-1-ve-2-testi',
    title: '9. Sınıf Coğrafya 1. ve 2. Ünite: Doğanın Doğası & Harita Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Coğrafyanın ilkeleri, harita projeksiyonları, ölçek ve izohips hesaplamaları testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'cografya',
    courseName: 'Coğrafya (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. ve 2. Ünite: Harita ve Coğrafya',
    questions: [
      {
        id: 'l1-u-cog-q1',
        courseKey: 'cografya',
        courseName: 'Coğrafya',
        topicName: '1. Ünite: Coğrafyanın Doğası - Coğrafya Biliminin İlkeleri',
        questionNumber: 1,
        questionText:
          '"Zeytin tarımı Türkiye\'de en çok Ege, Akdeniz ve Marmara kıyılarında yapılmaktadır."\n\nBu cümlede coğrafya biliminin hangi temel ilkesi kullanılmıştır?',
        options: {
          A: 'Nedensellik (Sebep-Sonuç) İlkesi',
          B: 'Dağılış İlkesi',
          C: 'Karşılıklı İlgi (Bağlantı) İlkesi',
          D: 'Dinamizm İlkesi',
          E: 'Tarihsellik İlkesi',
        },
        correctAnswer: 'B',
        explanation: 'Bir coğrafi olayın veya unsurun yeryüzünde "nerede" görüldüğünü, hangi sahalara yayıldığını gösteren ilke DAĞILIŞ ilkesidir. Dağılış ilkesi coğrafyayı diğer bilimlerden ayıran en belirgin ilkedir. Doğru seçenek B\'dir.',
        hintForSocratic: 'Cümle bir şeyin "nerede bulunduğunu ve nerelere yayıldığını" bildiriyorsa coğrafyanın hangi ilkesidir?',
      },
      {
        id: 'l1-u-cog-q2',
        courseKey: 'cografya',
        courseName: 'Coğrafya',
        topicName: '2. Ünite: Mekânsal Bilgi Teknolojileri - Projeksiyon Türleri',
        questionNumber: 2,
        questionText:
          'Dünyanın küresel şeklinin düzleme aktarılması sırasında oluşan bozulmaları en aza indirmek için projeksiyon yöntemleri geliştirilmiştir.\n\nEkvator ve çevresindeki ülkelerin (Brezilya, Endonezya, Kongo) haritaları çizilirken bozulmanın EN AZ olduğu projeksiyon türü hangisidir?',
        options: {
          A: 'Konik Projeksiyon (Orta Kuşak)',
          B: 'Düzlem Projeksiyon (Kutuplar)',
          C: 'Silindirik Projeksiyon (Ekvator Çevresi)',
          D: 'Parçalı Projeksiyon',
          E: 'Topografik Projeksiyon',
        },
        correctAnswer: 'C',
        explanation: 'Silindirik projeksiyonda silindir Ekvator çizgisine teğet geçer; bu nedenle Ekvator ve çevresinde bozulma en az olur, kutuplara doğru gidildikçe alan bozulması artar. Doğru seçenek C\'dir.',
        hintForSocratic: 'Silindir kâğıt küreye nerede teğet değer? Ekvator için hangi projeksiyon uygundur?',
      },
      {
        id: 'l1-u-cog-q3',
        courseKey: 'cografya',
        courseName: 'Coğrafya',
        topicName: '2. Ünite: Mekânsal Bilgi Teknolojileri - Ölçek ve Uzaklık Hesaplamaları',
        questionNumber: 3,
        questionText:
          '1 / 200.000 ölçekli bir topoğrafya haritasında A ve B şehirleri arasındaki uzaklık 5 cm olarak ölçülmüştür.\n\nBuna göre bu iki şehir arasındaki GERÇEK UZAKLIK kaç kilometredir?',
        options: {
          A: '1',
          B: '5',
          C: '10',
          D: '20',
          E: '100',
        },
        correctAnswer: 'C',
        explanation: 'Ölçek paydasındaki cm\'yi km\'ye çevirmek için 5 sıfır silinir:\n200.000 cm = 2 km (1 cm haritada gerçekte 2 km\'dir).\nGerçek Uzaklık = Harita Uzunluğu · Ölçek Paydası\nGU = 5 cm · 2 km = 10 km bulunur.\nDoğru seçenek C\'dir.',
        hintForSocratic: '1 km = 100.000 cm\'dir. Ölçek paydasından 5 sıfır silerek 1 cm\'nin kaç km olduğunu bul ve harita uzunluğuyla çarp.',
      },
      {
        id: 'l1-u-cog-q4',
        courseKey: 'cografya',
        courseName: 'Coğrafya',
        topicName: '2. Ünite: Mekânsal Bilgi Teknolojileri - İzohips Haritaları',
        questionNumber: 4,
        questionText:
          'Bir topoğrafya haritasında eş yükselti (izohips) eğrilerinin birbirine ÇOK SIKLAŞTIĞI (yaklaştığı) bir bölge için aşağıdakilerden hangisi KESİNLİKLE söylenebilir?',
        options: {
          A: 'Arazinin tamamen düz ve ova olduğu',
          B: 'Eğimin çok dik olduğu ve akarsu akış hızının yüksek olduğu',
          C: 'Yükseltinin sıfır metreye indiği',
          D: 'Kalıcı karların başladığı',
          E: 'Bölgede rüzgâr aşındırmasının durduğu',
        },
        correctAnswer: 'B',
        explanation: 'İzohipslerin sıklaştığı yerlerde eğim fazladır. Eğim fazla olduğundan buralarda akarsuların akış hızı, aşındırma gücü ve hidroelektrik potansiyeli artar; dağcılıkta uçurum veya falezler görülür. Doğru seçenek B\'dir.',
        hintForSocratic: 'Eğrilerin birbirine çok yaklaşması yokuşun/eğimin dikleştiğini mi yoksa düzleştiğini mi gösterir?',
      },
      {
        id: 'l1-u-cog-q5',
        courseKey: 'cografya',
        courseName: 'Coğrafya',
        topicName: '2. Ünite: Mekânsal Bilgi Teknolojileri - Coğrafi Bilgi Sistemleri (CBS)',
        questionNumber: 5,
        questionText:
          'Konuma dayalı mekânsal verilerin bilgisayar ortamında toplanması, depolanması, analiz edilmesi ve katmanlar halinde haritalara dönüştürülmesini sağlayan ileri teknoloji sistemine ne ad verilir?',
        options: {
          A: 'GPS (Küresel Konumlama)',
          B: 'CBS (Coğrafi Bilgi Sistemleri)',
          C: 'Sismograf Sistemi',
          D: 'Meteorolojik Radar',
          E: 'Batimetri Ağı',
        },
        correctAnswer: 'B',
        explanation: 'Mekânsal verilerin katmanlar halinde depolanıp analiz edildiği karar destek sistemine Coğrafi Bilgi Sistemleri (CBS / GIS) adı verilir. Doğru seçenek B\'dir.',
        hintForSocratic: 'Coğrafi verileri bilgisayarda katmanlar halinde işleyen sistemin Türkçe kısaltması nedir?',
      },
    ],
  },

  // 9. DİN KÜLTÜRÜ VE AHLAK BİLGİSİ (1. Ünite: Allah-İnsan İlişkisi)
  {
    id: 'exam-lise1-unit-din-1',
    slug: 'meb-9-din-unite-1-allah-insan-iliskisi-testi',
    title: '9. Sınıf Din Kültürü 1. Ünite: Allah-İnsan İlişkisi Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: İnsanın yaratılışı, fıtrat, vahiy-akıl ilişkisi ve dua ibadeti pekiştirme testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'din',
    courseName: 'Din Kültürü ve Ahlak Bilgisi',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Ünite: Allah-İnsan İlişkisi',
    questions: [
      {
        id: 'l1-u-din-q1',
        courseKey: 'din',
        courseName: 'Din Kültürü ve Ahlak Bilgisi',
        topicName: '1. Ünite: Allah-İnsan İlişkisi - İnsanın Yaratılışı ve Fıtrat',
        questionNumber: 1,
        questionText:
          'İnsanın doğuştan getirdiği, yaratıcısını tanıma, O\'na inanma ve iyiye yönelme potansiyelini ifade eden temel İslami kavram aşağıdakilerden hangisidir?',
        options: {
          A: 'Tevhid',
          B: 'Fıtrat',
          C: 'Takva',
          D: 'İhsan',
          E: 'İhlas',
        },
        correctAnswer: 'B',
        explanation: 'Fıtrat; insanın yaratılıştan sahip olduğu temiz öz, inanma eğilimi ve yaratıcısını bulma kabiliyetidir. Hz. Muhammed "Her doğan fıtrat üzere doğar..." buyurmuştur. Doğru seçenek B\'dir.',
        hintForSocratic: 'İnsanın doğuştan getirdiği temiz yaratılış koduna ne ad verilir?',
      },
      {
        id: 'l1-u-din-q2',
        courseKey: 'din',
        courseName: 'Din Kültürü ve Ahlak Bilgisi',
        topicName: '1. Ünite: Allah-İnsan İlişkisi - Vahiy ve Akıl Dengesi',
        questionNumber: 2,
        questionText:
          'İslam dininde bir insanın inanç ve ibadetlerden dinen SORUMLU (mükellef) tutulabilmesi için taşıması gereken İKİ TEMEL şart aşağıdakilerden hangisidir?',
        options: {
          A: 'Zengin olmak ve seyahat etmek',
          B: 'Akıl sağlığına sahip olmak ve irade (seçme) hürriyeti taşımak',
          C: 'Arapça bilmek ve din eğitimi almak',
          D: 'Toplumda lider konumunda bulunmak',
          E: 'Sadece erkek olmak',
        },
        correctAnswer: 'B',
        explanation: 'İslam\'da dinî sorumluluğun (teklif) iki temel şartı akıl ve iradedir. Aklı olmayan veya iradesiyle baskı altında olmadan seçim yapamayan kimseler sorumlu tutulmaz. Doğru seçenek B\'dir.',
        hintForSocratic: 'Kişinin yaptıklarından sorumlu olabilmesi için doğruyu yanlıştan ayıran hangi melekeye ve seçim yapma hakkına sahip olması gerekir?',
      },
      {
        id: 'l1-u-din-q3',
        courseKey: 'din',
        courseName: 'Din Kültürü ve Ahlak Bilgisi',
        topicName: '1. Ünite: Allah-İnsan İlişkisi - İbadet ve İhlas',
        questionNumber: 3,
        questionText:
          'Yapılan ibadetlerin ve hayırların yalnızca Allah\'ın rızasını kazanmak amacıyla, gösterişten (riyadan) uzak bir samimiyetle yapılmasına ne ad verilir?',
        options: {
          A: 'İhlas',
          B: 'Kader',
          C: 'Nifak',
          D: 'Gıybet',
          E: 'Kibir',
        },
        correctAnswer: 'A',
        explanation: 'İhlas; ibadet ve iyiliklerin yalnızca Allah rızası için saf ve samimi bir kalple yapılmasıdır. Zıddı gösteriş (riya) ve ikiyüzlülüktür. Doğru seçenek A\'dır.',
        hintForSocratic: 'Samimiyet ve ibadeti sadece Allah için yapma erdemine ne ad verilir?',
      },
      {
        id: 'l1-u-din-q4',
        courseKey: 'din',
        courseName: 'Din Kültürü ve Ahlak Bilgisi',
        topicName: '2. Ünite: İslam\'da İnanç Esasları - İman Çeşitleri',
        questionNumber: 4,
        questionText:
          'Kişinin anne-baba ve çevresinden gördüğü şekliyle, delillerini araştırmadan ve üzerinde düşünmeden kabul ettiği iman türüne ne ad verilir?',
        options: {
          A: 'Tahkiki İman',
          B: 'Taklidi İman',
          C: 'Tafsili İman',
          D: 'İcmali İman',
          E: 'Kamil İman',
        },
        correctAnswer: 'B',
        explanation: 'Çevrenin etkisiyle delilsiz ve araştırmadan benimsenen imana "Taklidi İman" denir. Bilgiye, araştırmaya ve akli delillere dayanan sağlam imana ise "Tahkiki İman" adı verilir. Doğru seçenek B\'dir.',
        hintForSocratic: 'Araştırmadan başkalarını taklit ederek benimsenen iman türü hangisidir?',
      },
      {
        id: 'l1-u-din-q5',
        courseKey: 'din',
        courseName: 'Din Kültürü ve Ahlak Bilgisi',
        topicName: '1. Ünite: Allah-İnsan İlişkisi - Kur\'an\'dan Mesajlar (Rum Suresi 17-27)',
        questionNumber: 5,
        questionText:
          'Rum suresinin 17-27. ayetlerinde göklerin ve yerin yaratılması, insanların farklı dillerde ve renklerde yaratılması, gece uykusu ve şimşeğin çakması gibi olayların vurgulanmasındaki ASIL AMAÇ nedir?',
        options: {
          A: 'Sadece coğrafi ve meteorolojik bilgi vermek',
          B: 'İnsanı evrendeki düzen ve çeşitlilik üzerinde düşünerek Allah\'ın varlığı ve kudretine ulaştırmak',
          C: 'İnsanların ticaret yollarını bulmasını sağlamak',
          D: 'Eski kavimlerin savaşlarını anlatmak',
          E: 'İbadetlerin vakitlerini hesaplatmak',
        },
        correctAnswer: 'B',
        explanation: 'Rum suresindeki bu ayetler ("O\'nun delillerindendir ki...") kâinattaki harika nizamı, insanın fıtratını ve biyolojik çeşitliliği insanın aklına hitap ederek Allah\'ın birliği ve sonsuz kudretini kavratmak için anlatır. Doğru seçenek B\'dir.',
        hintForSocratic: 'Ayetlerdeki doğa olayları ve insanın çeşitliliği insanı neyi tefekkür etmeye ve kime inanmaya çağırır?',
      },
    ],
  },
];

