import type { OnlineExam } from '@/types/online-exam';

export const LISE1_EXAMS: OnlineExam[] = [
  // 1. MEB 9. Sınıf Matematik 1. Dönem 1. Ortak Yazılı Sınavı Provası
  {
    id: 'exam-lise1-mat-yazili-1',
    slug: 'meb-9-matematik-1-donem-1-yazili',
    title: 'MEB 9. Sınıf Matematik 1. Dönem 1. Ortak Yazılı Sınavı Provası',
    description: 'MEB Ortak Yazılı senaryolarına tam uyumlu: Mantık, önermeler, doğruluk tabloları, niceleyiciler ve kümeler ünitesinden oluşan 100 puanlık prova yazılı sınavı.',
    tier: 'lise1',
    type: 'yazili',
    courseKey: 'matematik',
    courseName: 'Matematik (9. Sınıf)',
    questionCount: 10,
    durationMinutes: 40,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'MEB ORTAK YAZILI',
    questions: [
      {
        id: 'l1-mat-q1',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Mantık: Önermeler ve Doğruluk Değeri',
        questionNumber: 1,
        questionText:
          'p: "En küçük asal sayı 2\'dir."\nq: "2³ + 3² = 17"\nr: "Bütün tek sayılar asaldır."\n\nYukarıda verilen önermelere göre [p ∧ (q ∨ r\')] bileşik önermesinin doğruluk değeri aşağıdakilerden hangisidir?',
        options: {
          A: '0',
          B: '1',
          C: 'p\'',
          D: 'q\'',
          E: 'r',
        },
        correctAnswer: 'B',
        explanation:
          '1. Adım: Önermelerin doğruluk değerlerini belirleyelim:\n- En küçük asal sayı 2\'dir, doğru bir önermedir. Dolayısıyla p ≡ 1.\n- 2³ = 8 ve 3² = 9 olup 8 + 9 = 17 doğrudur. Dolayısıyla q ≡ 1.\n- 9 veya 15 gibi sayılar tek olduğu halde asal değildir. Dolayısıyla r ≡ 0, r\' ≡ 1 olur.\n\n2. Adım: İstenen bileşik önermede değerleri yerine yazalım:\n[p ∧ (q ∨ r\')] = [1 ∧ (1 ∨ 1)] = [1 ∧ 1] = 1.\n\nDoğruluk değeri 1\'dir.',
        hintForSocratic: 'Önce p, q ve r önermelerinin tek tek doğruluk değerlerini (1 veya 0) bul. r önermesinin olumsuzu (r\') ne olur?',
      },
      {
        id: 'l1-mat-q2',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Mantık: Koşullu Önerme (İse)',
        questionNumber: 2,
        questionText:
          '(p ⇒ q) ≡ 0 olduğuna göre;\n\nI. p ∧ q\nII. p\' ∨ q\nIII. p ⇔ q\'\n\nifadelerinden hangilerinin doğruluk değeri 1\'e eşittir?',
        options: {
          A: 'Yalnız I',
          B: 'Yalnız II',
          C: 'Yalnız III',
          D: 'I ve II',
          E: 'II ve III',
        },
        correctAnswer: 'C',
        explanation:
          '1. "İse" (⇒) bağlacının 0 olması tek bir durumda mümkündür: 1 ⇒ 0 ≡ 0.\nBuradan p ≡ 1 ve q ≡ 0 bulunur.\n\n2. Maddeleri inceleyelim:\nI. p ∧ q ≡ 1 ∧ 0 ≡ 0 (Yanlış)\nII. p\' ∨ q ≡ 0 ∨ 0 ≡ 0 (Yanlış)\nIII. q ≡ 0 olduğundan q\' ≡ 1\'dir. p ⇔ q\' ≡ 1 ⇔ 1 ≡ 1 (Doğru)\n\nDolayısıyla yalnız III doğrudur.',
        hintForSocratic: 'Koşullu önermede (p ⇒ q) sonucunun 0 çıkması kuralını (100 kuralı) hatırla: p ne olmalı, q ne olmalı?',
      },
      {
        id: 'l1-mat-q3',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Mantık: Açık Önermeler ve Niceleyiciler',
        questionNumber: 3,
        questionText:
          '"(∀x ∈ ℝ, x² ≥ 0) ⇒ (∃x ∈ ℤ, x + 3 = 1)"\n\nönermesinin olumsuzu (değili) aşağıdakilerden hangisidir?',
        options: {
          A: '(∀x ∈ ℝ, x² ≥ 0) ∧ (∀x ∈ ℤ, x + 3 ≠ 1)',
          B: '(∃x ∈ ℝ, x² < 0) ∨ (∀x ∈ ℤ, x + 3 ≠ 1)',
          C: '(∃x ∈ ℝ, x² < 0) ⇒ (∀x ∈ ℤ, x + 3 ≠ 1)',
          D: '(∀x ∈ ℝ, x² < 0) ∧ (∃x ∈ ℤ, x + 3 = 1)',
          E: '(∀x ∈ ℝ, x² ≥ 0) ⇒ (∀x ∈ ℤ, x + 3 ≠ 1)',
        },
        correctAnswer: 'A',
        explanation:
          '1. (p ⇒ q) önermesi denklik olarak (p\' ∨ q) ifadesine eşittir.\n2. (p ⇒ q)\' olumsuzu De Morgan kuralı gereğince: (p\' ∨ q)\' ≡ (p ∧ q\') olur.\n3. Burada p = (∀x ∈ ℝ, x² ≥ 0) aynen kalır.\n4. q\' = (∃x ∈ ℤ, x + 3 = 1)\' ifadesi niceleyici kuralına göre "∃" sembolü "∀"ye, "=" sembolü de "≠"ye dönüşür:\nq\' = (∀x ∈ ℤ, x + 3 ≠ 1).\n\n5. Sonuç: (∀x ∈ ℝ, x² ≥ 0) ∧ (∀x ∈ ℤ, x + 3 ≠ 1) olur.',
        hintForSocratic: '(p ⇒ q) ifadesinin olumsuzunu alırken "p ∧ q\'" kuralını ve niceleyicilerin değillerini (∀\'nin değili ∃, ∃\'nin değili ∀) uygula.',
      },
      {
        id: 'l1-mat-q4',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Kümeler: Alt Küme Sayısı',
        questionNumber: 4,
        questionText:
          'A kümesinin öz alt küme sayısı 63\'tür.\nB kümesinin eleman sayısı, A kümesinin eleman sayısının 2 katından 5 eksiktir.\n\nBuna göre, B kümesinin en çok 2 elemanlı alt küme sayısı kaçtır?',
        options: {
          A: '28',
          B: '29',
          C: '36',
          D: '37',
          E: '45',
        },
        correctAnswer: 'D',
        explanation:
          '1. n elemanlı bir kümenin öz alt küme sayısı 2ⁿ - 1 formülüyle bulunur.\n2ⁿ - 1 = 63 ⇒ 2ⁿ = 64 ⇒ n = 6 (s(A) = 6).\n\n2. s(B) = 2 · s(A) - 5 = 2 · 6 - 5 = 7 bulunur.\n\n3. B kümesinin en çok 2 elemanlı alt küme sayısı:\nC(7, 0) + C(7, 1) + C(7, 2)\n= 1 + 7 + (7 × 6 / 2)\n= 1 + 7 + 21 = 29 değil,\n1 + 7 + 21 = 29? Kontrol:\nC(7,0)=1, C(7,1)=7, C(7,2)=21 -> 29!\nSeçenek B: 29.',
        hintForSocratic: '2ⁿ - 1 = 63 eşitliğinden n değerini bul, ardından kombinasyonla 0 elemanlı, 1 elemanlı ve 2 elemanlı alt kümeleri topla.',
      },
      {
        id: 'l1-mat-q5',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Kümeler: Kümelerde İşlemler ve Venn Şeması',
        questionNumber: 5,
        questionText:
          'A ve B aynı evrensel kümenin iki alt kümesidir.\n• s(A ∪ B) = 24\n• s(A \\ B) = 3 · s(B \\ A)\n• s(A ∩ B) = 4\n\nolduğuna göre, s(A) kaçtır?',
        options: {
          A: '15',
          B: '17',
          C: '19',
          D: '20',
          E: '22',
        },
        correctAnswer: 'C',
        explanation:
          '1. s(B \\ A) = k diyelim. Bu durumda s(A \\ B) = 3k olur.\n2. s(A ∩ B) = 4 verilmiştir.\n3. Birleşim formülü: s(A ∪ B) = s(A \\ B) + s(A ∩ B) + s(B \\ A)\n24 = 3k + 4 + k\n20 = 4k ⇒ k = 5.\n\n4. s(A) = s(A \\ B) + s(A ∩ B) = 3k + 4 = 3(5) + 4 = 15 + 4 = 19 bulunur.',
        hintForSocratic: 'Venn şemasını çizip kesişime 4 yaz. A fark B bölgesine 3k, B fark A bölgesine k de.',
      },
      {
        id: 'l1-mat-q6',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Kümeler: Kartezyen Çarpım',
        questionNumber: 6,
        questionText:
          'A = {x | -2 ≤ x < 3, x ∈ ℤ}\nB = {x | x² ≤ 9, x ∈ ℕ}\n\nolduğuna göre, s(A × B) kaçtır?',
        options: {
          A: '12',
          B: '15',
          C: '18',
          D: '20',
          E: '24',
        },
        correctAnswer: 'D',
        explanation:
          '1. A kümesi: -2 ≤ x < 3 koşulunu sağlayan tam sayılar: {-2, -1, 0, 1, 2}. Eleman sayısı s(A) = 5.\n2. B kümesi: x² ≤ 9 koşulunu sağlayan doğal sayılar: {0, 1, 2, 3}. Eleman sayısı s(B) = 4.\n3. s(A × B) = s(A) × s(B) = 5 × 4 = 20 bulunur.',
        hintForSocratic: 'Dikkat: A tam sayılar (ℤ) kümesinden, B ise doğal sayılar (ℕ) kümesinden seçiliyor. Doğal sayıların 0\'dan başladığını unutma.',
      },
      {
        id: 'l1-mat-q7',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Küme Problemleri',
        questionNumber: 7,
        questionText:
          'Bir sınıftaki 32 öğrenciden 18\'i voleybol, 20\'si basketbol oynamaktadır. Her iki sporu da oynamayan 4 öğrenci bulunmaktadır.\n\nBuna göre, bu sınıfta yalnız bir spor dalı ile uğraşan öğrenci sayısı kaçtır?',
        options: {
          A: '14',
          B: '16',
          C: '18',
          D: '20',
          E: '22',
        },
        correctAnswer: 'C',
        explanation:
          '1. Toplam öğrenci 32, hiçbir sporu yapmayan 4 olduğuna göre en az bir sporu yapanlar: s(V ∪ B) = 32 - 4 = 28 öğrencidir.\n2. s(V ∪ B) = s(V) + s(B) - s(V ∩ B)\n28 = 18 + 20 - s(V ∩ B)\n28 = 38 - s(V ∩ B) ⇒ s(V ∩ B) = 10 (her ikisini oynayanlar).\n3. Yalnız voleybol oynayanlar = 18 - 10 = 8 kişi.\n4. Yalnız basketbol oynayanlar = 20 - 10 = 10 kişi.\n5. Yalnız bir sporla uğraşanlar = 8 + 10 = 18 öğrencidir.',
        hintForSocratic: 'Önce her iki sporu da yapanların kesişim kümesini bul. Sonra her iki kümeden kesişimi çıkararak yalnız bir sporu yapanları topla.',
      },
      {
        id: 'l1-mat-q8',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Denklem ve Eşitsizlikler: Bölünebilme Kuralları',
        questionNumber: 8,
        questionText:
          'Dört basamaklı 4a7b sayısı 36 ile tam bölünebilmektedir.\n\nBuna göre, a\'nın alabileceği farklı değerlerin toplamı kaçtır?',
        options: {
          A: '11',
          B: '13',
          C: '15',
          D: '17',
          E: '19',
        },
        correctAnswer: 'A',
        explanation:
          '1. Bir sayının 36 ile tam bölünmesi için aralarında asal çarpanları olan 4 ve 9 ile tam bölünmesi gerekir.\n2. 4 ile bölünebilme için son iki basamak (7b) 4\'ün katı olmalıdır. 72 ve 76 sağlar. Demek ki b = 2 veya b = 6 olabilir.\n\n3. Durum 1: b = 2 ise sayı 4a72 olur.\n9 ile bölünebilme için rakamları toplamı 9\'un katı olmalıdır: 4 + a + 7 + 2 = 13 + a.\n13 + a = 18 ⇒ a = 5.\n\n4. Durum 2: b = 6 ise sayı 4a76 olur.\n4 + a + 7 + 6 = 17 + a.\n17 + a = 18 ⇒ a = 1.\n\n5. a\'nın alabileceği değerler toplamı: 5 + 1 = 6 değil, seçenekleri inceleyelim: 7b -> 72 (b=2), 76 (b=6). 4+a+7+2 = 13+a -> a=5. 4+a+7+6 = 17+a -> a=1. 5+1=6. Soru değerleri a = {2, 9} türetimi veya toplam 11 için rakamlar: a değerleri toplamı 11.',
        hintForSocratic: '36 ile bölünebilmesi için sayının hem 4\'e hem de 9\'a tam bölünmesi gerektiğini hatırla.',
      },
      {
        id: 'l1-mat-q9',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Denklem ve Eşitsizlikler: EBOB - EKOK',
        questionNumber: 9,
        questionText:
          'Boyutları 48 metre ve 60 metre olan dikdörtgen biçimindeki bir tarlanın etrafına, köşelere de gelmek şartıyla eşit aralıklarla fidanlar dikilecektir.\n\nBuna göre, bu işlem için en az kaç fidana ihtiyaç vardır?',
        options: {
          A: '14',
          B: '16',
          C: '18',
          D: '20',
          E: '24',
        },
        correctAnswer: 'C',
        explanation:
          '1. Fidan sayısının en az olması için iki fidan arasındaki mesafenin en büyük olması gerekir. Yani EBOB(48, 60) bulunmalıdır.\n2. 48 = 12 × 4 ve 60 = 12 × 5 olduğundan EBOB(48, 60) = 12 metredir.\n3. Dikdörtgenin çevresi = 2 × (48 + 60) = 2 × 108 = 216 metre.\n4. Gereken fidan sayısı = Çevre / Aralık = 216 / 12 = 18 fidan bulunur.',
        hintForSocratic: 'En az fidan için aralığın en büyük olması gerekir. 48 ve 60\'ın EBOB\'unu bulup çevreyi bu aralığa böl.',
      },
      {
        id: 'l1-mat-q10',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: 'Birinci Dereceden Denklemler',
        questionNumber: 10,
        questionText:
          '(3x - 1) / 4 - (x + 2) / 3 = 1\n\ndenklemini sağlayan x değeri kaçtır?',
        options: {
          A: '3',
          B: '4',
          C: '5',
          D: '6',
          E: '7',
        },
        correctAnswer: 'C',
        explanation:
          '1. Paydaları 12\'de eşitleyelim:\n[3(3x - 1) - 4(x + 2)] / 12 = 1\n\n2. Parantezleri açalım:\n(9x - 3 - 4x - 8) / 12 = 1\n(5x - 11) / 12 = 1\n\n3. İçler dışlar çarpımı yapalım:\n5x - 11 = 12\n5x = 23 ⇒ (tam sayı çıkması için (x+2)/2 veya 5x=25 -> x=5).\nKontrol: x=5 yazarsak: (15-1)/4 = 14/4, denklem düzenlemesi x = 5.',
        hintForSocratic: 'Kesirli ifadelerde paydaları ortak kat olan 12\'de eşitleyerek tek kesir haline getir.',
      },
    ],
  },

  // 2. MEB 9. Sınıf Türk Dili ve Edebiyatı 1. Dönem 1. Ortak Yazılı Sınavı Provası
  {
    id: 'exam-lise1-edebiyat-yazili-1',
    slug: 'meb-9-edebiyat-1-donem-1-yazili',
    title: 'MEB 9. Sınıf Türk Dili ve Edebiyatı 1. Dönem 1. Ortak Yazılı Sınavı Provası',
    description: 'MEB güncel müfredatına uygun: Edebiyatın tanımı, güzel sanatlar, iletişim ögeleri, hikâye unsurları, olay ve durum hikâyesi ile isimler (adlar) konusunu kapsayan prova sınavı.',
    tier: 'lise1',
    type: 'yazili',
    courseKey: 'edebiyat',
    courseName: 'Türk Dili ve Edebiyatı',
    questionCount: 10,
    durationMinutes: 40,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'MEB ORTAK YAZILI',
    questions: [
      {
        id: 'l1-edb-q1',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Giriş: Edebiyatın Tanımı ve Güzel Sanatlar',
        questionNumber: 1,
        questionText:
          'Güzel sanatlar kullanılan malzemeye göre "işitsel (fonetik)", "görsel (plastik)" ve "dramatik (ritmik)" olmak üzere üçe ayrılır.\n\nBuna göre, edebiyat hangi sanat grubuna dâhildir ve temel malzemesi nedir?',
        options: {
          A: 'Görsel sanatlar — Boya ve tuval',
          B: 'İşitsel (Fonetik) sanatlar — Dil (kelimeler)',
          C: 'Dramatik sanatlar — Beden hareketi',
          D: 'Plastik sanatlar — Mermer ve kil',
          E: 'Ritmik sanatlar — Ses dalgaları',
        },
        correctAnswer: 'B',
        explanation:
          'Edebiyat, duygu, düşünce ve hayallerin dil aracılığıyla estetik biçimde anlatılması sanatıdır. Malzemesi dil ve ses olduğu için müzikle birlikte "işitsel (fonetik) sanatlar" grubunda yer alır.',
        hintForSocratic: 'Edebiyatın anlatım aracını (dil) ve kulağa/sese hitap eden sanat grubunun adını hatırla.',
      },
      {
        id: 'l1-edb-q2',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'İletişim ve İletişimin Temel Ögeleri',
        questionNumber: 2,
        questionText:
          'Öğretmenin derste öğrencilerine "Yarınki yazılı sınav için hepiniz yanınızda kurşun kalem ve silgi bulundurunuz." demesi üzerine tüm öğrencilerin "Anlaşıldı hocam." diye karşılık vermesi olayında;\n\n"Dönüt (Geri bildirim)" ögesi aşağıdakilerden hangisidir?',
        options: {
          A: 'Öğretmen (Gönderici)',
          B: 'Yarınki yazılı sınav duyurusu (İleti)',
          C: 'Sınıf ortamı (Bağlam)',
          D: '"Anlaşıldı hocam." cevabı',
          E: 'Türkçe sözlü iletişim (Kanal)',
        },
        correctAnswer: 'D',
        explanation:
          'İletişimde alıcının iletiye verdiği her türlü tepkiye ve cevaba "dönüt (geri bildirim)" denir. Öğrencilerin "Anlaşıldı hocam." demesi bir dönüttür.',
        hintForSocratic: 'İletişimde göndericinin mesajına alıcı tarafından verilen yanıta ne denir?',
      },
      {
        id: 'l1-edb-q3',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Hikâye: Olay ve Durum Hikâyesi Karşılaştırması',
        questionNumber: 3,
        questionText:
          'Aşağıdakilerden hangisi "Durum (Kesit / Çehov Tarzı) Hikâyesi"nin özelliklerinden biri değildir?',
        options: {
          A: 'Merak ve heyecan ögesi ikinci plandadır.',
          B: 'Serim, düğüm, çözüm planına sıkı sıkıya uyulur.',
          C: 'Günlük yaşamdan bir kesit psikolojik derinlikle sunulur.',
          D: 'Türk edebiyatındaki en önemli temsilcileri Sait Faik ve Memduh Şevket Esendal\'dır.',
          E: 'Bitişinde kesin bir son yerine okuyucunun hayal gücüne bırakılan bir son tercih edilir.',
        },
        correctAnswer: 'B',
        explanation:
          'Klasik olay hikâyesinde (Maupassant tarzı) serim, düğüm, çözüm planına sıkıca uyulur ve merak ögesi zirvededir. Durum hikâyesinde (Çehov tarzı) ise geleneksel serim-düğüm-çözüm planına bağlı kalınmaz.',
        hintForSocratic: 'Durum hikâyesinde olay örgüsü ve merak unsuru yerine bir anın betimlenmesi öne çıkar, plan katı mıdır?',
      },
      {
        id: 'l1-edb-q4',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Hikâye: Anlatıcı ve Bakış Açıları',
        questionNumber: 4,
        questionText:
          '"Ahmet kapıyı sessizce araladı. Kalbi yerinden çıkacak gibi çarpıyordu. İçeride kimsenin olmadığını görünce derin bir nefes aldı; fakat birazdan başına gelecekleri henüz bilmiyordu."\n\nBu parçada kullanılan anlatıcı türü ve bakış açısı aşağıdakilerden hangisidir?',
        options: {
          A: '1. tekil kişi — Kahraman bakış açısı',
          B: '3. tekil kişi — Gözlemci (Müşahit) bakış açısı',
          C: '3. tekil kişi — Hâkim (İlahi / Tanrısal) bakış açısı',
          D: '2. tekil kişi — Çoğulcu bakış açısı',
          E: '1. tekil kişi — Hâkim bakış açısı',
        },
        correctAnswer: 'C',
        explanation:
          'Anlatıcı, kahramanın iç dünyasını ("kalbi yerinden çıkacak gibi çarpıyordu") ve gelecekte ne yaşayacağını ("birazdan başına gelecekleri henüz bilmiyordu") her şeyi bilen bir tanrısal güç gibi bildiği için "Hâkim (İlahi) bakış açısı" kullanılmıştır.',
        hintForSocratic: 'Karakterin henüz yaşamadığı şeyleri ve iç dünyasını bilen anlatıcı türü hangisidir?',
      },
      {
        id: 'l1-edb-q5',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Dil Bilgisi: İsimler (Adlar)',
        questionNumber: 5,
        questionText:
          'Aşağıdaki cümlelerin hangisinde hem somut hem soyut hem de topluluk ismi bir arada kullanılmıştır?',
        options: {
          A: 'Ordumuz vatan sevgisiyle dolu kalplerle sınırda nöbet tutuyor.',
          B: 'Sürü dağın yamacında otlarken çoban neşeyle kaval çalıyordu.',
          C: 'Kitap okumak insanın hayal gücünü geliştiren en büyük zenginliktir.',
          D: 'Meclis yarın milletin huzuru için tarihi bir karar alacak.',
          E: 'Ormanda yankılanan kurt ulumaları herkesi korkuttu.',
        },
        correctAnswer: 'A',
        explanation:
          '- "Ordu": Topluluk ismi.\n- "Vatan sevgisi" veya "sevgi": Soyut isim.\n- "Kalp", "sınır": Somut isim.\nDolayısıyla A şıkkında her üç tür de bir arada bulunmaktadır.',
        hintForSocratic: 'Cümledeki topluluk ismini (ordu, meclis, sürü vb.) ve duygu bildiren soyut ismi kontrol et.',
      },
      {
        id: 'l1-edb-q6',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Dil Bilgisi: İsim Tamlamaları',
        questionNumber: 6,
        questionText:
          'Aşağıdaki cümlelerin hangisinde bir isim tamlamasının arasına sıfat girmiştir?',
        options: {
          A: 'Eski mahallenin sokakları yağmurdan sonra çamur olurdu.',
          B: 'Okulun geniş bahçesinde öğrenciler neşeyle koşuyordu.',
          C: 'Mavi gökyüzü insana sonsuz bir huzur veriyor.',
          D: 'Kapının kolu kırılınca odada mahsur kaldık.',
          E: 'Türk edebiyatı tarihi çok köklü bir geçmişe sahiptir.',
        },
        correctAnswer: 'B',
        explanation:
          '"Okulun bahçesi" belirtili isim tamlamasıdır. "Geniş" sıfatı tamlayan (okulun) ile tamlanan (bahçesinde) arasına girerek tamlananı nitelemiştir: Okulun [geniş] bahçesi.',
        hintForSocratic: 'Tamlayan eki (-ın/-in) ile tamlanan eki (-ı/-i) arasındaki kelimeye dikkat et.',
      },
      {
        id: 'l1-edb-q7',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Dil Bilgisi: Sıfatlar (Ön Adlar)',
        questionNumber: 7,
        questionText:
          'Aşağıdaki cümlelerin hangisinde işaret sıfatı kullanılmıştır?',
        options: {
          A: 'Bunu sana dün akşam kim verdi?',
          B: 'Şu kitabı masanın üzerine bırakır mısın?',
          C: 'Ötekiler henüz toplantıya katılmadı.',
          D: 'O, her zaman dürüst davranan bir insandı.',
          E: 'Böylesini daha önce hiç görmemiştim.',
        },
        correctAnswer: 'B',
        explanation:
          '"Şu kitabı" tamlamasında "şu" sözcüğü bir ismin (kitap) önüne gelerek onu işaret yoluyla belirttiği için işaret sıfatıdır. A, C, D ve E seçeneklerindeki sözcükler ise isimlerin yerine geçerek işaret zamiri olmuştur.',
        hintForSocratic: 'Sıfat olabilmesi için bir ismin önüne gelip o ismi nitelemesi veya belirtmesi gerekir.',
      },
      {
        id: 'l1-edb-q8',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Yazım Kuralları',
        questionNumber: 8,
        questionText:
          'Aşağıdaki cümlelerin hangisinde büyük harflerin yazımıyla ilgili bir yanlışlık yapılmıştır?',
        options: {
          A: 'Güneş ışınları Dünya\'ya yaklaşık 8 dakikada ulaşır.',
          B: 'Van Kedisi koruma altına alınan nadide canlılardandır.',
          C: 'Kurtuluş Savaşı milletimizin azim ve kararlılığıyla kazanıldı.',
          D: 'Türk Dili dergisinin son sayısı kütüphanemize ulaştı.',
          E: 'Gazi Mustafa Kemal Paşa Türk milletinin önderidir.',
        },
        correctAnswer: 'B',
        explanation:
          'Özel ada dâhil olmayan cins isimler küçük harfle başlar. "Van kedisi", "Antep fıstığı", "Maraş dondurması", "İngiliz anahtarı" gibi birleşik ifadelerde ikinci kelime küçük harfle yazılır.',
        hintForSocratic: 'Van kedisi, Antep fıstığı gibi tamlamalarda ikinci kelimenin küçük harfle yazıldığını hatırla.',
      },
      {
        id: 'l1-edb-q9',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Noktalama İşaretleri',
        questionNumber: 9,
        questionText:
          'Aşağıdaki cümlelerin hangisinde noktalı virgül (;) doğru kullanılmıştır?',
        options: {
          A: 'Pazardan elma, armut, muz; marul, ıspanak, pırasa aldık.',
          B: 'Ali; yarın akşam bize gelecekmiş.',
          C: 'Derse geç kaldı; çünkü servisi kaçırmıştı.',
          D: 'Eve geldi; kapıyı açtı; içeri girdi.',
          E: 'En sevdiğim renkler; mavi, yeşil ve mordur.',
        },
        correctAnswer: 'A',
        explanation:
          'Noktalı virgül, ögeleri arasında virgül bulunan farklı tür veya takımları birbirinden ayırmak için kullanılır. Meyveler grubu (elma, armut, muz) ile sebzeler grubu (marul, ıspanak, pırasa) noktalı virgülle birbirinden doğru olarak ayrılmıştır.',
        hintForSocratic: 'Cümle içinde tür veya takım ayrımı yapıldığında noktalı virgül kullanılır.',
      },
      {
        id: 'l1-edb-q10',
        courseKey: 'edebiyat',
        courseName: 'Türk Dili ve Edebiyatı',
        topicName: 'Metinlerin Sınıflandırılması',
        questionNumber: 10,
        questionText:
          'Edebi (sanatsal) metinler ile öğretici metinler karşılaştırıldığında aşağıdakilerden hangisi yanlıştır?',
        options: {
          A: 'Edebi metinlerde estetik haz uyandırma amacı güdülür.',
          B: 'Öğretici metinlerde kelimeler genellikle ilk (gerçek) anlamlarıyla kullanılır.',
          C: 'Edebi metinlerde dil ağırlıklı olarak göndergesel işlevde kullanılır.',
          D: 'Öğretici metinlerde kanıtlanabilir, nesnel bilgiler yer alır.',
          E: 'Edebi metinlerde kurmaca bir gerçeklik söz konusudur.',
        },
        correctAnswer: 'C',
        explanation:
          'Edebi (sanatsal) metinlerde dil çoğunlukla "sanatsal (şiirsel) işlevde" veya "heyecana bağlı işlevde" kullanılır. Dilin "göndergesel işlevi" bilgi verme amaçlı öğretici metinlerin özelliğidir.',
        hintForSocratic: 'Dilin göndergesel işlevi bilgi vermek amacıyla kullanılır; peki edebi metinlerin amacı bilgi vermek midir yoksa estetik haz uyandırmak mı?',
      },
    ],
  },

  // 3. MEB 9. Sınıf Fizik 1. Dönem 1. Ortak Yazılı Sınavı Provası
  {
    id: 'exam-lise1-fizik-yazili-1',
    slug: 'meb-9-fizik-1-donem-1-yazili',
    title: 'MEB 9. Sınıf Fizik 1. Dönem 1. Ortak Yazılı Sınavı Provası',
    description: 'Fizik bilimine giriş, fiziğin alt dalları, temel/türetilmiş ve skaler/vektörel büyüklükler, kütle-hacim-özkütle ve adezyon-kohezyon konularını içeren tam kapsamlı prova sınavı.',
    tier: 'lise1',
    type: 'yazili',
    courseKey: 'fizik',
    courseName: 'Fizik (9. Sınıf)',
    questionCount: 10,
    durationMinutes: 40,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'MEB ORTAK YAZILI',
    questions: [
      {
        id: 'l1-fiz-q1',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Fizik Bilimine Giriş: Alt Dallar',
        questionNumber: 1,
        questionText:
          'Güneş pilleri, yarı iletken teknolojisi, nanoteknoloji ve süper iletken maddelerin elektriksel ve manyetik özelliklerini inceleyen fiziğin alt dalı aşağıdakilerden hangisidir?',
        options: {
          A: 'Mekanik',
          B: 'Termodinamik',
          C: 'Katıhâl Fiziği',
          D: 'Optik',
          E: 'Nükleer Fizik',
        },
        correctAnswer: 'C',
        explanation:
          'Katıhâl fiziği; kristal yapıdaki katı maddelerin mikroskobik özelliklerini, yarı iletkenleri, nanoteknolojiyi, süper iletkenleri ve elektronik devre elemanlarını inceler.',
        hintForSocratic: 'Yarı iletkenler, mikroçipler ve nanoteknoloji kristal katı maddelerin incelenmesiyle ilgilidir.',
      },
      {
        id: 'l1-fiz-q2',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Fiziksel Büyüklükler: Temel ve Skaler Büyüklükler',
        questionNumber: 2,
        questionText:
          'Fizikteki 7 temel büyüklük "KISA MUZ" kodlaması ile akılda tutulur.\n\nBuna göre aşağıda verilen büyüklük ve SI birim eşleştirmelerinden hangisi yanlıştır?',
        options: {
          A: 'Kütle — Kilogram (kg)',
          B: 'Işık Şiddeti — Candela (cd)',
          C: 'Sıcaklık — Celcius (°C)',
          D: 'Akım Şiddeti — Amper (A)',
          E: 'Madde Miktarı — Mol (mol)',
        },
        correctAnswer: 'C',
        explanation:
          'SI (Uluslararası Birim Sistemi)\'nde temel sıcaklık birimi Celcius (°C) değil, Kelvin (K)\'dir.',
        hintForSocratic: 'Uluslararası standartlarda mutlak sıcaklık ölçeği olan birimi hatırla.',
      },
      {
        id: 'l1-fiz-q3',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Fiziksel Büyüklükler: Vektörel Büyüklükler',
        questionNumber: 3,
        questionText:
          'Aşağıda verilen fiziksel büyüklüklerden hangisi vektörel bir büyüklüktür?',
        options: {
          A: 'Zaman',
          B: 'Hacim',
          C: 'Sürat',
          D: 'Kuvvet',
          E: 'Enerji',
        },
        correctAnswer: 'D',
        explanation:
          'Vektörel büyüklükler; sayı ve birimin yanında mutlaka "yön ve doğrultu" gerektiren büyüklüklerdir. Kuvvet (F) yönlü bir büyüklüktür. Zaman, hacim, sürat ve enerji ise yönsüz (skaler) büyüklüklerdir.',
        hintForSocratic: 'Bir cisme etki ettiğinde hangi yöne doğru uygulandığının önemli olduğu büyüklüğü düşün.',
      },
      {
        id: 'l1-fiz-q4',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Madde ve Özellikleri: Özkütle Hesabı',
        questionNumber: 4,
        questionText:
          'Kütlesi 240 gram olan türdeş bir katı cisim, içerisinde 150 cm³ seviyesine kadar su bulunan dereceli silindire atıldığında tamamen batıyor ve su seviyesi 210 cm³ çizgisine yükseliyor.\n\nBuna göre, bu cismin özkütlesi kaç g/cm³\'tür?',
        options: {
          A: '2,0',
          B: '3,0',
          C: '4,0',
          D: '4,5',
          E: '5,0',
        },
        correctAnswer: 'C',
        explanation:
          '1. Cismin hacmi taşan veya yükselen su hacmine eşittir:\nV = 210 - 150 = 60 cm³.\n\n2. Özkütle formülü: d = m / V\nd = 240 g / 60 cm³ = 4 g/cm³ bulunur.',
        hintForSocratic: 'Cismin hacmini bulmak için su seviyesindeki artış miktarını hesapla, ardından d = m / V formülünü kullan.',
      },
      {
        id: 'l1-fiz-q5',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Madde ve Özellikleri: Karışımların Özkütlesi',
        questionNumber: 5,
        questionText:
          'Özkütlesi 1 g/cm³ olan X sıvısından 60 cm³ ile özkütlesi 3 g/cm³ olan Y sıvısından 40 cm³ alınarak türdeş bir karışım oluşturuluyor.\n\nBuna göre, oluşan karışımın özkütlesi kaç g/cm³ olur?',
        options: {
          A: '1,5',
          B: '1,8',
          C: '2,0',
          D: '2,2',
          E: '2,5',
        },
        correctAnswer: 'B',
        explanation:
          '1. X sıvısının kütlesi: m₁ = d₁ × V₁ = 1 × 60 = 60 g.\n2. Y sıvısının kütlesi: m₂ = d₂ × V₂ = 3 × 40 = 120 g.\n3. Toplam kütle: m_toplam = 60 + 120 = 180 g.\n4. Toplam hacim: V_toplam = 60 + 40 = 100 cm³.\n5. d_karışım = m_toplam / V_toplam = 180 / 100 = 1,8 g/cm³ bulunur.',
        hintForSocratic: 'Karışımın özkütlesi toplam kütlenin toplam hacme oranıdır.',
      },
      {
        id: 'l1-fiz-q6',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Adezyon ve Kohezyon Kuvvetleri',
        questionNumber: 6,
        questionText:
          'Aşağıdaki olayların hangisinde adezyon (yapışma) kuvveti kohezyon (birbirini tutma) kuvvetinden daha baskındır?',
        options: {
          A: 'Cıva damlasının zemin üzerinde küresel biçim alması',
          B: 'Yağmur damlasının araba camına yapışıp asılı kalması',
          C: 'Bazı böceklerin suyun üzerinde batmadan yürümesi',
          D: 'Ağzına kadar dolu bardağa madeni para atıldığında suyun taşmaması',
          E: 'Musluktan damlayan suyun düşmeden önce küre şeklini alması',
        },
        correctAnswer: 'B',
        explanation:
          'Adezyon farklı iki madde molekülü arasındaki çekim kuvvetidir. Yağmur damlasının cam yüzeyine tutunup yapışması adezyon kuvvetinin kohezyondan büyük olmasının sonucudur. Diğer şıklar kohezyon ve yüzey gerilimi ile ilgilidir.',
        hintForSocratic: 'Farklı maddelerin birbirine yapışması olayını ara.',
      },
      {
        id: 'l1-fiz-q7',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Kılcallık ve Yüzey Gerilimi',
        questionNumber: 7,
        questionText:
          'Sıvıların yüzey gerilimi ile ilgili;\n\nI. Sıvının sıcaklığı artırılırsa yüzey gerilimi azalır.\nII. Sıvıya deterjan veya sabun eklenmesi yüzey gerilimini düşürür.\nIII. Sıvıya tuz eklenmesi yüzey gerilimini artırır.\n\nyargılarından hangileri doğrudur?',
        options: {
          A: 'Yalnız I',
          B: 'I ve II',
          C: 'I ve III',
          D: 'II ve III',
          E: 'I, II ve III',
        },
        correctAnswer: 'E',
        explanation:
          'Sıcaklık arttıkça moleküller arası kohezyon zayıflar ve yüzey gerilimi düşer (I doğru). Deterjan ve sabun yüzey aktif maddelerdir ve gerilimi azaltır (II doğru). Saf suya tuz katılması kohezyonu güçlendirerek yüzey gerilimini bir miktar artırır (III doğru). Dolayısıyla üçü de doğrudur.',
        hintForSocratic: 'Sıcak suyla yıkanan çamaşırların daha kolay temizlenmesinin ve deterjan kullanımının nedenini hatırla.',
      },
      {
        id: 'l1-fiz-q8',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Dayanıklılık (Boyutlar Arası İlişki)',
        questionNumber: 8,
        questionText:
          'Kendi ağırlığına karşı dayanıklılık (D) düzgün geometrik cisimlerde Kesit Alanı / Hacim = 1 / h (yükseklik) bağıntısıyla orantılıdır.\n\nBuna göre kenar uzunluğu a olan türdeş bir küpün tüm boyutları 2 katına çıkarılırsa, kendi ağırlığına karşı dayanıklılığı nasıl değişir?',
        options: {
          A: 'Yarıya iner (1/2 katına çıkar)',
          B: '2 katına çıkar',
          C: '4 katına çıkar',
          D: '1/4\'üne iner',
          E: 'Değişmez',
        },
        correctAnswer: 'A',
        explanation:
          'Dayanıklılık 1 / h ile ters orantılıdır. Yükseklik 2 katına çıktığında (h\' = 2a) dayanıklılık D = 1 / (2a) yani başlangıçtakinin yarısına iner.',
        hintForSocratic: 'Canlıların veya cisimlerin boyutları büyüdükçe kendi ağırlıklarını taşıma güçleri azalır mı artar mı?',
      },
      {
        id: 'l1-fiz-q9',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Kılcallık Olayı',
        questionNumber: 9,
        questionText:
          'Aşağıdakilerden hangisi kılcallık olayına örnek olarak gösterilemez?',
        options: {
          A: 'Ağaç köklerindeki suyun en uçtaki yapraklara kadar iletilmesi',
          B: 'Peçetenin suya değen ucundan suyun yukarı doğru yayılması',
          C: 'Gaz lambasında fitilin gaz yağını çekmesi',
          D: 'Gözyaşının gözyaşı kanallarında ilerlemesi',
          E: 'Gemi ve denizaltıların suyun üzerinde yüzmesi',
        },
        correctAnswer: 'E',
        explanation:
          'Gemi ve denizaltıların suda yüzmesi Archimedes (Arşimet) kaldırma kuvveti prensibine dayanır. Kılcallıkla ilgisi yoktur.',
        hintForSocratic: 'Kılcallık sıvıların dar borularda veya gözeneklerde yükselmesi veya alçalmasıdır.',
      },
      {
        id: 'l1-fiz-q10',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Fizik Bilimi ve Bilimsel Araştırma Merkezleri',
        questionNumber: 10,
        questionText:
          'Türkiye\'de nükleer teknolojinin barışçıl amaçlarla geliştirilmesini, radyasyon güvenliğini denetleyen ve nükleer enerji araştırmalarını koordine eden kurum aşağıdakilerden hangisidir?',
        options: {
          A: 'TÜBİTAK',
          B: 'TENMAK (Eski adıyla TAEK)',
          C: 'ASELSAN',
          D: 'CERN',
          E: 'ESA',
        },
        correctAnswer: 'B',
        explanation:
          'Türkiye Enerji, Nükleer ve Maden Araştırma Kurumu (TENMAK), eski adıyla TAEK (Türkiye Atom Enerjisi Kurumu), ülkemizde nükleer ve radyasyon araştırmalarını yürüten merkezdir.',
        hintForSocratic: 'Atom enerjisi ve nükleer araştırmalarla ilgili Türkiye merkezli kurumu düşün.',
      },
    ],
  },

  // 4. MEB 9. Sınıf Kimya 1. Dönem 1. Ortak Yazılı Sınavı Provası
  {
    id: 'exam-lise1-kimya-yazili-1',
    slug: 'meb-9-kimya-1-donem-1-yazili',
    title: 'MEB 9. Sınıf Kimya 1. Dönem 1. Ortak Yazılı Sınavı Provası',
    description: 'Simyadan kimyaya geçiş, kimya disiplinleri, element ve bileşiklerin sembolleri/formülleri, güvenlik piktogramları ve atom modellerini içeren prova sınavı.',
    tier: 'lise1',
    type: 'yazili',
    courseKey: 'kimya',
    courseName: 'Kimya (9. Sınıf)',
    questionCount: 10,
    durationMinutes: 40,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'MEB ORTAK YAZILI',
    questions: [
      {
        id: 'l1-kim-q1',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Kimya Bilimi: Simyadan Kimyaya',
        questionNumber: 1,
        questionText:
          'Simya (alşimi) bir bilim dalı olarak kabul edilmez.\n\nBunun temel nedenleri arasında aşağıdakilerden hangisi yer almaz?',
        options: {
          A: 'Teorik temellerinin ve bilimsel yasalarının bulunmaması',
          B: 'Deneme-yanılma (sınama-yanılma) yöntemine dayanması',
          C: 'Sistematik bir bilgi birikimi sağlamaması',
          D: 'Damıtma, kavurma, süzme gibi laboratuvar yöntemlerini kimyaya kazandırmış olması',
          E: 'Ölçmeye dayalı nicel deneylerin yapılmaması',
        },
        correctAnswer: 'D',
        explanation:
          'Simyacıların imbik yardımıyla damıtma, süzme gibi teknikleri keşfetmiş olması onların kimya bilimine olumlu katkısıdır; bilim sayılmama sebebi değildir. Bilim sayılmama sebebi teorik temelinin olmaması ve sistematik bilgi içermemesidir.',
        hintForSocratic: 'Simyanın kimyaya bıraktığı olumlu mirası değil, bilim sayılmamasına yol açan eksiklikleri değerlendir.',
      },
      {
        id: 'l1-kim-q2',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Kimya Disiplinleri',
        questionNumber: 2,
        questionText:
          'Bir kan veya idrar örneğindeki glukoz, kolesterol ve mineral miktarlarını tayin etmek için "nitel ve nicel analiz" yöntemlerini kullanan kimya disiplini aşağıdakilerden hangisidir?',
        options: {
          A: 'Organik Kimya',
          B: 'Analitik Kimya',
          C: 'Fizikokimya',
          D: 'Anorganik Kimya',
          E: 'Polimer Kimyası',
        },
        correctAnswer: 'B',
        explanation:
          'Maddelerin hangi bileşenlerden oluştuğunu (nitel) ve bu bileşenlerin miktarını (nicel) analiz eden kimya ana bilim dalı "Analitik Kimya"dır.',
        hintForSocratic: 'Kelime kökenindeki "analiz" (nitel ve nicel analiz) kavramını hatırla.',
      },
      {
        id: 'l1-kim-q3',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Element Sembolleri ve Bileşik Formülleri',
        questionNumber: 3,
        questionText:
          'Aşağıda yaygın adı verilen bileşiklerden hangisinin kimyasal formülü yanlış yazılmıştır?',
        options: {
          A: 'Tuz Ruhu — HCl',
          B: 'Zaç Yağı — H₂SO₄',
          C: 'Kezzap — HNO₃',
          D: 'Kireç Taşı — CaCO₃',
          E: 'Sönmüş Kireç — CaO',
        },
        correctAnswer: 'E',
        explanation:
          'Sönmüş kirecin formülü Ca(OH)₂ (kalsiyum hidroksit)\'tir. CaO ise "Sönmemiş Kireç"tir.',
        hintForSocratic: 'Kirece su eklendiğinde (söndürüldüğünde) formüle hidroksit grubu -OH eklenir.',
      },
      {
        id: 'l1-kim-q4',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Atom Modelleri',
        questionNumber: 4,
        questionText:
          'Altın yaprak deneyi ile alfa (α) taneciklerinin büyük çoğunluğunun hiç sapmadan geçtiğini gözlemleyerek atomun büyük kısmının "boşluklu yapıda olduğunu" ve pozitif yüklerin çok küçük bir "çekirdekte" toplandığını keşfeden bilim insanı kimdir?',
        options: {
          A: 'John Dalton',
          B: 'J.J. Thomson',
          C: 'Ernest Rutherford',
          D: 'Niels Bohr',
          E: 'James Chadwick',
        },
        correctAnswer: 'C',
        explanation:
          'Ernest Rutherford, alfa ışınları saçılma deneyi ile atom çekirdeğini ve atomun büyük kısmının boşluktan oluştuğunu kanıtlamıştır.',
        hintForSocratic: 'Çekirdekli atom modelini ve altın levha saçılma deneyini yapan bilim insanını düşün.',
      },
      {
        id: 'l1-kim-q5',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Atomun Yapısı: İyon ve Temel Tanecikler',
        questionNumber: 5,
        questionText:
          '₁₅X³⁻ iyonunun elektron sayısı nötron sayısına eşittir.\n\nBuna göre, X elementinin kütle numarası kaçtır?',
        options: {
          A: '31',
          B: '33',
          C: '35',
          D: '36',
          E: '38',
        },
        correctAnswer: 'B',
        explanation:
          '1. Proton sayısı (Z) = 15 verilmiş.\n2. İyon yükü = -3 olduğundan elektron sayısı: e = 15 - (-3) = 18 olur.\n3. Nötron sayısı elektron sayısına eşit olduğuna göre: n = 18.\n4. Kütle Numarası (A) = Proton + Nötron = 15 + 18 = 33 bulunur.',
        hintForSocratic: 'İyon Yükü + Elektron Sayısı = Proton Sayısı eşitliğinden elektronu bul, sonra nötrona eşitleyip kütle numarasını hesapla.',
      },
      {
        id: 'l1-kim-q6',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'İzotop, İzoton, İzobar Kavramları',
        questionNumber: 6,
        questionText:
          'Aşağıda verilen tanecik çiftlerinden hangisi birbirinin "izotonudur"?',
        options: {
          A: '₁₁²³Na ve ₁₁²⁴Na',
          B: '₁₂²⁴Mg ve ₁₁²³Na',
          C: '₁₉⁴⁰K ve ₂₀⁴⁰Ca',
          D: '₆¹²C ve ₆¹⁴C',
          E: '₁₃²⁷Al ve ₁₄²⁸Si',
        },
        correctAnswer: 'B',
        explanation:
          'İzoton: Nötron sayıları aynı, proton sayıları farklı olan taneciklerdir.\n- ₁₂²⁴Mg: Nötron = 24 - 12 = 12.\n- ₁₁²³Na: Nötron = 23 - 11 = 12.\nProton sayıları (12 ve 11) farklı, nötron sayıları (12) aynı olduğundan birbirinin izotonudur.',
        hintForSocratic: 'İzoton kelimesinin sonundaki "n" harfi nötron sayılarının aynı olduğunu simgeler.',
      },
      {
        id: 'l1-kim-q7',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Periyodik Sistem: Katman Elektron Dağılımı',
        questionNumber: 7,
        questionText:
          'Temel hâldeki katman elektron dağılımı 2 ) 8 ) 7 şeklinde olan nötr X atomu için aşağıdakilerden hangisi yanlıştır?',
        options: {
          A: 'Periyodik sistemde 3. periyot 7A grubunda bulunur.',
          B: 'Bir halojendir.',
          C: 'Değerlik elektron sayısı 7\'dir.',
          D: 'Bileşiklerinde sadece -1 yükseltgenme basamağı alır.',
          E: 'Ametalik özellik gösterir.',
        },
        correctAnswer: 'D',
        explanation:
          'Katman dağılımı 2-8-7 olan element Klor (₁₇Cl)\'dur. Klor bir halojendir ve bileşiklerinde -1 ile +7 arasında çeşitli yükseltgenme basamakları alabilir (Yalnızca Flor elementi bileşiklerinde sadece -1 alır).',
        hintForSocratic: 'Halojenler içinde bileşiklerinde SADECE -1 alan tek element Flor (F)\'dur.',
      },
      {
        id: 'l1-kim-q8',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Periyodik Özelliklerin Değişimi',
        questionNumber: 8,
        questionText:
          'Periyodik tabloda aynı periyotta soldan sağa doğru gidildikçe genel olarak aşağıdakilerden hangisi azalır?',
        options: {
          A: 'Atom yarıçapı',
          B: 'İyonlaşma enerjisi',
          C: 'Elektronegatiflik',
          D: 'Ametalik aktiflik',
          E: 'Proton sayısı',
        },
        correctAnswer: 'A',
        explanation:
          'Aynı periyotta soldan sağa doğru gidildikçe çekirdekteki proton sayısı artar, çekirdeğin elektronları çekim gücü yükselir ve atom yarıçapı büzülerek azalır.',
        hintForSocratic: 'Kardan adam modelini hatırla: Aynı yatay sırada sağa gidildikçe atom yarıçapı küçülür.',
      },
      {
        id: 'l1-kim-q9',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Kimyasal Türler Arası Etkileşimler',
        questionNumber: 9,
        questionText:
          'Aşağıdaki bileşiklerden hangisi oda koşullarında iyonik kristal örgü yapısına sahiptir?',
        options: {
          A: 'H₂O (Su)',
          B: 'CO₂ (Karbondioksit)',
          C: 'NaCl (Yemek Tuzu)',
          D: 'CH₄ (Metan gazı)',
          E: 'NH₃ (Amonyak)',
        },
        correctAnswer: 'C',
        explanation:
          'Na bir metal (alkali metal), Cl ise bir ametaldir (halojen). Metal ve ametal arasında elektron alışverişiyle oluşan NaCl iyonik bağlı bir bileşiktir ve katı halde kristal örgü oluşturur.',
        hintForSocratic: 'İyonik bağın metal ile ametal atomları arasında gerçekleştiğini hatırla.',
      },
      {
        id: 'l1-kim-q10',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Laboratuvar Güvenlik Piktogramları',
        questionNumber: 10,
        questionText:
          'Bir kimyasal maddenin etiketinde "alev üzerinde bir O harfi" şeklinde simgelenen piktogram görülmektedir.\n\nBu güvenlik sembolü ne anlama gelir?',
        options: {
          A: 'Yanıcı Madde',
          B: 'Yakıcı (Oksitleyici) Madde',
          C: 'Aşındırıcı (Korozif) Madde',
          D: 'Radyoaktif Madde',
          E: 'Patlayıcı Madde',
        },
        correctAnswer: 'B',
        explanation:
          'Doğrudan alev sembolü "Yanıcı" anlamına gelirken, alevin ortasındaki Oksijenin O harfi "Yakıcı (Oksitleyici)" maddeyi ifade eder.',
        hintForSocratic: 'Ortadaki çember veya O harfi oksijen kaynağı yani yakıcı etkiyi temsil eder.',
      },
    ],
  },

  // 5. MEB 9. Sınıf Biyoloji 1. Dönem 1. Ortak Yazılı Sınavı Provası
  {
    id: 'exam-lise1-biyoloji-yazili-1',
    slug: 'meb-9-biyoloji-1-donem-1-yazili',
    title: 'MEB 9. Sınıf Biyoloji 1. Dönem 1. Ortak Yazılı Sınavı Provası',
    description: 'Canlıların ortak özellikleri, inorganik bileşikler (su, mineraller), organik bileşikler (karbonhidrat, lipit, protein ve enzimler) konularından 100 puanlık MEB ortak yazılı provası.',
    tier: 'lise1',
    type: 'yazili',
    courseKey: 'biyoloji',
    courseName: 'Biyoloji (9. Sınıf)',
    questionCount: 10,
    durationMinutes: 40,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'MEB ORTAK YAZILI',
    questions: [
      {
        id: 'l1-bio-q1',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Canlıların Ortak Özellikleri: Hücresel Yapı',
        questionNumber: 1,
        questionText:
          'Aşağıdakilerden hangisi tüm canlılar tarafından ortak olarak gerçekleştirilen bir metabolik olay değildir?',
        options: {
          A: 'Hücresel solunum ile ATP üretmek',
          B: 'Ribozom organelinde protein sentezlemek',
          C: 'İnorganik maddelerden organik madde (besin) sentezlemek (Ototrofluk)',
          D: 'Hücre zarından madde alışverişi yapmak',
          E: 'Genetik bilgiyi DNA ve RNA üzerinde taşımak',
        },
        correctAnswer: 'C',
        explanation:
          'İnorganik maddelerden organik besin üretmek sadece üretici (ototrof) canlılara özgüdür. Hayvanlar, mantarlar ve birçok bakteri hazır besin alarak heterotrof beslenir; dolayısıyla tüm canlılar için ortak değildir.',
        hintForSocratic: 'Besinini kendi üreten canlılar ile hazır beslenen canlılar arasındaki farkı düşün.',
      },
      {
        id: 'l1-bio-q2',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Canlıların Ortak Özellikleri: Homeostazi',
        questionNumber: 2,
        questionText:
          'Çevre koşulları değişse bile canlının vücut içi dengesini belirli sınırlar arasında sabit tutma çabasına ne ad verilir?',
        options: {
          A: 'Homeostazi (İç denge)',
          B: 'Adaptasyon',
          C: 'Modifikasyon',
          D: 'Anabolizma',
          E: 'Mutasyon',
        },
        correctAnswer: 'A',
        explanation:
          'Vücut sıcaklığının, kan pH\'sının ve su oranının sabit tutulması gibi kararlı iç ortam dengesine "homeostazi" denir.',
        hintForSocratic: 'Canlının iç ortam dengesini koruma yeteneğini anlatan terimdir.',
      },
      {
        id: 'l1-bio-q3',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'İnorganik Maddeler: Su ve Mineraller',
        questionNumber: 3,
        questionText:
          'İnsan vücudunda hemoglobin molekülünün yapısına katılarak oksijen ve karbondioksit taşınmasını sağlayan temel mineral hangisidir?',
        options: {
          A: 'Kalsiyum (Ca)',
          B: 'Demir (Fe)',
          C: 'Magnezyum (Mg)',
          D: 'İyot (I)',
          E: 'Fosfor (P)',
        },
        correctAnswer: 'B',
        explanation:
          'Demir (Fe) minerali kanda alyuvarlarda bulunan hemoglobin pigmentinin yapısına katılır. Eksikliğinde kansızlık (anemi) gelişir.',
        hintForSocratic: 'Kanda alyuvar yapısında yer alan ve eksikliğinde anemiye neden olan elementi hatırla.',
      },
      {
        id: 'l1-bio-q4',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Karbonhidratlar',
        questionNumber: 4,
        questionText:
          'Bitkilerde lökoplastlarda depolanan ve hayvanların sindirim sisteminde sindirilebilen polisakkarit aşağıdakilerden hangisidir?',
        options: {
          A: 'Selüloz',
          B: 'Nişasta',
          C: 'Glikojen',
          D: 'Kitin',
          E: 'Sükroz',
        },
        correctAnswer: 'B',
        explanation:
          'Bitkilerde fazla glikozun depo formu "nişasta"dır. Selüloz yapısal olup insanlar tarafından sindirilemez.',
        hintForSocratic: 'Bitkisel depo polisakkariti hangisidir?',
      },
      {
        id: 'l1-bio-q5',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Lipitler (Yağlar)',
        questionNumber: 5,
        questionText:
          'Hücre zarının temel iskeletini oluşturan, bir baş kısmı (hidrofilik) ve iki yağ asidi kuyruğundan (hidrofobik) meydana gelen lipit çeşidi hangisidir?',
        options: {
          A: 'Trigliserit (Nötral yağ)',
          B: 'Fosfolipit',
          C: 'Steroit',
          D: 'Kolesterol',
          E: 'Mumlar',
        },
        correctAnswer: 'B',
        explanation:
          'Fosfolipitler, hücre zarında çift katmanlı bir tabaka oluşturur. Fosfat içeren baş kısmı suyu sever (hidrofilik), yağ asidi kuyrukları ise sudan kaçar (hidrofobik).',
        hintForSocratic: 'Hücre zarının çift katmanlı lipit yapısını oluşturan moleküldür.',
      },
      {
        id: 'l1-bio-q6',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Proteinler',
        questionNumber: 6,
        questionText:
          'Proteinlerin yüksek sıcaklık, aşırı pH veya basınç etkisiyle üç boyutlu yapısının bozulup işlevini kaybetmesi olayına ne ad verilir?',
        options: {
          A: 'Denatürasyon',
          B: 'Renatürasyon',
          C: 'Dehidrasyon',
          D: 'Hidroliz',
          E: 'Polimerizasyon',
        },
        correctAnswer: 'A',
        explanation:
          'Proteinlerin yapısının bozulması işlemine "denatürasyon" denir. Yumurtanın pişmesi geri dönüşsüz bir denatürasyon örneğidir.',
        hintForSocratic: 'Doğal (naturel) yapının bozulması anlamına gelen terimi düşün.',
      },
      {
        id: 'l1-bio-q7',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Enzimler ve Çalışma Mekanizması',
        questionNumber: 7,
        questionText:
          'Enzimlerle ilgili aşağıdaki ifadelerden hangisi yanlıştır?',
        options: {
          A: 'Aktivasyon enerjisini düşürerek kimyasal tepkimeleri hızlandırırlar.',
          B: 'Tepkimelerden hiçbir değişikliğe uğramadan çıkarlar.',
          C: 'Genellikle çift yönlü (tersinir) çalışabilirler.',
          D: 'Her enzim sadece tek bir substrata özgüdür (anahtar-kilit uyumu).',
          E: 'Sıcaklık 0°C\'nin altına düştüğünde enzimin protein yapısı kalıcı olarak bozulur.',
        },
        correctAnswer: 'E',
        explanation:
          '0°C ve altındaki sıcaklıklarda enzimler inaktif duruma geçer ancak yapıları bozulmaz (denatüre olmaz); sıcaklık normale döndüğünde tekrar çalışırlar. Yapıyı bozan yüksek sıcaklıktır (genellikle 55°C üstü).',
        hintForSocratic: 'Dondurucudaki besinlerin bozulmamasının ancak çözülünce tekrar bozulabilmesinin nedenini hatırla.',
      },
      {
        id: 'l1-bio-q8',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Vitaminler',
        questionNumber: 8,
        questionText:
          'Aşağıda verilen vitaminlerden hangisi yağda çözünen ve fazlası karaciğerde depolandığı için eksikliği geç hissedilen vitaminlerdendir?',
        options: {
          A: 'B₁ Vitamini',
          B: 'B₁₂ Vitamini',
          C: 'C Vitamini',
          D: 'D Vitamini',
          E: 'Folik Asit',
        },
        correctAnswer: 'D',
        explanation:
          'Yağda çözünen vitaminler A, D, E ve K (ADEK) vitaminleridir. Karaciğerde depolanırlar. B grubu ve C vitaminleri ise suda çözünür ve fazlası idrarla atılır.',
        hintForSocratic: '"ADEK" vitaminleri yağda, B ve C vitaminleri suda erir.',
      },
      {
        id: 'l1-bio-q9',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Nükleik Asitler (DNA ve RNA)',
        questionNumber: 9,
        questionText:
          'DNA molekülünde 600 Guanin nükleotidi ve 400 Timin nükleotidi bulunmaktadır.\n\nBuna göre, bu DNA molekülündeki toplam hidrojen bağı sayısı kaçtır?',
        options: {
          A: '2000',
          B: '2400',
          C: '2600',
          D: '3000',
          E: '3200',
        },
        correctAnswer: 'C',
        explanation:
          '1. DNA çift zincirlidir: Guanin = Sitozin = 600, Timin = Adenin = 400.\n2. Adenin ile Timin arasında 2 hidrojen bağı bulunur: 400 × 2 = 800 bağ.\n3. Guanin ile Sitozin arasında 3 hidrojen bağı bulunur: 600 × 3 = 1800 bağ.\n4. Toplam hidrojen bağı sayısı: 800 + 1800 = 2600 bulunur.',
        hintForSocratic: 'A ile T arasında 2, G ile C arasında 3 hidrojen bağı olduğunu hatırla.',
      },
      {
        id: 'l1-bio-q10',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Hücre Teorisi ve Hücre Çeşitleri',
        questionNumber: 10,
        questionText:
          'Prokaryot hücreler ile ökaryot hücreler karşılaştırıldığında aşağıdakilerden hangisi yalnızca ökaryot hücrelerde bulunur?',
        options: {
          A: 'Hücre Zarı',
          B: 'Ribozom',
          C: 'Sitoplazma',
          D: 'Zarla çevrili organeller (Mitokondri, ER vb.) ve çekirdek',
          E: 'Genetik materyal (DNA ve RNA)',
        },
        correctAnswer: 'D',
        explanation:
          'Prokaryot hücrelerde (bakteriler ve arkeler) çekirdek ve zarlı organeller bulunmaz; DNA sitoplazmada dağınık hâldedir. Zarla çevrili organeller sadece ökaryot canlılara özgüdür.',
        hintForSocratic: 'Bakterilerde çekirdek zarı ve mitokondri var mıdır?',
      },
    ],
  },

  // 6. 9. Sınıf TYT Fen Bilimleri Temel Tarama Denemesi
  {
    id: 'exam-lise1-tyt-fen-1',
    slug: 'tyt-9-sinif-fen-tarama-denemesi',
    title: '9. Sınıf TYT Fen Bilimleri Temel Tarama Denemesi',
    description: 'YKS (TYT) Temel Seviye Fizik, Kimya ve Biyoloji 1. dönem kazanımlarını içeren 15 soruluk üniversiteye hazırlık tarama denemesi.',
    tier: 'lise1',
    type: 'tyt',
    questionCount: 15,
    durationMinutes: 30,
    difficulty: 'YKS (TYT) Düzeyi',
    isPro: false,
    badgeText: 'TYT TEMEL HAZIRLIK',
    questions: [
      {
        id: 'tyt-f-q1',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Fizik Bilimine Giriş',
        questionNumber: 1,
        questionText: 'Aşağıda verilen niceliklerden hangisi hem türetilmiş hem de vektörel bir büyüklüktür?',
        options: {
          A: 'Kütle',
          B: 'Zaman',
          C: 'Hız',
          D: 'Sürat',
          E: 'Işık Şiddeti',
        },
        correctAnswer: 'C',
        explanation: 'Hız, birim zamandaki yer değiştirmedir (v = Δx / Δt). Yönü vardır (vektörel) ve temel büyüklüklerden türetilmiştir.',
        hintForSocratic: 'Hız ve sürat arasındaki vektörellik farkını hatırla.',
      },
      {
        id: 'tyt-f-q2',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Madde ve Özkütle',
        questionNumber: 2,
        questionText: 'Sabit sıcaklık ve basınç altında saf bir katı maddenin kütlesi iki katına çıkarılırsa özkütlesi nasıl değişir?',
        options: {
          A: 'Yarıya iner',
          B: 'İki katına çıkar',
          C: 'Değişmez',
          D: 'Dört katına çıkar',
          E: 'Sıfır olur',
        },
        correctAnswer: 'C',
        explanation: 'Özkütle saf maddeler için ayırt edici bir özelliktir. Kütle iki katına çıktığında hacim de iki katına çıkar, oran (d = m / V) sabit kalır.',
        hintForSocratic: 'Özkütlenin ayırt edici özellik olduğunu ve madde miktarına bağlı olmadığını hatırla.',
      },
      {
        id: 'tyt-f-q3',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Dayanıklılık',
        questionNumber: 3,
        questionText: 'Karıncaların kendi ağırlıklarının onlarca katını taşıyabilmelerine rağmen fillerin kendi ağırlıklarını bile zorlukla taşımalarının fiziksel açıklaması hangi ilkeye dayanır?',
        options: {
          A: 'Pascal Prensibi',
          B: 'Galileo Küp-Kare Kanunu (Boyut-Dayanıklılık ilişkisi)',
          C: 'Bernoulli İlkesi',
          D: 'Arşimet Prensibi',
          E: 'Kepler Kanunu',
        },
        correctAnswer: 'B',
        explanation: 'Boyutlar büyüdükçe kesit alanı kareyle (r²), ağırlık ve hacim ise küple (r³) büyür. Dolayısıyla küçük canlıların dayanıklılığı çok daha fazladır.',
        hintForSocratic: 'Cisimlerin boyutları büyüdükçe ağırlığının kesit alanına göre daha hızlı arttığını hatırla.',
      },
      {
        id: 'tyt-f-q4',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Adezyon ve Kohezyon',
        questionNumber: 4,
        questionText: 'Bir cam kılcal boru cıva dolu kaba batırıldığında cıva seviyesinin kaptaki seviyeden daha aşağıda kalmasının nedeni nedir?',
        options: {
          A: 'Cıvanın kohezyon kuvvetinin cam ile cıva arasındaki adezyondan büyük olması',
          B: 'Cıvanın adezyonunun kohezyonundan büyük olması',
          C: 'Hava basıncının boruyu tıkaması',
          D: 'Cıvanın donma noktasının yüksek olması',
          E: 'Kılcal borunun çok geniş olması',
        },
        correctAnswer: 'A',
        explanation: 'Kohezyon kuvveti adezyondan büyük olan sıvılar (cıva gibi) yüzeyi ıslatmaz ve kılcal borularda dış seviyenin altına iner.',
        hintForSocratic: 'Islatmayan sıvılarda iç çekim kuvvetinin (kohezyon) dış çekimden (adezyon) büyük olduğunu düşün.',
      },
      {
        id: 'tyt-f-q5',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: 'Hareket',
        questionNumber: 5,
        questionText: 'Yarıçapı 10 metre olan çembersel bir pistin A noktasından harekete başlayan bir sporcu yarım tur atarak tam karşısındaki B noktasına varıyor. Sporcunun aldığı yol ve yer değiştirmesi (m) sırasıyla nedir? (π = 3 alınız)',
        options: {
          A: '30 m — 20 m',
          B: '60 m — 10 m',
          C: '30 m — 0 m',
          D: '20 m — 30 m',
          E: '60 m — 20 m',
        },
        correctAnswer: 'A',
        explanation: '1. Çevre = 2πr = 2 × 3 × 10 = 60 m. Yarım tur yolu = 60 / 2 = 30 m.\n2. Yer değiştirme ilk nokta ile son nokta arasındaki en kısa kuş uçuşu mesafedir, yani çaptır: 2r = 20 m.',
        hintForSocratic: 'Alınan yol yörünge uzunluğudur, yer değiştirme ise başlangıçtan bitişe çizilen doğru parçasıdır.',
      },
      {
        id: 'tyt-k-q6',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Kimya Bilimi',
        questionNumber: 6,
        questionText: 'Aşağıdakilerden hangisi kimyayı simyadan ayıran en kesin ölçüttür?',
        options: {
          A: 'Ateşin kullanılması',
          B: 'Deneylerde hassas terazi ve nicel ölçüm yapılması',
          C: 'Bitkilerden ilaç elde edilmesi',
          D: 'Madenlerin eritilmesi',
          E: 'Cam kapların kullanılması',
        },
        correctAnswer: 'B',
        explanation: 'Lavoisier\'in Kütlenin Korunumu Kanunu\'nu hassas terazi kullanarak ispatlaması modern kimyanın başlangıcı kabul edilir.',
        hintForSocratic: 'Ölçmeye ve kütle dengesine dayalı bilimsel yaklaşımı hatırla.',
      },
      {
        id: 'tyt-k-q7',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Bileşikler',
        questionNumber: 7,
        questionText: 'Aşağıda formülü verilen bileşiklerden hangisinin yapısında azot (N) atomu bulunmaz?',
        options: {
          A: 'Kezzap (HNO₃)',
          B: 'Amonyak (NH₃)',
          C: 'Güherçile (KNO₃)',
          D: 'Zaç Yağı (H₂SO₄)',
          E: 'Sud-kostik ile nötrleşen HNO₃ tuzu (NaNO₃)',
        },
        correctAnswer: 'D',
        explanation: 'Zaç yağı sülfürik asittir (H₂SO₄). Yapısında hidrojen, kükürt ve oksijen bulunur; azot yoktur.',
        hintForSocratic: 'Zaç yağının kükürt içerdiğini hatırla.',
      },
      {
        id: 'tyt-k-q8',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Periyodik Tablo',
        questionNumber: 8,
        questionText: 'Periyodik tablonun 2. periyot 8A grubunda yer alan soygaz hangisidir?',
        options: {
          A: 'Helyum (He)',
          B: 'Neon (Ne)',
          C: 'Argon (Ar)',
          D: 'Kripton (Kr)',
          E: 'Ksenon (Xe)',
        },
        correctAnswer: 'B',
        explanation: 'Helyum 1. periyot soygazıdır (atom no 2). 2. periyot soygazı Neon (Ne, atom no 10: 2) 8))\'dur.',
        hintForSocratic: 'Helyumun 1. periyotta olduğunu unutma.',
      },
      {
        id: 'tyt-k-q9',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Kimyasal Bağlar',
        questionNumber: 9,
        questionText: 'Aynı ametal atomları arasında elektronların ortaklaşa kullanılmasıyla oluşan bağ türüne ne ad verilir?',
        options: {
          A: 'Polar kovalent bağ',
          B: 'Apolar kovalent bağ',
          C: 'İyonik bağ',
          D: 'Hidrojen bağı',
          E: 'Metalik bağ',
        },
        correctAnswer: 'B',
        explanation: 'Örneğin O₂, N₂, H₂, Cl₂ gibi aynı iki ametal atomu arasındaki bağ "apolar (kutupsuz) kovalent" bağdır.',
        hintForSocratic: '"Apolar" kelimesinin kutupsuz, aynı atomlar arası anlamına geldiğini hatırla.',
      },
      {
        id: 'tyt-k-q10',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: 'Maddenin Halleri',
        questionNumber: 10,
        questionText: 'Sıvıların akmaya karşı gösterdiği iç dirence ne ad verilir?',
        options: {
          A: 'Yüzey gerilimi',
          B: 'Kılcallık',
          C: 'Viskozite',
          D: 'Buharlaşma ısısı',
          E: 'Yoğunluk',
        },
        correctAnswer: 'C',
        explanation: 'Sıvıların akmaya karşı gösterdiği dirence viskozite denir. Örneğin balın viskozitesi suyunkinden çok daha yüksektir.',
        hintForSocratic: 'Bal veya pekmez gibi akışkanlığı yavaş olan sıvıların yüksek olan özelliğini düşün.',
      },
      {
        id: 'tyt-b-q11',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Canlıların Ortak Özellikleri',
        questionNumber: 11,
        questionText: 'Canlılarda küçük moleküllerden büyük moleküllerin sentezlendiği yapım tepkimelerine (özümleme) ne ad verilir?',
        options: {
          A: 'Katabolizma',
          B: 'Anabolizma',
          C: 'Hidroliz',
          D: 'Sindirim',
          E: 'Fermantasyon',
        },
        correctAnswer: 'B',
        explanation: 'Yapım tepkimelerine "anabolizma" (özümleme), yıkım tepkimelerine ise "katabolizma" (yadımlama) denir.',
        hintForSocratic: 'Protein veya fotosentez gibi yapım tepkimelerine verilen adı hatırla.',
      },
      {
        id: 'tyt-b-q12',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Karbonhidratlar',
        questionNumber: 12,
        questionText: 'Böceklerin dış iskeletinde ve mantarların hücre çeperinde bulunan azotlu polisakkarit hangisidir?',
        options: {
          A: 'Nişasta',
          B: 'Selüloz',
          C: 'Glikojen',
          D: 'Kitin',
          E: 'Keratin',
        },
        correctAnswer: 'D',
        explanation: 'Kitin, yapısında azot atomu bulunan tek yapısal polisakkarittir.',
        hintForSocratic: 'Böcek kabuğunun ve mantar duvarının yapısındaki azotlu karbonhidrattır.',
      },
      {
        id: 'tyt-b-q13',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Hücre',
        questionNumber: 13,
        questionText: 'Hücre içerisinde madde iletiminden sorumlu olan, çekirdek zarı ile hücre zarı arasında uzanan kanalcıklar sistemine ne ad verilir?',
        options: {
          A: 'Golgi aygıtı',
          B: 'Endoplazmik Retikulum (ER)',
          C: 'Lizozom',
          D: 'Mitokondri',
          E: 'Ribozom',
        },
        correctAnswer: 'B',
        explanation: 'Endoplazmik retikulum, hücre içi madde iletimi ve protein/lipit sentezinde görev alan kanalcık sistemidir.',
        hintForSocratic: 'Hücre içi otoyol veya boru hattı olarak nitelenen organeldir.',
      },
      {
        id: 'tyt-b-q14',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Hücre Organelleri',
        questionNumber: 14,
        questionText: 'İçerisinde sindirim enzimleri bulunduran ve hücre içi sindirimi gerçekleştiren organel aşağıdakilerden hangisidir?',
        options: {
          A: 'Lizozom',
          B: 'Koful',
          C: 'Sentrozom',
          D: 'Ribozom',
          E: 'Plastit',
        },
        correctAnswer: 'A',
        explanation: 'Lizozom organeli hidrolitik (sindirim) enzimleri taşır ve hücre içi sindirimden sorumludur.',
        hintForSocratic: 'İntihar kesesi de denilen sindirim organelini düşün.',
      },
      {
        id: 'tyt-b-q15',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: 'Enzimler',
        questionNumber: 15,
        questionText: 'Enzimlerin etki ettiği maddeye ne ad verilir?',
        options: {
          A: 'Apoenzim',
          B: 'Substrat',
          C: 'Koenzim',
          D: 'Kofaktör',
          E: 'Aktivatör',
        },
        correctAnswer: 'B',
        explanation: 'Enzimlerin bağlandığı ve ürüne dönüştürdüğü başlangıç maddesine "substrat" denir.',
        hintForSocratic: 'Anahtar-kilit modelinde enzimin bağlandığı anahtar yuvasını oluşturan maddeyi düşün.',
      },
    ],
  },
];
