import type { OnlineExam } from '@/types/online-exam';

// MEB Türkiye Yüzyılı Maarif Modeli (9. Sınıf) Konu & Ünite Pekiştirme Testleri
// Tüm sorular MEB TTKB resmi kazanımlarına ve ortak yazılı soru kalıplarına tam uyumludur.

export const LISE1_UNIT_TESTS: OnlineExam[] = [
  // 1. MATEMATİK (1. Tema: Sayılar)
  {
    id: 'exam-lise1-unit-mat-1',
    slug: 'meb-9-matematik-tema-1-sayilar-testi',
    title: '9. Sınıf Matematik 1. Tema: Sayılar Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Gerçek sayıların üslü/köklü gösterimleri, sayı aralıkları ve özdeşlikler pekiştirme sınavı.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'matematik',
    courseName: 'Matematik (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 20,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Tema: Sayılar',
    questions: [
      {
        id: 'l1-u-mat-q1',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - Gerçek Sayıların Üslü ve Köklü Gösterimleri',
        questionNumber: 1,
        questionText: '2^(x + 1) = 32 olduğuna göre, 3^(x - 1) ifadesinin değeri kaçtır?',
        options: {
          A: '3',
          B: '9',
          C: '27',
          D: '81',
          E: '243',
        },
        correctAnswer: 'C',
        explanation: '1. Adım: 32 sayısını 2\'nin kuvveti olarak yazalım: 32 = 2⁵.\n2^(x + 1) = 2⁵ ⇒ x + 1 = 5 ⇒ x = 4 bulunur.\n\n2. Adım: x = 4 değerini istenen ifadede yerine koyalım:\n3^(x - 1) = 3^(4 - 1) = 3³ = 27 bulunur.\nDoğru seçenek C\'dir.',
        hintForSocratic: '32 sayısını 2\'nin kaçıncı kuvveti olarak yazabilirsin? Tabanlar eşitse üsler de birbirine eşit olmalıdır.',
      },
      {
        id: 'l1-u-mat-q2',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - Köklü İfadelerde Dört İşlem',
        questionNumber: 2,
        questionText: '√108 - √48 + √27 işleminin sonucu aşağıdakilerden hangisidir?',
        options: {
          A: '3√3',
          B: '4√3',
          C: '5√3',
          D: '6√3',
          E: '7√3',
        },
        correctAnswer: 'C',
        explanation: '1. Adım: Kök içindeki sayıları a√b biçiminde yazalım:\n√108 = √(36 · 3) = 6√3\n√48 = √(16 · 3) = 4√3\n√27 = √(9 · 3) = 3√3\n\n2. Adım: Katsayıları toplayıp çıkaralım:\n(6 - 4 + 3)√3 = 5√3 bulunur.\nDoğru seçenek C\'dir.',
        hintForSocratic: '108, 48 ve 27 sayılarını içinde tam kare olan çarpanlarına (36, 16, 9) ayırarak kök dışına çıkarmayı dene.',
      },
      {
        id: 'l1-u-mat-q3',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - Tam Kare ve Mutlak Değer Bağıntısı',
        questionNumber: 3,
        questionText: 'x ve y birer tam sayı olmak üzere,\n(x - 3)² + |y + 5| = 0\n\neşitliği verildiğine göre, x · y çarpımı kaçtır?',
        options: {
          A: '-15',
          B: '-8',
          C: '0',
          D: '8',
          E: '15',
        },
        correctAnswer: 'A',
        explanation: 'Gerçek sayılarda bir sayının karesi ve mutlak değeri hiçbir zaman negatif olamaz (≥ 0).\nİki negatif olmayan sayının toplamının sıfır olması ancak her ikisinin de sıfır olmasıyla mümkündür:\n(x - 3)² = 0 ⇒ x - 3 = 0 ⇒ x = 3\n|y + 5| = 0 ⇒ y + 5 = 0 ⇒ y = -5\n\nx · y = 3 · (-5) = -15 bulunur. Doğru seçenek A\'dır.',
        hintForSocratic: 'Bir tam kare ifade ve bir mutlak değer en az kaç olabilir? Toplamın 0 çıkması için ikisinin de kaç olması gerekir?',
      },
      {
        id: 'l1-u-mat-q4',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - Gerçek Sayı Aralıkları ve Kesişim',
        questionNumber: 4,
        questionText: 'A = [-4, 6) ve B = (-1, 9] aralıkları tanımlanıyor.\n\nBuna göre, (A ∩ B) aralığında yer alan tam sayıların toplamı kaçtır?',
        options: {
          A: '10',
          B: '12',
          C: '14',
          D: '15',
          E: '18',
        },
        correctAnswer: 'D',
        explanation: '1. Adım: A ∩ B kesişim kümesini bulalım. Sol sınırların büyüğü: max(-4, -1) = -1 (açık), sağ sınırların küçüğü: min(6, 9) = 6 (açık).\nA ∩ B = (-1, 6) açık aralığıdır.\n\n2. Adım: Bu aralıktaki tam sayılar: {0, 1, 2, 3, 4, 5}.\nToplam = 0 + 1 + 2 + 3 + 4 + 5 = 15 bulunur.\nDoğru seçenek D\'dir.',
        hintForSocratic: 'İki aralığın kesişiminde sınır noktalarına dikkat et: -1 ve 6 noktaları dahil midir, aradaki tam sayılar nelerdir?',
      },
      {
        id: 'l1-u-mat-q5',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - İki Kare Farkı ve Tam Kare Özdeşlikleri',
        questionNumber: 5,
        questionText: 'a ve b pozitif gerçek sayılar olmak üzere,\na + b = 7 ve a · b = 10\n\nolduğuna göre, a² + b² ifadesinin değeri kaçtır?',
        options: {
          A: '25',
          B: '29',
          C: '39',
          D: '49',
          E: '59',
        },
        correctAnswer: 'B',
        explanation: 'Tam kare açılımı kuralına göre:\n(a + b)² = a² + 2ab + b²\nBuradan a² + b² = (a + b)² - 2ab yazılır.\n\nVerilen değerleri yerine koyalım:\na² + b² = 7² - 2 · 10 = 49 - 20 = 29 bulunur.\nDoğru seçenek B\'dir.',
        hintForSocratic: '(a + b)² açılımını yaz. İçindeki a · b ve a² + b² terimlerini nasıl gruplayabilirsin?',
      },
    ],
  },

  // 2. FİZİK (1. ve 2. Ünite: Fizik Bilimi, Büyüklükler ve Hareket)
  {
    id: 'exam-lise1-unit-fiz-1',
    slug: 'meb-9-fizik-unite-1-ve-2-testi',
    title: '9. Sınıf Fizik 1. ve 2. Ünite: Fizik Bilimi & Hareket Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Fiziğin doğası, temel/türetilmiş büyüklükler, vektörler ve bir boyutta doğrusal hareket soruları.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'fizik',
    courseName: 'Fizik (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. ve 2. Ünite: Fizik Bilimi & Hareket',
    questions: [
      {
        id: 'l1-u-fiz-q1',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '2. Ünite: Kuvvet ve Hareket - Temel ve Türetilmiş Büyüklükler',
        questionNumber: 1,
        questionText: 'Aşağıda verilen fiziksel büyüklüklerden hangisi SI birim sisteminde TEMEL bir büyüklüktür?',
        options: {
          A: 'Kuvvet (Newton)',
          B: 'Hız (m/s)',
          C: 'Termodinamik Sıcaklık (Kelvin)',
          D: 'İvme (m/s²)',
          E: 'İş ve Enerji (Joule)',
        },
        correctAnswer: 'C',
        explanation: 'Fizikte 7 temel büyüklük "KISA MUZ" kodlamasıyla hatırlanır: Kütle, Işık şiddeti, Sıcaklık (Kelvin), Akım şiddeti, Madde miktarı, Uzunluk, Zaman. Kuvvet, hız, ivme ve enerji ise diğer büyüklüklerden türetilmiştir. Doğru seçenek C\'dir.',
        hintForSocratic: 'KISA MUZ kısaltmasını hatırla. Sıcaklık tek başına doğrudan mı ölçülür yoksa başka formüllerle mi türetilir?',
      },
      {
        id: 'l1-u-fiz-q2',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '2. Ünite: Kuvvet ve Hareket - Doğrusal Hareket ve Yer Değiştirme',
        questionNumber: 2,
        questionText: 'Doğrusal bir yolda sabit 20 m/s hızla ilerleyen bir otomobil, 15 saniye boyunca bu hareketini sürdürmektedir.\n\nBuna göre otomobilin bu süre zarfındaki yer değiştirmesi kaç metredir?',
        options: {
          A: '150',
          B: '200',
          C: '250',
          D: '300',
          E: '350',
        },
        correctAnswer: 'D',
        explanation: 'Sabit hızlı doğrusal harekette yer değiştirme bağıntısı:\nΔx = v · t\nΔx = 20 m/s · 15 s = 300 metre bulunur.\nDoğru seçenek D\'dir.',
        hintForSocratic: 'Sabit hızda yer değiştirme = Hız × Zaman formülünü uygula.',
      },
      {
        id: 'l1-u-fiz-q3',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '1. Ünite: Fizik Bilimi ve Kariyer Keşfi - Fiziğin Alt Dalları',
        questionNumber: 3,
        questionText: 'Fiber optik kablolarla ışığın tam yansıması prensibine dayalı yüksek hızlı internet iletişimi ve göz kusurlarını düzelten lazer ameliyatları, fiziğin hangi alt dalının inceleme alanına girer?',
        options: {
          A: 'Mekanik',
          B: 'Termodinamik',
          C: 'Optik',
          D: 'Manyetizma',
          E: 'Nükleer Fizik',
        },
        correctAnswer: 'C',
        explanation: 'Işığın yapısını, yayılmasını, yansıma ve kırılma gibi olaylarını inceleyen fizik alt dalı Optik\'tir. Fiber optik ve lazer teknolojisi doğrudan optiğin konusudur. Doğru seçenek C\'dir.',
        hintForSocratic: 'Işık, mercekler, yansıma ve kırılma ile ilgilenen fizik alt dalı hangisidir?',
      },
      {
        id: 'l1-u-fiz-q4',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '2. Ünite: Kuvvet ve Hareket - Kartezyen Koordinatlarda Vektörler',
        questionNumber: 4,
        questionText: 'Aynı noktaya etki eden iki kuvvetten F1 doğu yönünde 6 N, F2 ise kuzey yönünde 8 N büyüklüğündedir.\n\nBuna göre bu iki kuvvetin bileşkesinin (R) büyüklüğü kaç Newton\'dur?',
        options: {
          A: '10',
          B: '12',
          C: '14',
          D: '48',
          E: '100',
        },
        correctAnswer: 'A',
        explanation: 'Doğu ve kuzey yönleri birbirine diktir (aralarındaki açı 90°\'dir).\nPisagor bağıntısından bileşke:\nR = √(F1² + F2²) = √(6² + 8²) = √(36 + 64) = √100 = 10 N bulunur.\nDoğru seçenek A\'dır.',
        hintForSocratic: 'Aralarında 90 derece açı bulunan dik iki vektörün bileşkesini bulmak için Pisagor bağıntısını (3-4-5 üçgeninin katları) hatırla.',
      },
      {
        id: 'l1-u-fiz-q5',
        courseKey: 'fizik',
        courseName: 'Fizik',
        topicName: '2. Ünite: Kuvvet ve Hareket - Doğadaki Temel Kuvvetler',
        questionNumber: 5,
        questionText: 'Doğadaki dört temel kuvvetten biri olan, etki menzili sonsuz kabul edilen ve gezegenlerin Güneş etrafında belirli bir yörüngede kalmasını sağlayan kuvvet aşağıdakilerden hangisidir?',
        options: {
          A: 'Güçlü Nükleer Kuvvet',
          B: 'Zayıf Nükleer Kuvvet',
          C: 'Kütle Çekim Kuvveti',
          D: 'Elektromanyetik Kuvvet',
          E: 'Sürtünme Kuvveti',
        },
        correctAnswer: 'C',
        explanation: 'Kütlesi olan tüm cisimlerin birbirine uyguladığı çekim kuvveti Kütle Çekim Kuvveti\'dir. Menzili sonsuzdur ve gezegenlerin, uyduların yörüngede kalmasını sağlar. Doğru seçenek C\'dir.',
        hintForSocratic: 'Gök cisimlerinin kütleleri nedeniyle birbirini çekmesini sağlayan temel doğa kuvveti hangisidir?',
      },
    ],
  },

  // 3. KİMYA (1. Tema: Etkileşim - Kimya Bilimi, Atom Modelleri ve Periyodik Tablo)
  {
    id: 'exam-lise1-unit-kim-1',
    slug: 'meb-9-kimya-tema-1-etkilesim-testi',
    title: '9. Sınıf Kimya 1. Tema: Etkileşim & Atomun Yapısı Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Laboratuvar güvenliği, atom teorileri, elektron dağılımı ve periyodik sistem özellikleri testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'kimya',
    courseName: 'Kimya (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Tema: Etkileşim',
    questions: [
      {
        id: 'l1-u-kim-q1',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Laboratuvar Güvenlik Kuralları ve Piktogramlar',
        questionNumber: 1,
        questionText: 'Bir kimyasal madde şişesi üzerinde "alev simgesi" (üzerinde alev deseni bulunan tehlike piktogramı) bulunmaktadır.\n\nBu uyarı işareti kimyasal maddenin hangi özelliğe sahip olduğunu belirtir?',
        options: {
          A: 'Aşındırıcı (Korozif) Madde',
          B: 'Yanıcı Madde',
          C: 'Radyoaktif Madde',
          D: 'Patlayıcı Madde',
          E: 'Çevreye Zararlı Madde',
        },
        correctAnswer: 'B',
        explanation: 'Doğrudan alev deseni içeren piktogram maddenin "Yanıcı" (flammable) olduğunu, kolay tutuşabileceğini ve ateş kaynaklarından uzak tutulması gerektiğini gösterir. Doğru seçenek B\'dir.',
        hintForSocratic: 'Alev şekli yangın ve kolay tutuşma ile ilgilidir. Bu piktogram hangi özelliği simgeler?',
      },
      {
        id: 'l1-u-kim-q2',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Elektron Dizilimi ve Periyodik Tablo',
        questionNumber: 2,
        questionText: 'Nötr bir X atomunun katman elektron dizilimi 2 - 8 - 7 şeklindedir.\n\nBuna göre X elementi periyodik sistemde hangi periyot ve grupta yer alır?',
        options: {
          A: '2. Periyot 7A Grubu',
          B: '3. Periyot 7A Grubu',
          C: '3. Periyot 8A Grubu',
          D: '7. Periyot 3A Grubu',
          E: '2. Periyot 8A Grubu',
        },
        correctAnswer: 'B',
        explanation: 'Katman sayısı periyot numarasını, son katmandaki değerlik elektron sayısı ise A grubunu verir.\n3 katman vardır ⇒ 3. Periyot.\nSon katmanda 7 elektron vardır ⇒ 7A Grubu (Halojen).\nDoğru seçenek B\'dir.',
        hintForSocratic: 'Katman sayısı periyodu, son katmandaki elektron sayısı grubu verir. Kaç katman ve son katmanda kaç elektron var?',
      },
      {
        id: 'l1-u-kim-q3',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Periyodik Özelliklerin Değişimi',
        questionNumber: 3,
        questionText: 'Periyodik tabloda aynı periyotta soldan sağa doğru gidildikçe genel olarak aşağıdakilerden hangisi gerçekleşir?',
        options: {
          A: 'Atom yarıçapı artar.',
          B: 'Katman sayısı artar.',
          C: 'Metalik aktiflik artar.',
          D: 'Elektronegatiflik ve ametalik özellik artar.',
          E: 'Çekirdeğin proton sayısı azalır.',
        },
        correctAnswer: 'D',
        explanation: 'Aynı periyotta soldan sağa gidildikçe çekirdek yükü (proton sayısı) artar, katman sayısı değişmez. Çekim gücü arttığından atom yarıçapı küçülür, elektron ilgisi, iyonlaşma enerjisi, elektronegatiflik ve ametalik özellik artar. Doğru seçenek D\'dir.',
        hintForSocratic: 'Sağ tarafta ametaller ve halojenler yer alır. Soldan sağa giderken ametallere mi metallere mi yaklaşırız?',
      },
      {
        id: 'l1-u-kim-q4',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Atom Modelleri ve Tarihsel Gelişim',
        questionNumber: 4,
        questionText: 'Dalton atom modelinde yer alan;\nI. Atomlar bölünemez, parçalanamaz en küçük yapı taşlarıdır.\nII. Bir elementin bütün atomları kütlece birbirinin tıpatıp aynısıdır.\nIII. Farklı element atomları birbirinden farklıdır.\n\nyargılarından hangileri günümüz modern atom teorisine göre GEÇERLİLİĞİNİ YİTİRMİŞTİR?',
        options: {
          A: 'Yalnız I',
          B: 'Yalnız II',
          C: 'I ve II',
          D: 'II ve III',
          E: 'I, II ve III',
        },
        correctAnswer: 'C',
        explanation: 'Günümüzde atomlar nükleer reaksiyonlarla bölünebilir (I yanlış). İzotop atomların keşfiyle aynı elementin farklı nötron sayılı/kütleli atomları olduğu kanıtlanmıştır (II yanlış). Farklı elementlerin atomları ise birbirinden farklıdır (III hâlâ geçerlidir). Dolayısıyla I ve II geçerliliğini yitirmiştir. Doğru seçenek C\'dir.',
        hintForSocratic: 'Nükleer fisyon atomun bölünebildiğini, izotop kavramı ise aynı elementin farklı kütleli atomları olduğunu gösterir.',
      },
      {
        id: 'l1-u-kim-q5',
        courseKey: 'kimya',
        courseName: 'Kimya',
        topicName: '1. Tema: Etkileşim - Kimya Disiplinleri ve Çalışma Alanları',
        questionNumber: 5,
        questionText: 'Bir su arıtma tesisinde suyun içindeki ağır metallerin (kurşun, cıva vb.) türünü ve miktarını hassas cihazlarla analiz eden kimya alt disiplini aşağıdakilerden hangisidir?',
        options: {
          A: 'Organik Kimya',
          B: 'Analitik Kimya',
          C: 'Biyokimya',
          D: 'Fizikokimya',
          E: 'Polimer Kimyası',
        },
        correctAnswer: 'B',
        explanation: 'Maddelerin bileşenlerini, ne olduklarını (nitel) ve ne kadar olduklarını (nicel) analiz eden temel kimya disiplini Analitik Kimya\'dır. Doğru seçenek B\'dir.',
        hintForSocratic: 'Tür (nitel) ve miktar (nicel) analizi yapan kimya disiplininin adı nedir?',
      },
    ],
  },

  // 4. BİYOLOJİ (1. Tema: Yaşam - Biyomoleküller ve Enzimler)
  {
    id: 'exam-lise1-unit-biyo-1',
    slug: 'meb-9-biyoloji-tema-1-yasam-testi',
    title: '9. Sınıf Biyoloji 1. Tema: Yaşam & Canlıların Bileşenleri Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Canlıların ortak özellikleri, inorganik/organik bileşikler ve enzimler konu pekiştirme testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'biyoloji',
    courseName: 'Biyoloji (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'MEB Yazılı Düzeyi',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Tema: Yaşam',
    questions: [
      {
        id: 'l1-u-biy-q1',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - Canlıların Ortak Özellikleri',
        questionNumber: 1,
        questionText: 'Aşağıda verilen hücresel özelliklerden hangisi dünyadaki TÜM canlılarda ortak olarak gerçekleşir?',
        options: {
          A: 'Fotosentez yaparak kendi besinini üretme',
          B: 'Oksijenli solunum ile ATP üretme',
          C: 'Ribozom organelinde protein sentezleme',
          D: 'Mitoz bölünme ile çoğalma',
          E: 'Çekirdek zarı içerisinde DNA taşıma',
        },
        correctAnswer: 'C',
        explanation: 'Ribozom organeli prokaryot ve ökaryot tüm hücresel canlılarda bulunan tek zarsız organeldir ve tüm canlılar kendi proteinlerini ribozomda sentezler. Fotosentez, oksijenli solunum veya çekirdek zarı ise sadece belirli canlı gruplarında bulunur. Doğru seçenek C\'dir.',
        hintForSocratic: 'Zarsız olan ve hem bakteride hem insanda bulunan evrensel protein üretim merkezi hangi organeldir?',
      },
      {
        id: 'l1-u-biy-q2',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - Organik Bileşikler: Proteinler ve Dehidrasyon',
        questionNumber: 2,
        questionText: '100 adet amino asidin dehidrasyon senteziyle birbirine bağlanması sonucu doğrusal bir polipeptit zinciri oluşmaktadır.\n\nBu tepkime sürecinde kurulan peptit bağı sayısı ve açığa çıkan su (H2O) molekülü sayısı aşağıdakilerden hangisinde doğru verilmiştir?',
        options: {
          A: '100 bağ / 100 su',
          B: '99 bağ / 99 su',
          C: '100 bağ / 99 su',
          D: '99 bağ / 100 su',
          E: '50 bağ / 50 su',
        },
        correctAnswer: 'B',
        explanation: 'n sayıda monomerin birleştiği doğrusal polimerizasyonda:\nBağ sayısı = n - 1 = 100 - 1 = 99\nAçığa çıkan su sayısı = Kurulan bağ sayısı = 99 moleküldür.\nDoğru seçenek B\'dir.',
        hintForSocratic: 'n sayıda amino asitten oluşan doğrusal bir zincirde bağ sayısı ve açığa çıkan su sayısı n - 1 kuralına eşittir.',
      },
      {
        id: 'l1-u-biy-q3',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - Biyolojik Katalizörler: Enzimler',
        questionNumber: 3,
        questionText: 'Bir enzimatik reaksiyonun gerçekleştiği ortamın sıcaklığı 37°C\'den 65°C\'ye çıkarılmış ve ardından tekrar 37°C\'ye düşürülmüştür.\n\nSıcaklık 37°C\'ye geri düşürüldüğünde tepkimenin yeniden başlamamasının temel nedeni aşağıdakilerden hangisidir?',
        options: {
          A: 'Substratın ortamdan tamamen tükenmesi',
          B: 'Yüksek sıcaklıkta enzimin üç boyutlu protein yapısının geri dönüşümsüz bozulması (denatürasyon)',
          C: 'Enzimin aktivasyon enerjisini aşırı artırması',
          D: 'Ortamdaki su oranının sıfıra inmesi',
          E: 'Enzimin koenzim kısmının substratla yarışması',
        },
        correctAnswer: 'B',
        explanation: 'Enzimler protein yapılıdır. 55-60°C üzerindeki sıcaklıklarda proteinlerin tersiyer/üç boyutlu yapısı bozulur (denatürasyon). Bu bozulma geri dönüşümsüz olduğu için sıcaklık normale dönse bile enzim işlevini kaybeder. Doğru seçenek B\'dir.',
        hintForSocratic: 'Yumurtayı haşladıktan sonra soğutsan bile eski çiğ haline dönebilir mi? Proteinlerin yüksek sıcaklıkta yapısının bozulmasına ne denir?',
      },
      {
        id: 'l1-u-biy-q4',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - İnorganik Bileşikler',
        questionNumber: 4,
        questionText: 'Canlıların yapısında bulunan inorganik bileşikler (su, mineraller, asitler, bazlar) ile ilgili aşağıdakilerden hangisi YANLIŞTIR?',
        options: {
          A: 'Canlılar tarafından sentezlenemez, dışarıdan hazır alınırlar.',
          B: 'Hücre zarından sindirilmeden doğrudan geçebilirler.',
          C: 'Hücresel solunumda enerji verici (ATP üretimi için) birinci derece yakıt olarak kullanılırlar.',
          D: 'Enzimlerin yapısına kofaktör olarak katılarak düzenleyici rol oynarlar.',
          E: 'Vücudun asit-baz dengesini ve ozmotik basıncını ayarlarlar.',
        },
        correctAnswer: 'C',
        explanation: 'İnorganik bileşikler (su, mineraller vb.) hiçbir canlı tarafından hücresel solunumda PARÇALANARAK ENERJİ (ATP) ÜRETMEK AMACIYLA KULLANILMAZ. Enerji verici moleküller sadece organik moleküllerdir (karbonhidrat, yağ, protein). Doğru seçenek C\'dir.',
        hintForSocratic: 'Su veya tuz içtiğimizde kalori/enerji alır mıyız? İnorganik maddeler enerji verir mi?',
      },
      {
        id: 'l1-u-biy-q5',
        courseKey: 'biyoloji',
        courseName: 'Biyoloji',
        topicName: '1. Tema: Yaşam - Nükleik Asitler (DNA ve RNA)',
        questionNumber: 5,
        questionText: 'DNA ve RNA molekülleri karşılaştırıldığında;\nI. Adenin, Guanin ve Sitozin bazlarını taşıma\nII. Deoksiriboz beş karbonlu şekerine sahip olma\nIII. Çift sarmallı heliks yapı gösterme\n\nözelliklerinden hangileri HER İKİ nükleik asit için de ORTAKTIR?',
        options: {
          A: 'Yalnız I',
          B: 'Yalnız II',
          C: 'I ve II',
          D: 'I ve III',
          E: 'I, II ve III',
        },
        correctAnswer: 'A',
        explanation: 'Adenin, Guanin ve Sitozin bazları hem DNA hem RNA\'da ortaktır (I doğru). Deoksiriboz şekeri ve çift zincirli sarmal yapı sadece DNA\'ya aittir; RNA riboz şekeri taşır ve tek zincirlidir. Yalnız I ortaktır. Doğru seçenek A\'dır.',
        hintForSocratic: 'DNA ve RNA\'nın şekerleri aynı mıdır (Deoksiriboz vs Riboz)? Hangi organik bazlar her ikisinde de bulunur?',
      },
    ],
  },

  // 5. İNGİLİZCE (Theme 1: School Life)
  {
    id: 'exam-lise1-unit-ing-1',
    slug: 'meb-9-ingilizce-theme-1-school-life-testi',
    title: '9. Sınıf İngilizce Theme 1: School Life Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli İngilizce Theme 1: School Life ünitesi için özel hazırlanmış 5 soruluk hızlı pekiştirme testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'ingilizce',
    courseName: 'İngilizce (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'Orta',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: 'Theme 1: School Life',
    questions: [
      {
        id: 'l1-u-ing-q1',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 1: School Life - Countries, Nationalities & Capitals',
        questionNumber: 1,
        questionText:
          'Match the student with their country and language:\n\n"Pierre is from France. His native language is ------, and the capital of his country is ------."\n\nWhich pair completes the sentence?',
        options: {
          A: 'French / Paris',
          B: 'France / Lyon',
          C: 'German / Berlin',
          D: 'Spanish / Madrid',
          E: 'Italian / Rome',
        },
        correctAnswer: 'A',
        explanation: 'Fransa\'dan (France) olan birinin ana dili Fransızca (French), başkenti ise Paris\'tir. Doğru seçenek A\'dır.',
        hintForSocratic: 'Fransa\'nın ana dili ve başkenti hangisidir?',
      },
      {
        id: 'l1-u-ing-q2',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 1: School Life - School Timetable and Subjects',
        questionNumber: 2,
        questionText:
          'Teacher: "Which subject do you have right after the chemistry class on Wednesdays?"\nStudent: "We have ------. We learn about computers, algorithms and flowcharts."\n\nWhich school subject is the student talking about?',
        options: {
          A: 'History',
          B: 'Computer Science',
          C: 'Geography',
          D: 'Physical Education',
          E: 'Visual Arts',
        },
        correctAnswer: 'B',
        explanation: 'Bilgisayar, algoritma ve akış şemalarının öğrenildiği ders Bilgisayar Bilimi\'dir (Computer Science). Doğru seçenek B\'dir.',
        hintForSocratic: 'Computers, algorithms ve flowcharts hangi ders ile ilgilidir?',
      },
      {
        id: 'l1-u-ing-q3',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 2: Classroom Life - Friendships & Social Interactions',
        questionNumber: 3,
        questionText:
          'Selim: "Could you lend me your dictionary for the English vocabulary exercise?"\nCan: "------. Here you are!"\n\nWhich of the following polite expressions completes Can\'s answer?',
        options: {
          A: 'Certainly, of course',
          B: 'I completely disagree',
          C: 'I am afraid I can\'t',
          D: 'Never mind, forget it',
          E: 'No way, I hate sharing',
        },
        correctAnswer: 'A',
        explanation: '"Here you are" (Buyur, al) diyerek sözlüğü veren Can, olumlu ve kibar bir kabul ifadesi kullanmıştır: "Certainly, of course" (Kesinlikle, elbette). Doğru seçenek A\'dır.',
        hintForSocratic: 'Olumlu bir rica cevabı arıyoruz; "Here you are" dediğine göre kabul etmiştir.',
      },
      {
        id: 'l1-u-ing-q4',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 3: Personal Life - Personality Adjectives',
        questionNumber: 4,
        questionText:
          'Choose the ODD one out in terms of personality traits:',
        options: {
          A: 'Generous',
          B: 'Honest',
          C: 'Reliable',
          D: 'Curly',
          E: 'Friendly',
        },
        correctAnswer: 'D',
        explanation: 'Generous (cömert), Honest (dürüst), Reliable (güvenilir) ve Friendly (arkadaş canlısı) kişilik sıfatlarıdır (personality). Curly (kıvırcık) ise fiziksel görünüş sıfatıdır (physical appearance). Doğru seçenek D\'dir.',
        hintForSocratic: 'Kişilik (iç özellik) ile dış görünüşü ayırt et: Saçın kıvırcık olması kişilik midir?',
      },
      {
        id: 'l1-u-ing-q5',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 4: Family Life - Daily Routines',
        questionNumber: 5,
        questionText:
          '"My father is a surgeon. He works at a central hospital and he usually performs critical operations early in the morning."\n\nWhat does the speaker\'s father do for a living?',
        options: {
          A: 'He is a medical doctor / surgeon.',
          B: 'He is a high school teacher.',
          C: 'He is a civil engineer.',
          D: 'He is a graphic designer.',
          E: 'He is a lawyer in a courthouse.',
        },
        correctAnswer: 'A',
        explanation: 'Surgeon (cerrah) hastanede ameliyat yapan bir tıp doktorudur (medical doctor / surgeon). Doğru seçenek A\'dır.',
        hintForSocratic: 'Surgeon ve operations kelimeleri hangi mesleği işaret eder?',
      },
    ],
  },
];
