import type { OnlineExam } from '@/types/online-exam';

// MEB Türkiye Yüzyılı Maarif Modeli (9. Sınıf) Konu & Ünite Pekiştirme Testleri

export const LISE1_UNIT_TESTS: OnlineExam[] = [
  // 1. İNGİLİZCE (Theme 1: School Life)
  {
    id: 'exam-lise1-unit-ing-1',
    slug: 'meb-9-ingilizce-theme-1-school-life-testi',
    title: '9. Sınıf İngilizce Theme 1: School Life Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli İngilizce Theme 1: School Life ünitesi için özel hazırlanmış 5 soruluk hızlı pekiştirme testi.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'ingilizce',
    courseName: 'İngilizce',
    questionCount: 5,
    durationMinutes: 15,
    difficulty: 'Orta',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: 'Theme 1: School Life',
    questions: [
      {
        id: 'l1-u-ing-q1',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 1: School Life - Countries, Nationalities & Capitals',
        questionNumber: 1,
        questionText:
          'Match the student with their country and language:\n\n"Pierre is from France. His native language is ------, and the capital of his country is ------."\n\nWhich pair completes the sentence?',
        options: {
          A: 'French / Paris',
          B: 'France / Lyon',
          C: 'German / Berlin',
          D: 'Spanish / Madrid',
          E: 'Italian / Rome',
        },
        correctAnswer: 'A',
        explanation: 'Fransa\'dan (France) olan birinin ana dili Fransızca (French), başkenti ise Paris\'tir. Doğru seçenek A\'dır.',
        hintForSocratic: 'Fransa\'nın ana dili ve başkenti hangisidir?',
      },
      {
        id: 'l1-u-ing-q2',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 1: School Life - School Timetable and Subjects',
        questionNumber: 2,
        questionText:
          'Teacher: "Which subject do you have right after the chemistry class on Wednesdays?"\nStudent: "We have ------. We learn about computers, algorithms and flowcharts."\n\nWhich school subject is the student talking about?',
        options: {
          A: 'History',
          B: 'Computer Science',
          C: 'Geography',
          D: 'Physical Education',
          E: 'Visual Arts',
        },
        correctAnswer: 'B',
        explanation: 'Bilgisayar, algoritma ve akış şemalarının öğrenildiği ders Bilgisayar Bilimi\'dir (Computer Science). Doğru seçenek B\'dir.',
        hintForSocratic: 'Computers, algorithms ve flowcharts hangi ders ile ilgilidir?',
      },
      {
        id: 'l1-u-ing-q3',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 2: Classroom Life - Friendships & Social Interactions',
        questionNumber: 3,
        questionText:
          'Selim: "Could you lend me your dictionary for the English vocabulary exercise?"\nCan: "------. Here you are!"\n\nWhich of the following polite expressions completes Can\'s answer?',
        options: {
          A: 'Certainly, of course',
          B: 'I completely disagree',
          C: 'I am afraid I can\'t',
          D: 'Never mind, forget it',
          E: 'No way, I hate sharing',
        },
        correctAnswer: 'A',
        explanation: '"Here you are" (Buyur, al) diyerek sözlüğü veren Can, olumlu ve kibar bir kabul ifadesi kullanmıştır: "Certainly, of course" (Kesinlikle, elbette). Doğru seçenek A\'dır.',
        hintForSocratic: 'Olumlu bir rica cevabı arıyoruz; "Here you are" dediğine göre kabul etmiştir.',
      },
      {
        id: 'l1-u-ing-q4',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 3: Personal Life - Personality Adjectives',
        questionNumber: 4,
        questionText:
          'Choose the ODD one out in terms of personality traits:',
        options: {
          A: 'Generous',
          B: 'Honest',
          C: 'Reliable',
          D: 'Curly',
          E: 'Friendly',
        },
        correctAnswer: 'D',
        explanation: 'Generous (cömert), Honest (dürüst), Reliable (güvenilir) ve Friendly (arkadaş canlısı) kişilik sıfatlarıdır (personality). Curly (kıvırcık) ise fiziksel görünüş sıfatıdır (physical appearance). Doğru seçenek D\'dir.',
        hintForSocratic: 'Kişilik (iç özellik) ile dış görünüşü ayırt et: Saçın kıvırcık olması kişilik midir?',
      },
      {
        id: 'l1-u-ing-q5',
        courseKey: 'ingilizce',
        courseName: 'İngilizce',
        topicName: 'Theme 4: Family Life - Daily Routines',
        questionNumber: 5,
        questionText:
          '"My father is a surgeon. He works at a central hospital and he usually performs critical operations early in the morning."\n\nWhat does the speaker\'s father do for a living?',
        options: {
          A: 'He is a medical doctor / surgeon.',
          B: 'He is a high school teacher.',
          C: 'He is a civil engineer.',
          D: 'He is a graphic designer.',
          E: 'He is a lawyer in a courthouse.',
        },
        correctAnswer: 'A',
        explanation: 'Surgeon (cerrah) hastanede ameliyat yapan bir tıp doktorudur (medical doctor / surgeon). Doğru seçenek A\'dır.',
        hintForSocratic: 'Surgeon ve operations kelimeleri hangi mesleği işaret eder?',
      },
    ],
  },

  // 2. MATEMATİK (1. Tema: Sayılar)
  {
    id: 'exam-lise1-unit-mat-1',
    slug: 'meb-9-matematik-tema-1-sayilar-testi',
    title: '9. Sınıf Matematik 1. Tema: Sayılar Pekiştirme Testi',
    description: 'Türkiye Yüzyılı Maarif Modeli: Gerçek sayıların üslü/köklü gösterimleri, sayı aralıkları ve özdeşlikler pekiştirme sınavı.',
    tier: 'lise1',
    type: 'mini',
    courseKey: 'matematik',
    courseName: 'Matematik (9. Sınıf)',
    questionCount: 5,
    durationMinutes: 20,
    difficulty: 'Orta',
    isPro: false,
    badgeText: 'ÜNİTE PEKİŞTİRME',
    unitName: '1. Tema: Sayılar',
    questions: [
      {
        id: 'l1-u-mat-q1',
        courseKey: 'matematik',
        courseName: 'Matematik',
        topicName: '1. Tema: Sayılar - Gerçek Sayıların Üslü ve Köklü Gösterimleri',
        questionNumber: 1,
        questionText: '2^(x+1) = 32 olduğuna göre 3^(x-1) kaçtır?',
        options: {
          A: '3',
          B: '9',
          C: '27',
          D: '81',
          E: '243',
        },
        correctAnswer: 'C',
        explanation: '2^(x+1) = 32 = 2⁵ olduğundan x + 1 = 5 ⇒ x = 4 bulunur. 3^(x-1) = 3^(4-1) = 3³ = 27 olur.',
        hintForSocratic: '32 sayısını 2\'nin kaçıncı kuvveti olarak yazabilirsin?',
      },
    ],
  },
];
