import type { TopicStudyNote } from '@/types/study';

export const FEN_NOTES: TopicStudyNote[] = [
  {
    topicId: 'fen-mevsimler',
    courseKey: 'fen',
    courseName: 'Fen Bilimleri',
    topicName: 'Mevsimler ve İklim',
    lgsFrequency: 'Her yıl 1-2 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Mevsimlerin oluşmasının 2 temel sebebi vardır: 1) Dünya\'nın Güneş etrafında dolanması (Yıllık hareket), 2) Dünya\'nın eksen eğikliği (23° 27\').',
      'Dünya\'nın Güneş\'e olan mesafesinin mevsimlerin oluşumuyla HİÇBİR İLGİSİ YOKTUR! (Kuzey Yarım Küre kış yaşarken Güneş\'e en yakındır - 3 Ocak).',
      'Güneş ışınları bir bölgeye dik (90°) veya dike yakın açıyla gelirse birim yüzeye düşen enerji fazla olur -> Yaz yaşanır, gölge boyu KISA olur.',
      'Güneş ışınları eğik açıyla gelirse birim yüzeye düşen enerji az olur -> Kış yaşanır, gölge boyu UZUN olur.',
      '21 Mart - 23 Eylül (Ekinoks): Gece-gündüz eşitliği (12 saat gece, 12 saat gündüz). Güneş ışınları Ekvator\'a dik gelir.',
      '21 Haziran: Kuzey Yarım Küre\'de Yaz, Güney\'de Kış başlangıcı. Işınlar Yengeç Dönencesi\'ne dik gelir. Kuzey\'de en uzun gündüz.',
      '21 Aralık: Güney Yarım Küre\'de Yaz, Kuzey\'de Kış başlangıcı. Işınlar Oğlak Dönencesi\'ne dik gelir. Kuzey\'de en uzun gece.',
      'İklim: Geniş bölgede uzun yıllar (35-40 yıl) değişmeyen hava şartları ortalamasıdır (Klimatoloji). Hava Durumu: Dar alanda kısa süreli değişkenliktir (Meteoroloji).',
    ],
    formulas: [
      'Geliş Açısı ↑ => Birim Yüzeye Düşen Isı Enerjisi ↑ => Sıcaklık ↑',
      'Geliş Açısı ↑ (Dike Yakın) => Gölge Boyu ↓ (Kısalır)',
      'Eksen Eğikliği: 23° 27\' (Farklı yarım kürelerde zıt mevsimler oluşturur)',
    ],
    mebTraps: [
      'MEB Tuzak 1: "Dünya Güneş\'e yaklaştığı için yaz olur" çeldiricisine KESİNLİKLE DÜŞMEYİN.',
      'MEB Tuzak 2: Işık dik geldiğinde AYDINLANAN ALAN KÜÇÜK, birim alana düşen ENERJİ FAZLADIR. Işık eğik geldiğinde AYDINLANAN ALAN BÜYÜK, ENERJİ AZDIR.',
      'MEB Tuzak 3: 21 Mart ve 23 Eylül\'de Dünya\'nın her yerinde gece ve gündüz süresi eşittir (12 saat).',
    ],
    questionStrategy:
      'Görseldeki dönence çizgilerini ve ışığın geliş açısını incele. Işık hangi yarım küreye dik geliyorsa orada yaz olduğunu ve gölge boyunun en kısa olduğunu hatırla.',
    relatedExamSlug: 'lgs-fen-unite-1-mevsimler-iklim',
    exampleQuestion: {
      questionText: '21 Haziran tarihinde Türkiye\'de öğle vakti düz bir zemine dikilen bir çubuğun gölge boyu ile Avustralya\'daki aynı çubuğun gölge boyu nasıl karşılaştırılır?',
      solutionSteps: [
        '1. Adım: Türkiye Kuzey Yarım Küre\'dedir. 21 Haziran\'da Kuzey\'de yaz başlar ve güneş ışınları dike en yakın açıyla gelir -> Gölge boyu EN KISADIR.',
        '2. Adım: Avustralya Güney Yarım Küre\'dedir. 21 Haziran\'da Güney\'de kış başlar ve ışınlar çok eğik gelir -> Gölge boyu EN UZUNDUR.',
        '3. Sonuç: Türkiye\'deki gölge boyu Avustralya\'dakinden çok daha kısadır.',
      ],
      keyTakeaway: 'Işığın geliş açısı büyüdükçe (dike yaklaştıkça) gölge boyu kısalır, sıcaklık artar!',
    },
  },
  {
    topicId: 'fen-dna-genetik',
    courseKey: 'fen',
    courseName: 'Fen Bilimleri',
    topicName: 'DNA ve Genetik Kod',
    lgsFrequency: 'Her yıl 2-3 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Genetik Yapıların Hiyerarşisi (Büyükten Küçüğe - KeDiGeNi): Kromozom > DNA > Gen > Nükleotid.',
      'Kromozom Sayısı Kuralı: Canlının gelişmişliği ile kromozom sayısı arasında HİÇBİR İLİŞKİ YOKTUR! (İnsan: 46, Moli balığı: 46, Eğrelti otu: 500).',
      'Nükleotid Yapısı: 1 Fosfat (P) + 1 Deoksiriboz Şekeri (D) + 1 Organik Baz (A, T, G, C). Nükleotidin adını içerisindeki ORGANİK BAZ belirler!',
      'Eşleşme Kuralı: Çift zincirli DNA\'da Adenin karşısına Timin (A=T), Guanin karşısına Sitozin (G=C) gelir.',
      'DNA\'da Eşitlikler: Toplam Nükleotid Sayısı = Toplam Fosfat = Toplam Şeker = Toplam Organik Baz Sayısı.',
      'Tüm İnsanlarda/Canlılarda Nükleotid Çeşitleri AYNI (4 çeşit: A, T, G, C), Çeşitliliği sağlayan nükleotidlerin SAYISI VE DİZİLİMİDİR!',
      'DNA Eşlenmesi: Fermuar gibi açılır, sitoplazmadan çekirdeğe serbest nükleotidler girer, 2 adet kalıtsal olarak birebir aynı yeni DNA oluşur.',
      'DNA Onarımı: Karşılıklı zincirlerden biri boşsa veya yanlış baz gelmişse onarılır; KARŞILIKLI İKİ ZİNCİR BİRDEN BOŞSA ONARILAMAZ (Mutasyon kalıcı olur).',
    ],
    formulas: [
      'Hiyerarşi: Kromozom > DNA > Gen > Nükleotid (KeDiGeNi)',
      'Nükleotid = Fosfat + Şeker + Organik Baz',
      'Adenin (A) = Timin (T)  |  Guanin (G) = Sitozin (C)',
      'Toplam Nükleotid = Toplam Fosfat = Toplam Şeker',
    ],
    mebTraps: [
      'MEB Tuzak 1: Farklı canlı türlerinin nükleotid çeşitlerinin farklı olduğunu sanmak! TÜM CANLILARDA AYNI 4 ÇEŞİT BAZ (A, T, G, C) VARDIR.',
      'MEB Tuzak 2: Kromozom sayısı fazla olan canlının daha gelişmiş olduğunu düşünmek; kromozom sayısı gelişmişlik ölçütü değildir.',
      'MEB Tuzak 3: DNA eşlenmesinde sitoplazmadaki serbest nükleotid sayısı AZALIR, çekirdekteki nükleotid sayısı ARTAR.',
    ],
    questionStrategy:
      'Grafik sorularında sitoplazma ve çekirdek nükleotid değişimine dikkat et. DNA onarımı sorularında iki zincirin aynı anda kopup kopmadığını kontrol et.',
    relatedExamSlug: 'lgs-fen-unite-2-dna-genetik-kod',
    exampleQuestion: {
      questionText: '1200 nükleotidden oluşan bir DNA molekülünde 200 adet Adenin nükleotidi bulunduğuna göre Guanin nükleotidi sayısı kaçtır?',
      solutionSteps: [
        '1. Adım: Adenin = Timin olduğundan 200 Adenin varsa 200 Timin vardır -> Toplam A + T = 400.',
        '2. Adım: Kalan nükleotidler Guanin ve Sitozindir: 1200 - 400 = 800.',
        '3. Adım: Guanin = Sitozin olduğundan 800 / 2 = 400 Guanin, 400 Sitozin bulunur.',
      ],
      keyTakeaway: 'Toplam sayıdan (A+T) çiftini çıkardıktan sonra kalanı ikiye bölerek G ve C sayılarına kolayca ulaşırsınız.',
    },
  },
  {
    topicId: 'fen-kalitim-biyoteknoloji',
    courseKey: 'fen',
    courseName: 'Fen Bilimleri',
    topicName: 'Kalıtım ve Biyoteknoloji',
    lgsFrequency: 'Her yıl 2 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Genotip: Canlının genetik yapısı (AA, Aa, aa). Fenotip: Dış görünüş (Sarı tohum, yeşil tohum vb.).',
      'Saf Döl (Homozigot): İki genin aynı olması (AA veya aa). Melez Döl (Heterozigot): Genlerin farklı olması (Aa).',
      'Baskın (Dominant): Etkisini her durumda gösteren gen (A). Çekinik (Resesif): Yalnızca saf olduğunda (aa) etkisini gösteren gen.',
      'Melez İki Bireyin Çaprazlanması (Aa × Aa): Genotip: %25 AA, %50 Aa, %25 aa (1:2:1). Fenotip: %75 Baskın, %25 Çekinik (3:1).',
      'Cinsiyet Kalıtımı: Anne XX, Baba XY. Doğan çocuğun kız veya erkek olma olasılığı HER DOĞUMDA DAİMA %50\'DİR! Cinsiyeti babadan gelen sperm (X veya Y) belirler.',
      'Akraba Evliliği: Çekinik genlerle taşınan ölümcül/hastalık genlerinin yan yana gelme (homozigot olma) olasılığını ARTIRIR.',
      'Mutasyon: DNA yapısının bozulması (Van kedisi, albinoluk, orak hücre). Üreme hücresindeyse kalıtsaldır, vücut hücresindeyse kalıtsal değildir.',
      'Modifikasyon: Çevre etkisiyle genin İŞLEYİŞİNİN değişmesi, DNA yapısı değişmez, KALITSAL DEĞİLDİR (Çuha çiçeğinin sıcaklığa göre renk değiştirmesi, kas yapma, arı sütüyle beslenen kraliçe arı).',
      'Adaptasyon: Canlının yaşama ve üreme şansını artıran kalıtsal uyumdur (Kaktüsün iğne yaprakları, bukalemun kamuflesi, kutup ayısının kalın yağ tabakası).',
      'Biyoteknoloji: Gen aktarımı, klonlama, gen tedavisi, DNA parmak izi, yapay döllenme.',
    ],
    formulas: [
      'Aa × Aa Çaprazlaması => %75 Baskın Fenotip, %25 Çekinik Fenotip',
      'Cinsiyet Olasılığı = Daima 1/2 (%50)',
      'Mutasyon = Gen Yapısı Değişir  |  Modifikasyon = Gen İşleyişi Değişir',
    ],
    mebTraps: [
      'MEB Tuzak 1: "Ailenin 3 kızı var, 4. çocuğun erkek olma olasılığı nedir?" sorusunda önceki doğumlar sonrakini ETKİLEMEZ; olasılık yine %50\'dir.',
      'MEB Tuzak 2: Modifikasyonu mutasyonla karıştırmak! Bronzlaşmak veya sporla kas yapmak gen yapısını değiştirmez, çocuğa aktarılmaz (Modifikasyondur).',
      'MEB Tuzak 3: Klonlamada yavru canlı çekirdeği alınan canlının birebir kopyasıdır, taşıyıcı veya yumurtası alınan canlının değil!',
    ],
    questionStrategy:
      'Çaprazlama sorularında çekinik fenotipli bireyden (aa) başla; çünkü çekinik fenotipin genotipi kesinlikle bellidir (küçük harflerden biri anneden diğeri babadan gelmiştir).',
    relatedExamSlug: 'lgs-fen-unite-2-kalitim',
    exampleQuestion: {
      questionText: 'Melez sarı tohumlu iki bezelye bitkisinin çaprazlanması sonucu yeşil tohumlu bezelye oluşma olasılığı kaçtır? (Sarı tohum geni yeşil tohum genine baskındır)',
      solutionSteps: [
        '1. Adım: Sarı tohum geni: A, Yeşil tohum geni: a.',
        '2. Adım: Her iki ebeveyn melez sarı olduğundan genotipleri Aa × Aa\'dır.',
        '3. Adım: Çaprazlama sonucu: AA, Aa, Aa, aa.',
        '4. Adım: Yeşil tohum çekinik olduğundan sadece "aa" genotiplidir.',
        '5. Adım: 4 ihtimalden 1\'i aa\'dır -> Olasılık = 1/4 (%25).',
      ],
      keyTakeaway: 'Melez × Melez çaprazlamalarında çekinik özellik daima %25 (1/4) oranında ortaya çıkar.',
    },
  },
  {
    topicId: 'fen-basinc',
    courseKey: 'fen',
    courseName: 'Fen Bilimleri',
    topicName: 'Basınç (Katı, Sıvı ve Gaz Basıncı)',
    lgsFrequency: 'Her yıl 2-3 soru (En belirleyici fen konusu)',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Katı Basıncı: P = Kuvvet (Ağırlık) / Yüzey Alanı. Ağırlık artarsa basınç artar (doğru orantı). Yüzey alanı küçülürse basınç artar (ters orantı). Bıçak bilemek, krampon çivisi basıncı artırır; kar ayakkabısı, traktör tekeri basıncı azaltır.',
      'Sıvı Basıncı: P = Derinlik (h) × Sıvı Yoğunluğu (d). Sıvının kabın şekline, genişliğine veya sıvı miktarına ASLA BAĞLI DEĞİLDİR!',
      'Pascal Prensibi: Sıvılar sıkıştırılamaz ve kapalı kaptaki sıvılar üzerlerine uygulanan basıncı HER YÖNE AYNEN iletir (hidrolik fren, berber koltuğu, su cenderesi).',
      'Açık Hava Basıncı (Torricelli): Deniz seviyesinde 0 °C\'de 76 cm cıva sütunu ile dengelenir. Yükseklere çıkıldıkça açık hava basıncı AZALIR.',
      'Kapalı Gaz Basıncı: Hacim küçülürse basınç artar, sıcaklık artarsa basınç artar.',
    ],
    formulas: [
      'Katı Basıncı: P = G / S',
      'Sıvı Basıncı: P = h · d (Derinlik × Yoğunluk)',
      'Pascal Prensibi: P1 = P2 (F1 / S1 = F2 / S2)',
    ],
    mebTraps: [
      'MEB Tuzak 1: Sıvı basıncında derinlik kabın tabanından değil, daima SIVININ EN ÜST SERBEST YÜZEYİNDEN aşağıya doğru ölçülür!',
      'MEB Tuzak 2: Katı cisim düzgün düşey olarak kesilip parçalandığında (örneğin dikdörtgen tuğla ortadan dik kesildiğinde) ağırlık ve yüzey aynı oranda azaldığı için tabana yapılan BASINÇ DEĞİŞMEZ!',
      'MEB Tuzak 3: Sıvı kabının genişliği veya içindeki toplam su miktarı tabandaki sıvı basıncını ETKİLEMEZ; sadece h ve d belirler.',
    ],
    questionStrategy:
      'Önce hangi basınç türünün sorulduğunu belirle (katı, sıvı, gaz). Deney düzeneklerinde değiştirilen tek değişkeni (bağımsız değişken) tespit et.',
    relatedExamSlug: 'lgs-fen-unite-3-basinc-uzmanlik',
    exampleQuestion: {
      questionText: 'Taban alanı 2S, üst alanı S olan kesik koni şeklindeki kapalı bir kap tamamen suyla doludur. Kap ters çevrildiğinde tabandaki sıvı basıncı ve kabın zemine yaptığı katı basıncı nasıl değişir?',
      solutionSteps: [
        '1. Adım: Sıvı Basıncı: Kap tamamen dolu olduğu için ters çevrilse de sıvı yüksekliği (h) ve yoğunluğu (d) değişmez -> Sıvı basıncı DEĞİŞMEZ.',
        '2. Adım: Katı Basıncı: Kabın taban alanı 2S\'den S\'ye düşmüştür (yüzey küçülmüştür). Toplam ağırlık aynı kaldığı halde yüzey küçüldüğü için zemine yapılan katı basıncı ARTAR.',
      ],
      keyTakeaway: 'Kabın içindeki sıvı basıncı ile kabın masaya yaptığı katı basıncını asla birbiriyle karıştırmayın!',
    },
  },
  {
    topicId: 'fen-madde-endustri',
    courseKey: 'fen',
    courseName: 'Fen Bilimleri',
    topicName: 'Madde ve Endüstri (Periyodik Sistem, Asit-Baz)',
    lgsFrequency: 'Her yıl 3-4 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Periyodik Sistem: Elementler artan ATOM NUMARALARINA (Proton sayısı - Moseley) göre sıralanmıştır. 7 periyot (yatay), 18 grup (8 A, 10 B düşey) bulunur.',
      'Aynı Gruptakiler: Son katmandaki elektron sayıları (değerlik elektronu) eşittir ve kimyasal özellikleri GENELLİKLE benzerdir.',
      'Periyodik Tablo İstisnaları: 1A grubunun ilk elementi HİDROJEN bir AMETALDİR! 8A grubundaki HELYUM\'un son katmanında 2 elektron vardır ama SOYGAZDIR!',
      'Fiziksel Değişim: Maddenin sadece dış görünüşü değişir, kimliği değişmez (Erime, buharlaşma, kırılma, yırtılma, çözünme).',
      'Kimyasal Değişim: Maddenin iç yapısı ve kimliği değişir (Yanma, paslanma, mayalanma, pişme, koku/gaz çıkışı, çökelek oluşumu).',
      'Kimyasal Tepkimelerde Korunanlar: TOPLAM KÜTLE DAİMA KORUNUR! Atom sayısı ve cinsi kesinlikle korunur. Molekül sayısı değişebilir.',
      'Asitler: pH 0-7, tatları ekşi, turnusolu KIRMIZI yapar, metallerle H₂ gazı çıkarır, mermeri aşındırır.',
      'Bazlar: pH 7-14, tatları acı, ele kayganlık hissi verir, turnusolu MAVİ yapar, cam ve porseleni matlaştırır.',
      'Asit Yağmurları: Fosil yakıtların yanmasıyla çıkan SO₂, NO₂, CO₂ gazları su buharıyla birleşerek asit yağmuru oluşturur.',
    ],
    formulas: [
      'Kütlenin Korunumu: Girenlerin Kütlesi = Ürünlerin Kütlesi',
      'Asit + Baz -> Tuz + Su (Nötralleşme)',
      'pH < 7 Asit  |  pH = 7 Nötr  |  pH > 7 Baz',
    ],
    mebTraps: [
      'MEB Tuzak 1: Helyum\'un değerlik elektron sayısını 8 sanmak! Helyum 2 elektronludur ama kararlı olduğu için 8A\'dadır.',
      'MEB Tuzak 2: Ağzı açık kapta gerçekleşen tepkimede gaz uçup giderse kap kütlesi azalır; ancak bu durum kütlenin korunumunu bozmaz, uçan gazla beraber toplam kütle korunmuştur.',
      'MEB Tuzak 3: Şekerin veya tuzun suda çözünmesi kimyasal değil FİZİKSEL bir değişimdir.',
    ],
    questionStrategy:
      'Kimyasal tepkime grafiklerinde azalan çizgiler GİRENLER, sıfırdan artan çizgiler ÜRÜNLERDİR. Girenlerin azalan miktarları toplamı ürünlerin artan miktarları toplamına eşit olmalıdır.',
    relatedExamSlug: 'lgs-fen-unite-4-madde-endustri',
    exampleQuestion: {
      questionText: 'Kapalı bir kapta 32 gram X maddesi ile 40 gram Y maddesi tepkimeye giriyor. Tepkime sonunda 10 gram Y artarken Z maddesi oluşuyor. Oluşan Z maddesi kaç gramdır?',
      solutionSteps: [
        '1. Adım: X tamamen kullanılmıştır: 32 gram.',
        '2. Adım: Y\'den 40 gram konmuş ama 10 gram artmıştır -> Harcanan Y = 40 - 10 = 30 gram.',
        '3. Adım: Tepkimeye giren toplam kütle = 32 + 30 = 62 gramdır.',
        '4. Adım: Kütlenin korunumuna göre oluşan Z = 62 gramdır.',
      ],
      keyTakeaway: 'Artan madde miktarı tepkimeye girmemiştir, girenler kütlesine sadece harcanan miktar dahil edilir!',
    },
  },
  {
    topicId: 'fen-basit-makineler',
    courseKey: 'fen',
    courseName: 'Fen Bilimleri',
    topicName: 'Basit Makineler (Kaldıraç, Makara, Eğik Düzlem)',
    lgsFrequency: 'Her yıl 2 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'ALTIN KURAL: HİÇBİR BASİT MAKİNEDE İŞTEN VEYA ENERJİDEN KAZANÇ SAĞLANAMAZ! Sadece iş yapma kolaylığı sağlanır.',
      'Kuvvet Kazancı: Kuvvetten kazanç varsa YOLDAN AYNI ORANDA KAYIP VARDIR. Yük / Kuvvet > 1 ise kuvvet kazancı vardır.',
      'Sabit Makara: Kuvvet kazancı YOKTUR (Kuvvet = Yük). Yalnızca kuvvetin yönünü değiştirerek iş kolaylığı sağlar.',
      'Hareketli Makara: 2 kat kuvvet kazancı vardır (F = P / 2). Ancak ipi 2 metre çekersen yük sadece 1 metre yükselir (yoldan 2 kat kayıp).',
      'Palangalar: Hareketli ve sabit makaraların birleşimidir. İpin çekilme yönü yukarıysa makara sayısı + 1\'e, aşağıysa makara sayısına bölünür.',
      'Kaldıraçlar: Kuvvet × Kuvvet Kolu = Yük × Yük Kolu. Kuvvet kolu yük kolundan uzunsa KUVVETTEN KAZANÇ vardır.',
      'Eğik Düzlem: DAİMA KUVVETTEN KAZANÇ SAĞLAR! Formül: Kuvvet × Boy (l) = Yük × Yükseklik (h). Eğik düzlemin boyu uzadıkça kuvvet kazancı artar.',
      'Çıkrık: Kuvvet kolu (R) yük kolundan (r) büyük olduğu için DAİMA kuvvet kazancı vardır (Kıyma makinesi, direksiyon, tornavida).',
    ],
    formulas: [
      'Kuvvet Kazancı = Yük (P) / Kuvvet (F) = Kuvvet Kolu / Yük Kolu',
      'Kaldıraç: F · Kuvvet Kolu = P · Yük Kolu',
      'Eğik Düzlem: F · l = P · h',
      'Sabit Makara: F = P  |  Hareketli Makara: F = P / 2',
    ],
    mebTraps: [
      'MEB Tuzak 1: "Bu basit makine ile işten kazanç sağlanmıştır" ifadesi %100 YANLIŞTIR! Yapılan iş hiçbir basit makinede değişmez.',
      'MEB Tuzak 2: Eğik düzlemde yüksekliği (h) değiştirmeden boyu (l) artırırsak uygulanan kuvvet KÜÇÜLÜR (daha az kuvvetle çıkarılır), yapılan iş ise DEĞİŞMEZ.',
      'MEB Tuzak 3: Hareketli makaranın ağırlığı soruda verildiyse yüke eklemeyi unutmayın.',
    ],
    questionStrategy:
      'Kaldıraç sorularında desteğin olduğu noktaya göre tork al (F × mesafe = P × mesafe). Eğik düzlemde dik üçgenin hipotenüsünün kuvvetle çarpıldığını hatırla.',
    relatedExamSlug: 'lgs-fen-unite-5-basit-makineler',
    exampleQuestion: {
      questionText: 'Ağırlığı 60 N olan bir yük, sürtünmesiz bir eğik düzlemde 5 metre uzunluğundaki yoldan 2 metre yüksekliğe çıkarılmak isteniyor. Uygulanması gereken kuvvet kaç Newton\'dur?',
      solutionSteps: [
        '1. Adım: Eğik düzlem formülü: Kuvvet × Yol (l) = Yük (P) × Yükseklik (h).',
        '2. Adım: F × 5 = 60 × 2.',
        '3. Adım: 5F = 120 => F = 24 Newton.',
        '4. Adım: 60 N\'luk yük 24 N ile taşınmıştır -> Kuvvet kazancı = 60 / 24 = 2,5 kattır.',
      ],
      keyTakeaway: 'Eğik düzlemde uygulanan kuvvet yükten daima küçüktür (daima kuvvetten kazanç vardır).',
    },
  },
  {
    topicId: 'fen-enerji-cevre',
    courseKey: 'fen',
    courseName: 'Fen Bilimleri',
    topicName: 'Enerji Dönüşümleri ve Çevre Bilimi (Fotosentez, Besin Zinciri)',
    lgsFrequency: 'Her yıl 2-3 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Besin Zinciri: Üretici -> Otçul (1. Tüketici) -> Etçil (2. Tüketici) -> Üst Avcı. Enerjinin ana kaynağı GÜNEŞ\'tir.',
      'Ayrıştırıcılar (Mantar ve Bakteriler): Besin zincirinin HER BASAMAĞINDA yer alır ve organik atıkları inorganik maddelere dönüştürür.',
      'Ekoloji Piramidinde Aşağıdan Yukarıya Çıkıldıkça: 1) Aktarılan enerji AZALIR (Her basamağa %10\'u geçer), 2) Biyokütle AZALIR, 3) Birey sayısı AZALIR, 4) Biyolojik birikim (Zehir miktarı) ARTAR, 5) Vücut büyüklüğü genellikle ARTAR.',
      'Fotosentez: Karbondioksit + Su + Işık -> Besin (Glikoz) + Oksijen. Sadece klorofilli canlılar ve IŞIKLI ORTAMDA gerçekleşir. Yapay ışıkta da fotosentez olur!',
      'Fotosentez Hızı: Işık şiddeti ve CO₂ miktarı arttıkça belirli bir noktaya kadar artar, sonra sabit kalır. En hızlı MOR ve KIRMIZI ışıkta, en yavaş YEŞİL ışıkta gerçekleşir!',
      'Oksijenli Solunum: Besin + Oksijen -> CO₂ + Su + 32 ATP (Mitokondride gerçekleşir, yüksek enerji).',
      'Fermantasyon (Oksijensiz): Sitoplazmada gerçekleşir. Etil alkol fermantasyonu (hamur mayalanması, CO₂ çıkar) ve Laktik asit fermantasyonu (yoğurt, yorgun kaslar, CO₂ ÇIKMAZ!).',
    ],
    formulas: [
      'Fotosentez: 6CO₂ + 6H₂O + Işık -> C₆H₁₂O₆ + 6O₂',
      'Oksijenli Solunum: C₆H₁₂O₆ + 6O₂ -> 6CO₂ + 6H₂O + Enerji (ATP)',
      '10% Kuralı: Üretici (10.000 J) -> 1. Tüketici (1.000 J) -> 2. Tüketici (100 J) -> 3. Tüketici (10 J)',
    ],
    mebTraps: [
      'MEB Tuzak 1: Bitkilerin sadece gündüz fotosentez, gece solunum yaptığı yanılgısı! BİTKİLER GECE VE GÜNDÜZ 24 SAAT KESİNTİSİZ SOLUNUM YAPAR; fotosentezi ise yalnızca ışık varken yapar.',
      'MEB Tuzak 2: Kireç suyunun CO₂ tutucu olduğunu unutmak! Kireç suyu CO₂ gördüğünde bulanır.',
      'MEB Tuzak 3: Biyolojik birikim (zehir) üreticide en az, zincirin en tepesindeki avcıda EN FAZLADIR.',
    ],
    questionStrategy:
      'Besin zincirinde bir canlının sayısı azaldığında zincirleme etkiyi oklarla takip et: O canlıyı yiyen aç kalır (azalır), o canlının yediği ise av baskısı kalktığı için çoğalır.',
    relatedExamSlug: 'lgs-fen-unite-6-enerji-donusumleri',
    exampleQuestion: {
      questionText: 'Ot -> Çekirge -> Kurbağa -> Yılan -> Kartal besin zincirinde ortama karışan tarım ilacının (zehirli atığın) vücudunda en çok ve en az biriktiği canlılar hangileridir?',
      solutionSteps: [
        '1. Adım: Ekoloji piramidinde aşağıdan yukarıya doğru biyolojik birikim (zehir) artar.',
        '2. Adım: En alttaki üreticide (Ot) zehir birikimi EN AZDIR.',
        '3. Adım: Piramidin en tepesindeki üst tüketicide (Kartal) zehir birikimi EN FAZLADIR.',
      ],
      keyTakeaway: 'Zehir dokularda parçalanamadığı için üst basamaklara çıktıkça katlanarak birikir.',
    },
  },
  {
    topicId: 'fen-elektrik',
    courseKey: 'fen',
    courseName: 'Fen Bilimleri',
    topicName: 'Elektrik Yükleri ve Elektrik Enerjisi',
    lgsFrequency: 'Her yıl 1-2 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Elektrik Yükleri: Pozitif (+) yük (proton fazlalığı), Negatif (-) yük (elektron fazlalığı), Nötr (Proton sayısı = Elektron sayısı).',
      'Yük Etkileşimi: Aynı yükler birbirini İTER (+ ile +, - ile -). Zıt yükler birbirini ÇEKER (+ ile -). NÖTR cisimler yüklü cisimler tarafından ÇEKİLİR!',
      'Sürtünme ile Elektriklenme: Yalnızca yalıtkanlar arasında olur. Ebonit (Plastik) çubuk yün kumaşa sürtülürse EKSİ (-), Cam çubuk ipek kumaşa sürtülürse ARTI (+) yüklenir. İki cisim EŞİT MİKTARDA VE ZIT YÜKLENİR.',
      'Dokunma ile Elektriklenme: Toplam yük cisimlerin kapasitelerine (yarıçaplarına) göre paylaşılır. Temas eden cisimlerin SON YÜK İŞARETLERİ KESİNLİKLE AYNI OLUR.',
      'Etki ile Elektriklenme (Kutuplanma): Yük geçişi olmaz, cisim içindeki yükler kutuplanır (yakın taraf zıt, uzak taraf aynı yükle yüklenir).',
      'Elektroskop: Bir cismin yüklü olup olmadığını ve yükün cinsini anlamaya yarar. Yüklü elektroskopa aynı yük yaklaştırılırsa yapraklar DAHA ÇOK AÇILIR; zıt yük yaklaştırılırsa BİRAZ KAPANIR.',
      'Topraklama: Yüklü cisimlerin nötr hale getirilmesi için iletken bir telle toprağa bağlanmasıdır.',
    ],
    formulas: [
      'Sürtünme: Ebonit (-) / Yün (+)  |  Cam (+) / İpek (-)',
      'Dokunma: q_son = (q1 + q2) / (r1 + r2) · r',
      'Topraklama: Son durum daima NÖTR',
    ],
    mebTraps: [
      'MEB Tuzak 1: Yüklü bir cismin nötr bir cismi çekemeyeceğini sanmak! Yüklü cisimler nötr cisimleri etkiyle kutuplandırarak KESİNLİKLE ÇEKER.',
      'MEB Tuzak 2: Elektriklenmede protonların hareket ettiğini düşünmek; KATI İLETKENLERDE SADECE ELEKTRONLAR HAREKET EDER, protonlar çekirdekte sabittir!',
    ],
    questionStrategy:
      'Elektroskop sorularında dokunduruluyor mu yoksa sadece yaklaştırılıyor mu (etki) dikkat et. Dokunmada yük paylaşımı, yaklaştırmada kutuplanma kurallarını uygula.',
    relatedExamSlug: 'lgs-fen-unite-7-elektrik',
    exampleQuestion: {
      questionText: 'Pozitif (+) yüklü bir cisim, nötr ve iletken bir elektroskobun topuzuna DOKUNDURULMADAN sadece yaklaştırılırsa elektroskobun topuzu ve yaprakları hangi yükle yüklenir?',
      solutionSteps: [
        '1. Adım: Cisim yaklaştırıldığı için olay etki ile elektriklenmedir (yük geçişi olmaz).',
        '2. Adım: Pozitif (+) yüklü cisim, elektroskoptaki serbest elektronları (-) topuza doğru çeker.',
        '3. Adım: Topuzda (-) yükler birikir, yapraklarda ise (+) yükler kalır.',
        '4. Sonuç: Topuz negatif (-), yapraklar pozitif (+) olur ve yapraklar açılır.',
      ],
      keyTakeaway: 'Etki ile elektriklenmede yaklaştırılan yere yakın kutup daima zıt işaretle yüklenir.',
    },
  },
];
