import type { TopicStudyNote } from '@/types/study';

export const MATEMATIK_NOTES: TopicStudyNote[] = [
  {
    topicId: 'mat-ebob-ekok',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Çarpanlar ve Katlar (EBOB - EKOK)',
    lgsFrequency: 'Her yıl kesin 1-2 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Büyük parçalardan küçük parçalar elde ediliyorsa (bölme, paylaştırma, paketleme, eş kareler) -> EBOB kullanılır.',
      'Küçük parçalardan büyük bir bütün oluşturuluyorsa (fayans döşeme, nöbet tutma, zillerin çalması, adımlama) -> EKOK kullanılır.',
      'Aralarında asal iki sayının EBOB\'u 1, EKOK\'u ise bu iki sayının çarpımıdır.',
      'İki doğal sayının çarpımı, bu sayıların EBOB\'u ile EKOK\'unun çarpımına eşittir: A × B = EBOB(A, B) × EKOK(A, B).',
    ],
    formulas: [
      'EBOB: En Büyük Ortak Bölen (Bütünden parçaya)',
      'EKOK: En Küçük Ortak Kat (Parçadan bütüne)',
      'Kesim Sayısı = Parça Sayısı - 1',
      'Direk / Ağaç Sayısı = Çevre / EBOB (Kapalı şekillerde)',
    ],
    mebTraps: [
      'MEB Tuzak 1: Parça sayısı ile kesim sayısını karıştırmak! Bir kalası 4 parçaya bölmek için 3 kesim yapılır, 4 değil.',
      'MEB Tuzak 2: Kenarları 20 m ve 30 m olan bir bahçenin köşelerine de dikilmek şartıyla ağaç sayısı sorulduğunda, köşe noktalarını fazladan eklemeyin; Çevre / EBOB formülü köşeleri zaten kapsar.',
      'MEB Tuzak 3: "En az kaç paket/kare" dendiğinde önce EBOB ile parça boyutunu bulup, ardından toplam alanı/hacmi parçanın alanına/hacmine bölmeyi unutmayın.',
    ],
    questionStrategy:
      'Önce sorunun bölme (EBOB) mi yoksa katlanarak büyüme (EKOK) mi olduğunu tespit et. Sayıların altına EBOB veya EKOK değerini yaz, ardından sorunun senden ne istediğine (parça sayısı mı, kesim sayısı mı, toplam ücret mi) dikkat et.',
    relatedExamSlug: 'lgs-mat-unite-1-carpanlar-katlar',
    exampleQuestion: {
      questionText: 'Kenar uzunlukları 48 m ve 60 m olan dikdörtgen şeklindeki bir tarlanın etrafına, köşelerine de gelmek şartıyla eşit aralıklarla fidan dikilecektir. En az kaç fidan gerekir?',
      solutionSteps: [
        '1. Adım: Fidan aralıklarının en büyük olması gerekir -> EBOB(48, 60) hesaplanır.',
        '2. Adım: 48 ve 60\'ın EBOB\'u = 12 metredir. Yani her 12 metrede bir fidan dikilecek.',
        '3. Adım: Tarlanın çevresi = 2 × (48 + 60) = 216 metredir.',
        '4. Adım: Gerekli fidan sayısı = Çevre / EBOB = 216 / 12 = 18 adet fidandır.',
      ],
      keyTakeaway: 'Kapalı dikdörtgen çevrelerinde köşeler formülün içindedir, köşeleri ayrıca ekleyip fazladan saymayın!',
    },
  },
  {
    topicId: 'mat-uslu',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Üslü İfadeler',
    lgsFrequency: 'Her yıl 2-3 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Çarpma: Tabanlar aynıysa üsler toplanır (a^x · a^y = a^(x+y)). Üsler aynıysa tabanlar çarpılır (a^x · b^x = (a·b)^x).',
      'Bölme: Tabanlar aynıysa payın üssünden paydanın üssü çıkarılır (a^x / a^y = a^(x-y)).',
      'Üssün Üssü: Üsler çarpılır ((a^x)^y = a^(x·y)).',
      'Negatif Üs: Sayıyı çarpmaya göre ters çevirir, sayının işaretini değiştirmez (a^(-n) = 1 / a^n).',
      'Bilimsel Gösterim: a × 10^n şeklinde yazılır. Buradaki "a" katsayısı 1 ≤ |a| < 10 şartını sağlamalıdır.',
    ],
    formulas: [
      'a^0 = 1 (a ≠ 0)',
      '(-a)^çift = +a^çift  |  (-a)^tek = -a^tek',
      'a^(-n) = 1 / a^n',
      '1 ≤ |a| < 10 için a × 10^n (Bilimsel Gösterim)',
    ],
    mebTraps: [
      'MEB Tuzak 1: Parantez tuzağı! -3^2 = -9 iken (-3)^2 = +9\'dur. Parantez yoksa üs işareti etkilemez.',
      'MEB Tuzak 2: Bilimsel gösterimde katsayının 10 olamayacağını unutmak! 10 × 10^6 bilimsel gösterim değildir, 1 × 10^7 olmalıdır.',
      'MEB Tuzak 3: "Kaç basamaklıdır?" sorularında ifadeyi 2^n × 5^n = 10^n kalıbına dönüştürmeyi unutmayın.',
    ],
    questionStrategy:
      'Tüm tabanları en küçük asal tabana (genellikle 2, 3 veya 5 tabanına) çevir. Parantez ve eksi işaretlerine aşırı dikkat et.',
    relatedExamSlug: 'lgs-mat-unite-2-uslu-sayilar',
    exampleQuestion: {
      questionText: 'Bir laboratuvardaki bakteri sayısı her 30 dakikada bir 2 katına çıkmaktadır. Başlangıçta 8^4 bakteri bulunan kapta 4 saat sonra kaç bakteri bulunur?',
      solutionSteps: [
        '1. Adım: Başlangıç bakteri sayısını 2 tabanına çevir: 8^4 = (2^3)^4 = 2^12.',
        '2. Adım: 4 saat = 240 dakika. 30 dakikada bir bölünüyorsa 240 / 30 = 8 kez çoğalır.',
        '3. Adım: 8 kez 2 ile çarpmak = 2^8 katına çıkması demektir.',
        '4. Adım: Son durum = 2^12 × 2^8 = 2^(12+8) = 2^20 bakteri.',
      ],
      keyTakeaway: 'Zaman periyodu problemlerinde önce toplam bölünme sayısını bulup üs olarak ekleyin.',
    },
  },
  {
    topicId: 'mat-karekok',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Kareköklü İfadeler',
    lgsFrequency: 'Her yıl 2-3 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Alanı bilinen bir karenin bir kenar uzunluğu, alanının kareköküne eşittir: Kenar = √Alan.',
      'Kök dışına çıkarma: a√b biçiminde yazarken içerideki tam kare çarpan dışarı çıkar (√72 = √(36×2) = 6√2).',
      'Toplama ve Çıkarma: Yalnızca kök içleri aynı olan ifadelerin katsayıları toplanır ya da çıkarılır (3√2 + 5√2 = 8√2). Kök içleri kesinlikle toplanmaz!',
      'Çarpma ve Bölme: Katsayılar kendi arasında, kök içleri kendi arasında çarpılır / bölünür.',
      'Ondalık Gösterimlerin Karekökü: Kesre çevirip pay ve paydanın ayrı ayrı kökünü al (√0,04 = √(4/100) = 2/10 = 0,2).',
    ],
    formulas: [
      '√(a² · b) = a√b',
      'a√x + b√x = (a + b)√x',
      '√a · √b = √(a · b)',
      'Tam kareler: 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400',
    ],
    mebTraps: [
      'MEB Tuzak 1: √(a + b) ifadesini √a + √b olarak ayırmak KESİNLİKLE YANLIŞTIR! Örneğin √(16 + 9) = √25 = 5\'tir, 4 + 3 = 7 değildir!',
      'MEB Tuzak 2: İki tam sayı arasındaki yeri tahmin ederken karelerini karşılaştırın (Örn: 7 = √49 ile 8 = √64 arasında). Hangisine daha yakın olduğunu farkın küçüklüğünden bulun.',
    ],
    questionStrategy:
      'Önce kök dışına çıkabilen tüm sayıları a√b biçimine getir. Sayı doğrusu veya uzunluk sorularında kare alarak tam sayı sınırlarını belirle.',
    relatedExamSlug: 'lgs-mat-unite-3-karekoklu-ifadeler',
    exampleQuestion: {
      questionText: 'Alanı 180 cm² olan kare şeklindeki bir kartondan alanı 20 cm² olan kare şeklinde bir parça kesilip atılıyor. Kalan şeklin çevresi nasıl değişir?',
      solutionSteps: [
        '1. Adım: Büyük karenin bir kenarı = √180 = √(36 × 5) = 6√5 cm.',
        '2. Adım: Kesilen küçük karenin bir kenarı = √20 = √(4 × 5) = 2√5 cm.',
        '3. Adım: Köşeden kesilirse çevre DEĞİŞMEZ! Kenardan (ortadan) kesilirse çevre 2 kenar kadar (2 × 2√5 = 4√5 cm) ARTAR!',
      ],
      keyTakeaway: 'Geometrik kare kesimlerinde köşeden kesilince çevrenin asla değişmediğini MEB sıkça sorar!',
    },
  },
  {
    topicId: 'mat-veri-analizi',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Veri Analizi',
    lgsFrequency: 'Her yıl kesin 1 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Daire Grafiği: Bir bütünün parçalarını göstermede en etkilidir. Toplam miktar 360° ile orantılanır (360° = Toplam Veri).',
      'Sütun Grafiği: Farklı kategorilerin büyüklüklerini ve miktarlarını karşılaştırmak için en uygundur.',
      'Çizgi Grafiği: Bir verinin zamana bağlı artış, azalış ve değişim eğilimini (sıcaklık, döviz, boy vb.) incelemek için idealdir.',
      'Grafikler Arası Dönüşüm: Daire grafiğindeki merkez açılar sadeleştirilerek ortak bir "k" katı bulunur (Örn: 120° = 4k, 90° = 3k, 150° = 5k).',
    ],
    formulas: [
      'Merkez Açı = (İstenen Parça / Toplam Miktar) × 360°',
      'Yüzde = (Merkez Açı / 360°) × 100',
    ],
    mebTraps: [
      'MEB Tuzak 1: Daire grafiğindeki açıyı doğrudan miktar sanmak! Açı sadece oranı verir, gerçek miktar toplam sayıya göre hesaplanmalıdır.',
      'MEB Tuzak 2: Sütun grafiğinde dikey eksenin 0\'dan başlamamış olması! Eksen 0\'dan başlamadığında sütun boyları arasındaki oran yanıltıcı görünür.',
    ],
    questionStrategy:
      'Daire grafiği verildiğinde önce bilinmeyen açıyı 360°\'den çıkararak bul. Ardından açıların EBOB\'unu alıp hepsini en küçük "k" cinsinden yaz (Örn: 60°->k, 120°->2k, 180°->3k).',
    relatedExamSlug: 'lgs-mat-unite-4-veri-analizi',
    exampleQuestion: {
      questionText: 'Bir çiftlikteki hayvanların dağılımı daire grafiğinde gösterilmiştir: Koyun 150°, İnek 120°, Keçi ise kalan açıdır. Çiftlikte 36 keçi olduğuna göre toplam kaç hayvan vardır?',
      solutionSteps: [
        '1. Adım: Keçilerin açısı = 360° - (150° + 120°) = 360° - 270° = 90°.',
        '2. Adım: Orantı kur: 90° \'lik dilim 36 keçiye denk geliyorsa, 360° (tüm hayvanlar) kaça denk gelir?',
        '3. Adım: 360°, 90°\'nin 4 katıdır. Toplam hayvan sayısı = 36 × 4 = 144 adettir.',
      ],
      keyTakeaway: 'Açılar arası kat ilişkisi (360 / 90 = 4 kat) kurarak uzun içler-dışlar çarpımı yapmadan saniyeler içinde sonuca ulaşın!',
    },
  },
  {
    topicId: 'mat-olasilik',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Basit Olayların Olma Olasılığı',
    lgsFrequency: 'Her yıl kesin 1 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Olasılık Formülü: Bir olayın olma olasılığı = (İstenen Olası Durumların Sayısı) / (Tüm Olası Durumların Sayısı).',
      'Olasılık Değer Aralığı: Bir olayın olasılığı daima 0 ile 1 arasındadır: 0 ≤ P(A) ≤ 1. Asla negatif veya 1\'den büyük olamaz!',
      'İmkânsız Olay: Gerçekleşme şansı olmayan olaydır, olasılığı 0\'dır (Örn: Zar atıldığında 8 gelmesi).',
      'Kesin Olay: Kesinlikle gerçekleşecek olaydır, olasılığı 1\'dir (Örn: Havaya atılan zarın 7\'den küçük gelmesi).',
      'Tümleyen Olay: Bir olayın olma olasılığı ile olmama olasılığının toplamı 1\'dir: P(Olma) + P(Olmama) = 1.',
      'Eşit Olasılık: Çıktıların şanslarının birbirine eşit olması durumudur (Örn: Hilesiz madeni parada Yazı ve Tura gelme şansı 1/2\'dir).',
    ],
    formulas: [
      'Olasılık P = İstenen Durum Sayısı / Tüm Durumların Sayısı',
      'P(A) + P(A\') = 1  =>  P(Olmama) = 1 - P(Olma)',
      '0 ≤ P(Olay) ≤ 1',
    ],
    mebTraps: [
      'MEB Tuzak 1: Torbadan top/kart çekildikten sonra GERİ ATILMADIĞI durumlarda paydadaki toplam sayıyı 1 azaltmayı unutmak!',
      'MEB Tuzak 2: "Asal sayı olma olasılığı" dendiğinde 1 sayısını asal kabul etmek (1 ASAL DEĞİLDİR; en küçük ve tek çift asal 2\'dir).',
      'MEB Tuzak 3: "En az" veya "en fazla" koşullarında sınır değerleri hesaba katmamak.',
    ],
    questionStrategy:
      'Önce mutlaka paydadaki "Tüm Durumların Sayısı"nı eksiksiz listele. Sonra soru kökünün istediği özel şartı sağlayan elemanları işaretleyip sadeleştir.',
    relatedExamSlug: 'lgs-mat-unite-5-olasilik',
    exampleQuestion: {
      questionText: '1\'den 20\'ye kadar numaralandırılmış özdeş 20 kart bir torbaya konuluyor. Rastgele çekilen bir kartın asal sayı veya tam kare sayı olma olasılığı kaçtır?',
      solutionSteps: [
        '1. Adım: Tüm durumlar = 20 tanedir.',
        '2. Adım: Asal sayılar: 2, 3, 5, 7, 11, 13, 17, 19 (Toplam 8 tane).',
        '3. Adım: Tam kare sayılar: 1, 4, 9, 16 (Toplam 4 tane).',
        '4. Adım: Ortak eleman var mı? Hayır, asallar ile tam kareler kesişmez. İstenen durumlar = 8 + 4 = 12.',
        '5. Adım: Olasılık = 12 / 20 = 3 / 5.',
      ],
      keyTakeaway: 'İstenen durumları toplarken her iki gruba da dahil olan ortak sayı varsa onu iki kez saymamaya çok dikkat edin!',
    },
  },
  {
    topicId: 'mat-cebir',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Cebirsel İfadeler ve Özdeşlikler',
    lgsFrequency: 'Her yıl 2-3 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Özdeşlik: Değişkenin her değeri için daima doğru olan eşitliklerdir. Denklem ile karıştırılmamalıdır.',
      'Tam Kare (İki Terimin Toplamının Karesi): (a + b)² = a² + 2ab + b².',
      'Tam Kare (İki Terimin Farkının Karesi): (a - b)² = a² - 2ab + b².',
      'İki Kare Farkı (LGS\'nin 1 Numaralı Özdeşliği): a² - b² = (a - b) × (a + b).',
      'Ortak Çarpan Parantezine Alma: Her terimde ortak olan sayı veya harf başa alınır: 3x² + 6x = 3x(x + 2).',
    ],
    formulas: [
      '(a + b)² = a² + 2ab + b²',
      '(a - b)² = a² - 2ab + b²',
      'a² - b² = (a - b)(a + b)',
    ],
    mebTraps: [
      'MEB Tuzak 1: (a + b)² ifadesini a² + b² olarak yazmak en büyük hatadır! Ortadaki 2ab çarpımını asla unutmayın.',
      'MEB Tuzak 2: Geometrik modellemelerde boyalı alan sorulduğunda büyük şeklin alanından beyaz kutuların alanını çıkarıp iki kare farkı uygulayın.',
    ],
    questionStrategy:
      'Geometrik şekilli sorularda kenarları harflendirip alanları ayrı ayrı topla. Çıkan ifadeyi tam kare veya iki kare farkı formülleriyle eşleştir.',
    relatedExamSlug: 'lgs-mat-unite-5-cebirsel-ifadeler',
    exampleQuestion: {
      questionText: 'Bir kenarı (2x + 3) cm olan kare şeklindeki panonun köşelerinden bir kenarı 2 cm olan 4 adet eş kare kesilip atılıyor. Kalan alanın cebirsel ifadesi nedir?',
      solutionSteps: [
        '1. Adım: Büyük karenin alanı = (2x + 3)² = 4x² + 12x + 9.',
        '2. Adım: Kesilen bir küçük karenin alanı = 2 × 2 = 4 cm².',
        '3. Adım: 4 adet küçük kare kesildiği için atılan toplam alan = 4 × 4 = 16 cm².',
        '4. Adım: Kalan Alan = (4x² + 12x + 9) - 16 = 4x² + 12x - 7 cm².',
      ],
      keyTakeaway: 'Alan çıkarma sorularında önce tüm alanı, sonra çıkan parçaların toplam alanını hesaplayıp birbirinden çıkarın.',
    },
  },
  {
    topicId: 'mat-dogrusal-egim',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Doğrusal Denklemler ve Eğim',
    lgsFrequency: 'Her yıl 2-3 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Koordinat Sistemi: 1. Bölge (+, +), 2. Bölge (-, +), 3. Bölge (-, -), 4. Bölge (+, -). Eksenler üzerindeki noktalar hiçbir bölgeye ait değildir! (x ekseninde y=0, y ekseninde x=0).',
      'Doğru Grafiği Çizme: x=0 verip y eksenini kestiği noktayı bul; y=0 verip x eksenini kestiği noktayı bul.',
      'Eğim (m): Dikey Uzunluk / Yatay Uzunluk (m = Δy / Δx).',
      'Eğim İşareti: Sağa yatık doğruların eğimi POZİTİF (+), sola yatık doğruların eğimi NEGATİF (-)\'tir.',
      'Denklemden Eğim Bulma: y = mx + n formunda y yalnız bırakıldığında x\'in önündeki katsayı (m) doğrudan eğimdir!',
      'Yatay doğru (y = c) eğimi 0\'dır; Dikey doğru (x = c) eğimi TANIMSIZDIR.',
    ],
    formulas: [
      'Eğim m = Dikey Uzunluk / Yatay Uzunluk',
      'y = mx + n denkleminde eğim = m',
      'ax + by + c = 0 için eğim = -a / b',
      'Orijinden geçen doğrular: y = mx',
    ],
    mebTraps: [
      'MEB Tuzak 1: 2x + 3y - 6 = 0 denkleminde eğimi x\'in katsayısı olan 2 sanmak! Önce y yalnız bırakılır: 3y = -2x + 6 => y = (-2/3)x + 2. Eğim = -2/3\'tür.',
      'MEB Tuzak 2: Sola yatık doğrularda eksi (-) işaretini unutmak! Üçgen uzunlukları pozitif olsa bile doğru sola yatıksa eğim kesinlikle negatiftir.',
      'MEB Tuzak 3: Merdiven ve rampa eğimlerinde hipotenüsü yatay uzunluk ile karıştırmak.',
    ],
    questionStrategy:
      'Soru grafik veriyorsa önce doğrunun sağa mı sola mı yatık olduğuna bakarak işaretini (+/-) belirle. Ardından dik kenarları oranla. Denklem veriyorsa y\'yi yalnız bırak.',
    relatedExamSlug: 'lgs-mat-unite-6-dogrusal-denklemler',
    exampleQuestion: {
      questionText: '3x - 4y + 12 = 0 doğrusunun eğimi kaçtır ve bu doğrunun eksenlerle oluşturduğu üçgenin alanı kaç birimkaredir?',
      solutionSteps: [
        '1. Adım: Eğim için y\'yi yalnız bırak: 4y = 3x + 12 => y = (3/4)x + 3. Eğim = 3/4.',
        '2. Adım: Eksenleri kestiği yerler: x = 0 için y = 3; y = 0 için 3x = -12 => x = -4.',
        '3. Adım: Üçgenin dik kenarları 3 birim ve 4 birimdir (uzunluk negatif olamaz).',
        '4. Adım: Alan = (3 × 4) / 2 = 6 birimkaredir.',
      ],
      keyTakeaway: 'Eksenlerle oluşan üçgen alanlarında koordinatların mutlak değerini (pozitif uzunluğunu) dik kenar olarak alın!',
    },
  },
  {
    topicId: 'mat-esitsizlikler',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Eşitsizlikler',
    lgsFrequency: 'Her yıl 1-2 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Semboller: < (küçüktür), ≤ (küçük veya eşittir), > (büyüktür), ≥ (büyük veya eşittir).',
      'Sayı Doğrusu Gösterimi: Dahil olan sınırlarda (≤, ≥) noktanın içi DOLU; dahil olmayan sınırlarda (<, >) içi BOŞ çizilir.',
      'ALTIN KURAL: Bir eşitsizliğin her iki tarafı NEGATİF bir sayı ile çarpılır veya bölünürse EŞİTSİZLİK YÖN DEĞİŞTİRİR! (< iken > olur, ≤ iken ≥ olur).',
      'Pozitif bir sayı ile çarpma veya bölmede eşitsizlik yön değiştirmez.',
      'Eşitsizliğin her iki tarafına aynı sayı eklenir veya çıkarılırsa yön değişmez.',
    ],
    formulas: [
      'a < b ise -a > -b (Negatif ile çarpınca yön değişir!)',
      'x ≥ k -> [k, ∞) (k noktası dolu)',
      'x < k -> (-∞, k) (k noktası boş)',
    ],
    mebTraps: [
      'MEB Tuzak 1: Eşitsizliği çözerken -2x ≤ 8 durumunda her iki tarafı -2\'ye böldükten sonra x ≤ -4 yazmak! Doğrusu x ≥ -4 olmalıdır (yön değişir).',
      'MEB Tuzak 2: Problem metninde "en fazla 120 TL" denildiğinde x < 120 yazmak; "en fazla" dendiği için 120 dahildir (x ≤ 120). "En az" dendiğinde de x ≥ k yazılmalıdır.',
    ],
    questionStrategy:
      'Önce problem metnindeki "en az", "en çok", "en fazla", "aşan", "altında" kelimelerini doğru sembolle (<, ≤, >, ≥) eşleştir. Bilinmeyeni tek tarafta topla, eksi ile bölerken oku ters çevirmeyi unutma.',
    relatedExamSlug: 'lgs-mat-unite-7-esitsizlikler',
    exampleQuestion: {
      questionText: 'Bir otoparkın ücret tarifesi: Giriş 25 TL ve her saat için 15 TL\'dir. Cebinde 130 TL bulunan bir sürücü bu otoparkta en fazla kaç tam saat kalabilir?',
      solutionSteps: [
        '1. Adım: Kalan saat sayısına x diyelim. Toplam ücret = 25 + 15x.',
        '2. Adım: Cebindeki para 130 TL olduğuna göre ücret 130 TL\'yi geçemez: 25 + 15x ≤ 130.',
        '3. Adım: 25\'i karşıya at: 15x ≤ 105.',
        '4. Adım: Her iki tarafı 15\'e böl: x ≤ 7.',
        '5. Adım: En fazla 7 tam saat kalabilir.',
      ],
      keyTakeaway: '"En fazla" ibaresi ≤ (küçük eşittir) demektir ve sınır değerin kendisi çözüme dahildir.',
    },
  },
  {
    topicId: 'mat-ucgenler',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Üçgenler (Açı-Kenar Bağıntıları, Benzerlik)',
    lgsFrequency: 'Her yıl 2-3 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Üçgen Eşitsizliği: Bir üçgende herhangi bir kenar, diğer iki kenarın farkının mutlak değerinden büyük, toplamından küçüktür: |b - c| < a < b + c.',
      'Açı-Kenar İlişkisi: Büyük açı karşısında büyük kenar, küçük açı karşısında küçük kenar bulunur. (m(A) > m(B) => a > b).',
      'Yardımcı Elemanlar: Yükseklik (h), Açıortay (n), Kenarortay (V). Çeşitkenar üçgende aynı köşeden çizilenler arasında: Yükseklik < Açıortay < Kenarortay (h < n < V).',
      'Pisagor Bağıntısı: Dik üçgende hipotenüsün karesi dik kenarların kareleri toplamına eşittir: a² + b² = c².',
      'Özel Dik Üçgenler: 3-4-5 (katları: 6-8-10, 9-12-15, 12-16-20), 5-12-13, 8-15-17, 7-24-25.',
    ],
    formulas: [
      '|b - c| < a < b + c (Üçgen Eşitsizliği)',
      'a² + b² = c² (Pisagor Bağıntısı)',
      'h_a ≤ n_A ≤ V_a (Yardımcı eleman sıralaması)',
    ],
    mebTraps: [
      'MEB Tuzak 1: İki üçgenin birleşimi olan sorularda en uzun kenarı ararken sadece tek üçgendeki en büyük açıya aldanmak! Bir üçgendeki 80°\'nin karşısındaki kenar, yanındaki üçgende 30°\'nin karşısına denk gelebilir.',
      'MEB Tuzak 2: Geniş açılı üçgende geniş açının karşısındaki kenar Pisagor\'dan büyüktür (a² > b² + c²); dar açılı üçgende küçüktür.',
    ],
    questionStrategy:
      'Önce üçgenlerin tüm iç açılarını tamamla (toplam 180°). Ortak kenar varsa oklar çizerek küçükten büyüğe doğru kenar sıralamasını takip et. Dik üçgen gördüğün an özel üçgen katlarını ara.',
    relatedExamSlug: 'lgs-mat-unite-8-ucgenler',
    exampleQuestion: {
      questionText: 'Kenar uzunlukları tam sayı olan bir üçgenin iki kenarı 7 cm ve 11 cm\'dir. Bu üçgenin çevresi en az ve en çok kaç cm olabilir?',
      solutionSteps: [
        '1. Adım: Bilinmeyen üçüncü kenara x diyelim. Üçgen eşitsizliği kur: |11 - 7| < x < 11 + 7 => 4 < x < 18.',
        '2. Adım: x tam sayı olarak en az 5 cm, en çok 17 cm olabilir.',
        '3. Adım: En az çevre = 7 + 11 + 5 = 23 cm.',
        '4. Adım: En çok çevre = 7 + 11 + 17 = 35 cm.',
      ],
      keyTakeaway: 'Üçgen eşitsizliğinde sınır değerler (4 ve 18) alınamaz; tam sayı dendiği için 5 ve 17 sınırları kullanılır.',
    },
  },
  {
    topicId: 'mat-eslik-benzerlik',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Eşlik ve Benzerlik',
    lgsFrequency: 'Her yıl 1-2 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Eşlik (≅): Karşılıklı açıları eşit ve karşılıklı kenar uzunlukları BİREBİR AYNI olan çokgenlerdir. Eş şekillerin benzerlik oranı k = 1\'dir.',
      'Benzerlik (~): Karşılıklı açıları eşit, karşılıklı kenar uzunlukları ise ORANTILI olan çokgenlerdir.',
      'Benzerlik Oranı (k): Karşılıklı kenarların birbirine bölünmesiyle bulunur.',
      'Çevreler Oranı: Benzer iki çokgenin çevreleri oranı benzerlik oranına eşittir (Ç1 / Ç2 = k).',
      'Alanlar Oranı: Benzer iki çokgenin alanları oranı BENZERLİK ORANININ KARESİNE eşittir (A1 / A2 = k²)!',
    ],
    formulas: [
      'Benzerlik Oranı = k',
      'Çevreler Oranı = k',
      'Alanlar Oranı = k²',
    ],
    mebTraps: [
      'MEB Tuzak 1: İki benzer üçgenin kenar oranı 1/3 iken alanlar oranını da 1/3 almak! Kenar oranı 1/3 ise alanlar oranı (1/3)² = 1/9\'dur.',
      'MEB Tuzak 2: Açı eşleştirmelerini yanlış yapmak! A açısı D açısına eşitse, A\'nın karşısındaki kenar D\'nin karşısındaki kenarla oranlanmalıdır.',
    ],
    questionStrategy:
      'Şekildeki ortak ve paralel açıları harflendir (a, b, 90° gibi). Aynı açıların karşısındaki kenarları birbirine oranlayarak benzerlik denklemini kur.',
    relatedExamSlug: 'lgs-mat-unite-9-benzerlik',
    exampleQuestion: {
      questionText: 'Benzerlik oranı 2/5 olan iki benzer dikdörtgenden küçük olanının alanı 40 cm² olduğuna göre büyük olanının alanı kaç cm²\'dir?',
      solutionSteps: [
        '1. Adım: Benzerlik oranı k = 2/5\'tir.',
        '2. Adım: Alanlar oranı = k² = (2/5)² = 4/25\'tir.',
        '3. Adım: Orantı kuralım: 4 / 25 = 40 / A_büyük.',
        '4. Adım: Pay 10 katına çıktığı için payda da 10 katına çıkar: A_büyük = 25 × 10 = 250 cm².',
      ],
      keyTakeaway: 'Benzerlikte alan hesabı yaparken önce benzerlik oranının karesini (k²) almayı asla unutmayın!',
    },
  },
  {
    topicId: 'mat-donusum-geometrisi',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Dönüşüm Geometrisi',
    lgsFrequency: 'Her yıl kesin 1 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Öteleme: Bir şeklin doğrultusu ve yönü değişmeden belirli bir yönde kaydırılmasıdır. Şeklin boyutu, alanı ve duruş açısı ASLA DEĞİŞMEZ.',
      'Koordinatta Öteleme: Sağa a birim -> (x + a, y); Sola a birim -> (x - a, y); Yukarı b birim -> (x, y + b); Aşağı b birim -> (x, y - b).',
      'Yansıma (Simetri): Bir şeklin doğruya göre ayna görüntüsüdür. Şeklin boyutu ve biçimi değişmez ancak sağ-sol yönü TERS DÖNER.',
      'x Eksenine Göre Yansıma: x koordinatı aynı kalır, y işaret değiştirir: (x, y) -> (x, -y).',
      'y Eksenine Göre Yansıma: y koordinatı aynı kalır, x işaret değiştirir: (x, y) -> (-x, y).',
      'Orijine Göre Yansıma: Her iki koordinat da işaret değiştirir: (x, y) -> (-x, -y).',
    ],
    formulas: [
      'x eksenine göre yansıma: (x, y) -> (x, -y)',
      'y eksenine göre yansıma: (x, y) -> (-x, y)',
      'Orijine göre yansıma: (x, y) -> (-x, -y)',
      'Ötelemede şekil eş kalır (Alan ve çevre korunur).',
    ],
    mebTraps: [
      'MEB Tuzak 1: Yansımada simetri doğrusuna olan dik uzaklığı eşit almamak! Noktanın aynaya olan dik uzaklığı kaç birimse görüntüsü de aynanın diğer tarafında o kadar birim uzakta olmalıdır.',
      'MEB Tuzak 2: Öteleme ile yansıma peş peşe uygulandığında sırayı karıştırmak veya yansımada şeklin yönünün ters döndüğünü unutup öteleme gibi çizmek.',
    ],
    questionStrategy:
      'Şeklin tamamını taşımak yerine köşelerindeki kilit noktaların (A, B, C) koordinatlarını tek tek dönüştür, sonra bu noktaları birleştir.',
    relatedExamSlug: 'lgs-mat-unite-10-donusum',
    exampleQuestion: {
      questionText: 'A(-3, 4) noktası 5 birim sağa ve 6 birim aşağı ötelendikten sonra x eksenine göre yansıtılıyor. Oluşan yeni noktanın koordinatları nedir?',
      solutionSteps: [
        '1. Adım: 5 birim sağa öteleme: x koordinatına 5 ekle -> -3 + 5 = 2.',
        '2. Adım: 6 birim aşağı öteleme: y koordinatından 6 çıkar -> 4 - 6 = -2. Ötelenen nokta: (2, -2).',
        '3. Adım: x eksenine göre yansıma: x aynı kalır, y işaret değiştirir -> (2, -(-2)) = (2, 2).',
        '4. Sonuç: Yeni nokta (2, 2)\'dir.',
      ],
      keyTakeaway: 'Adım adım işlem yapın: önce ötelemeleri uygulayıp ara noktayı yazın, ardından yansıma kuralını uygulayın.',
    },
  },
  {
    topicId: 'mat-geometrik-cisimler',
    courseKey: 'matematik',
    courseName: 'Matematik',
    topicName: 'Geometrik Cisimler (Prizma, Silindir, Koni)',
    lgsFrequency: 'Her yıl 1-2 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Dik Dairesel Silindir Açınımı: İki eş daire (tabanlar) ve bir dikdörtgenden (yanal yüzey) oluşur.',
      'Silindir Dikdörtgen Kenarı: Yanal yüzeyi oluşturan dikdörtgenin bir kenarı silindirin yüksekliği (h), diğer kenarı ise TABAN DAİRESİNİN ÇEVRESİDİR (2πr)!',
      'Silindir Hacmi: Taban Alanı × Yükseklik = πr²h.',
      'Silindir Yanal Alanı: 2πr × h. Toplam Alan = 2πrh + 2πr².',
      'Dik Koni: Tabanı daire, yanal yüzeyi daire dilimidir. Tepe noktası ile taban merkezini birleştiren doğru yüksekliktir (h).',
      'Konide Pisagor Bağıntısı: a² = h² + r² (a: ana doğru, h: yükseklik, r: taban yarıçapı).',
      'Koni Açınım Açısı Formülü: r / a = α / 360° (r: yarıçap, a: ana doğru, α: daire dilimi merkez açısı).',
    ],
    formulas: [
      'Silindir Yanal Alanı = 2πr · h',
      'Silindir Hacmi = πr² · h',
      'Koni Pisagor: a² = h² + r²',
      'Koni Merkez Açısı: r / a = α / 360°',
    ],
    mebTraps: [
      'MEB Tuzak 1: Silindirin yanal yüzeyini açtığında oluşan dikdörtgenin uzun kenarını yarıçapla karıştırmak; o kenar kesinlikle 2πr\'dir.',
      'MEB Tuzak 2: Koni açınımında r/a = α/360° formülünde "a" yerine yüksekliği (h) yazmak! Formüldeki "a" ana doğrudur (eğik kenar), yükseklik değildir.',
    ],
    questionStrategy:
      'Cismin kapalı halinden açık haline veya açık halinden kapalı haline geçişlerde kenar eşleşmelerine dikkat et: Dairenin çevresi = Dikdörtgenin kenarı.',
    relatedExamSlug: 'lgs-mat-unite-11-geometrik-cisimler',
    exampleQuestion: {
      questionText: 'Taban yarıçapı 3 cm, ana doğrusu 9 cm olan bir dik koninin yanal yüzey açınımındaki daire diliminin merkez açısı kaç derecedir?',
      solutionSteps: [
        '1. Adım: r / a = α / 360° formülünü uygula.',
        '2. Adım: r = 3 cm, a = 9 cm.',
        '3. Adım: 3 / 9 = α / 360° => 1 / 3 = α / 360°.',
        '4. Adım: İçler-dışlar çarpımı yap: 3α = 360° => α = 120°.',
      ],
      keyTakeaway: 'r/a oranı kaçsa daire diliminin açısı da 360°\'nin o kadarıdır (1/3 ise 360/3 = 120°).',
    },
  },
];
