import type { TopicStudyNote } from '@/types/study';

export const TURKCE_NOTES: TopicStudyNote[] = [
  {
    topicId: 'turkce-fiilimsiler',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Fiilimsiler (Eylemsiler)',
    lgsFrequency: 'Her yıl kesin 1 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Fiilimsiler fiil kök veya gövdelerine gelir, fiil anlamını korur ama cümlede isim, sıfat veya zarf görevinde kullanılır.',
      'İsim-fiil Kodlaması (M-A-Y-I-Ş-M-A-K): -ma / -me, -ış / -iş / -uş / -üş, -mak / -mek.',
      'Sıfat-fiil Kodlaması (ANASI MEZAR DİKECEKMİŞ): -an / -en, -ası / -esi, -maz / -mez, -ar / -er, -dık / -dik, -ecek / -acak, -miş / -mış.',
      'Zarf-fiil Kodlaması (KENYALI ASİYE İPİ ARAKLADIKÇA...): -ken, -alı, -asıya, -e...-e, -ip, -arak, -dıkça, -ince, -meksizin, -r...-mez.',
      'Fiilimsiler kip ve kişi eki alamazlar, yani çekimli fiil değillerdir.',
      'Cümlede fiilimsinin bulunduğu yan cümleler oluştururlar.',
    ],
    mebTraps: [
      'MEB Tuzak 1: Kalıcı İsim Tuzağı! "Dolma, dondurma, ekmek, çakmak, giriş, çıkış, danışma, kavurma" gibi sözcükler artık bir varlığın adı olmuşsa fiilimsi DEĞİLDİR.',
      'MEB Tuzak 2: Sıfat-fiil ekleri (-ecek, -miş, -ar, -mez) ile geçmiş ve gelecek zaman kip eklerini karıştırmak! Yüklemdeyse KİP ekidir, ismin önüne gelip niteleme yapıyorsa SIFAT-FİİL ekidir (Örn: "Koşar adımlarla gitti" -> Sıfat-fiil; "Her sabah koşar" -> Kip eki).',
      'MEB Tuzak 3: Olumsuzluk eki olan -ma/-me ile isim-fiil eki olan -ma/-me\'yi karıştırmak.',
    ],
    questionStrategy:
      'Cümledeki yüklemi (çekimli fiili) hemen bul ve paranteze al. Kalan sözcüklerde fiil kökü olup yapım eki almış olanları incele. İsmi niteliyorsa sıfat-fiil, cümleye "Nasıl?" veya "Ne zaman?" sorusunu sorduruyorsa zarf-fiildir.',
    relatedExamSlug: 'lgs-turkce-unite-1-fiilimsiler',
    exampleQuestion: {
      questionText: '"Gelecek yıl yapılacak sınavda başarılı olmak için durmaksızın çalışmalıyız." cümlesindeki fiilimsilerin türleri sırasıyla hangileridir?',
      solutionSteps: [
        '1. Adım: "gelecek (yıl)" -> İsmi niteleyen sıfat-fiil (-ecek).',
        '2. Adım: "yapılacak (sınav)" -> İsmi niteleyen sıfat-fiil (-acak).',
        '3. Adım: "olmak" -> -mak eki almış isim-fiil.',
        '4. Adım: "durmaksızın" -> Durumu bildiren zarf-fiil (-meksizin).',
      ],
      keyTakeaway: '"Çalışmalıyız" sözcüğü yüklemdir (-malı gereklilik kipi, -yız kişi eki almıştır), onu fiilimsi sanıp saymayın!',
    },
  },
  {
    topicId: 'turkce-sozcukte-anlam',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Sözcükte Anlam',
    lgsFrequency: 'Her yıl 2-3 soru',
    difficultyLevel: 'Temel',
    summaryBullets: [
      'Gerçek (Temel) Anlam: Sözcüğün akla gelen ilk, sözlükteki asıl anlamıdır (Örn: "Ağır bir çuval taşıdı").',
      'Mecaz Anlam: Sözcüğün gerçek anlamından tamamen uzaklaşarak kazandığı soyut, yeni anlamdır (Örn: "Ağır sözlerle kalbimi kırdı").',
      'Terim Anlam: Bilim, sanat, spor veya meslek dalına özgü özel kavramları karşılayan sözcüklerdir (Örn: Açı, nota, penaltı, hücre).',
      'Eş Anlamlı (Anlamdaş) - Zıt (Karşıt) Anlamlı Sözcükler: Birbirinin tam karşıtı olan durumlar (Bir sözcüğün olumsuzu onun zıttı DEĞİLDİR; "gelmek" zıttı "gitmek"tir, "gelmemek" değildir).',
      'Deyimler ve Atasözleri: Kalıplaşmış sözlerdir; sözcüklerin yeri değiştirilemez, yerine eş anlamlısı getirilemez.',
      'Sözcük Öbeklerinde Anlam: Altı çizili sözün cümleye kattığı anlamı bulurken tüm cümleyi ve bağlamı okumak şarttır.',
    ],
    mebTraps: [
      'MEB Tuzak 1: Bir sözcüğün olumsuzunu onun zıt anlamlısı sanmak! (Gülmek zıttı ağlamaktır, gülmemek zıt anlam değildir).',
      'MEB Tuzak 2: Altı çizili sözün sadece kendi anlamına odaklanıp cümlenin genelinde kazandığı mecazi anlamı gözden kaçırmak.',
    ],
    questionStrategy:
      'Altı çizili ifadenin bulunduğu cümleyi baştan sona oku. Cümlenin yerine şıklardaki anlamı koyduğunda cümlenin akışı bozulmuyorsa doğru şıktasın.',
    relatedExamSlug: 'lgs-turkce-unite-2-sozcukte-anlam',
    exampleQuestion: {
      questionText: '"Yazar, bu eserinde toplumun kanayan yaralarına parmak basmış." cümlesindeki altı çizili ifadenin kattığı anlam nedir?',
      solutionSteps: [
        '1. Adım: "Parmak basmak" bir deyimdir.',
        '2. Adım: Mecaz anlam içerir: Gerçekten parmakla dokunmak değil, önemli bir soruna dikkat çekmek, o sorunu vurgulamaktır.',
        '3. Sonuç: Bir konuya odaklanıp dikkat çekmek anlamına gelir.',
      ],
      keyTakeaway: 'Deyimler genellikle mecaz anlam taşır, günlük dildeki karşılığını soyut düşünerek bulun.',
    },
  },
  {
    topicId: 'turkce-cumlede-anlam',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Cümlede Anlam',
    lgsFrequency: 'Her yıl 2-3 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Öznel Anlatım: Kişiden kişiye değişen, kanıtlanamayan, beğeni veya duygu içeren yargılardır (Örn: "Mavi en güzel renktir").',
      'Nesnel Anlatım: Kişisel görüş içermeyen, herkesçe kabul edilen, bilimsel olarak kanıtlanabilen yargılardır (Örn: "Türkiye\'nin başkenti Ankara\'dır").',
      'Neden-Sonuç (Sebep-Sonuç): Eylemin hangi gerekçeyle yapıldığını bildirir. Yargıların ikisi de gerçekleşmiştir (-dığı için, -den dolayı: "Kar yağdığı için yollar kapandı").',
      'Amaç-Sonuç: Eylemin hangi hedefe ulaşmak için yapıldığını bildirir (-mek amacıyla, -mek için: "Sınavı kazanmak için çok çalıştı").',
      'Koşul-Sonuç (Şart): Bir olayın gerçekleşmesinin başka bir olaya bağlı olmasıdır (-se/-sa, -dıkça: "Ödevini bitirirsen dışarı çıkabilirsin").',
      'Örtülü Anlam: Cümlede açıkça söylenmediği halde "de/da", "en", "daha", "yine" gibi sözcüklerle ulaşılan gizli anlamlardır (Örn: "Ahmet de maça geldi" -> Başkaları da gelmiş).',
    ],
    mebTraps: [
      'MEB Tuzak 1: Neden-Sonuç ile Amaç-Sonuç cümlelerini karıştırmak! Cümleye "hangi amaçla?" sorusu sorulabiliyorsa AMAÇ-SONUÇ; "hangi gerekçeyle/nedenle?" sorusu soruluyorsa NEDEN-SONUÇTUR.',
      'MEB Tuzak 2: Öznel cümlelerde "bence/bana göre" kelimesi aranması yanılgısı; gizli öznellik içeren estetik sıfatlar (harika, büyüleyici, sıkıcı) cümleyi doğrudan öznel yapar.',
    ],
    questionStrategy:
      'Cümledeki eylemin yanına "amacıyla" kelimesini koy: Uyumlu oluyorsa Amaç-Sonuç, "nedeniyle" kelimesi uyumlu oluyorsa Neden-Sonuçtur.',
    relatedExamSlug: 'lgs-turkce-unite-3-cumlede-anlam',
    exampleQuestion: {
      questionText: '"Yazar, gençlere rehberlik etmek üzere bu kitabı kaleme almış." cümlesinin anlam ilişkisi nedir?',
      solutionSteps: [
        '1. Adım: Cümleyi test edelim: "gençlere rehberlik etmek amacıyla bu kitabı kaleme almış."',
        '2. Adım: "amacıyla" ifadesi tam oturduğu için bir hedef bildirmektedir.',
        '3. Sonuç: Bu cümle bir AMAÇ-SONUÇ cümlesidir.',
      ],
      keyTakeaway: '"-mek üzere" kalıbı genellikle amaç-sonuç bildirir, neden-sonuç ile karıştırmayın.',
    },
  },
  {
    topicId: 'turkce-paragraf',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Paragrafta Anlam (Ana Fikir, Yardımcı Fikir)',
    lgsFrequency: 'Her yıl 8-10 soru (Sınavın omurgası)',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Ana Düşünce (Ana Fikir): Yazarın okuyucuya vermek istediği asıl mesaj, metnin yazılış gayesidir. Genellikle metnin son cümlelerinde özetlenir ("aslında, kısacası, oysa, önemli olan").',
      'Konu: Metinde neyden bahsedildiğidir (1-2 sözcükle özetlenir).',
      'Yardımcı Düşünceler: Ana düşünceyi destekleyen, detaylandıran yan fikirlerdir ("Değinilmemiştir, ulaşılamaz, çıkarılamaz" soruları).',
      'Paragrafta Yapı: Giriş, Gelişme, Sonuç. Giriş cümlesinde önceki cümleye gönderme yapan bağlaçlar ("bu yüzden, çünkü, nitekim, oysa, bu durum") ASLA BULUNMAZ.',
      'Anlatım Biçimleri: Açıklama (Bilgi verme), Tartışma (Kendi fikrini savunma, karşı fikri çürütme), Öyküleme (Olay, kişi, zaman, yer), Betimleme (Sözcüklerle resim çizme, niteleme sıfatları).',
    ],
    mebTraps: [
      'MEB Tuzak 1: Kendi genel kültürünü metne katmak! Metinde geçmeyen ama gerçek hayatta doğru olan bilgiyi doğru kabul etmeyin; sadece metne bağlı kalın.',
      'MEB Tuzak 2: Kesinlik bildiren sözcükler ("sadece, daima, tümüyle, hiçbir zaman"): Metinde açıkça yoksa bu şıklar genellikle yanlıştır.',
    ],
    questionStrategy:
      'Önce mutlaka soru kökünü oku ("çıkarılamaz", "hangisine değinilmemiştir"). Ardından şıklara 5 saniye göz gezdirip anahtar kelimeleri aklında tutarak metni oku.',
    relatedExamSlug: 'lgs-turkce-unite-4-paragraf-mantik',
    exampleQuestion: {
      questionText: 'Paragraf sorularında "Bu metnin ana düşüncesi aşağıdakilerden hangisidir?" dendiğinde metnin neresine odaklanmalıyız?',
      solutionSteps: [
        '1. Adım: Metnin ilk 1-2 cümlesi konuyu tanıtır, acele edip ilk cümleyi ana fikir sanmayın.',
        '2. Adım: Yazar örnekler verir, karşılaştırma yapar ("örneğin, nitekim, oysa").',
        '3. Adım: Sonuç bildiren ifadelere ("kısacası, asıl mesele, bundan ötürü") bakın. Yazarın vermek istediği ders buradadır.',
      ],
      keyTakeaway: 'Ana fikir daima kapsamlı bir öğüt veya evrensel bir ders cümlesidir, dar bir örnek ana fikir olamaz!',
    },
  },
  {
    topicId: 'turkce-cumlenin-ogeleri',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Cümlenin Ögeleri',
    lgsFrequency: 'Her yıl kesin 1 soru',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Öge Bulma Sırası (YÖNTEM): 1. Yüklem -> 2. Özne -> 3. Nesne -> 4. Tümleçler (Yer Tamlayıcısı ve Zarf Tamlayıcısı).',
      'Yüklem: Cümlenin temel direğidir, çekimli fiil veya ek fiil almış isimdir.',
      'Özne: Yükleme sorulan "Kim?" veya "Ne?" sorusuna yanıt verir. Gerçek özne, gizli özne ve sözde özne (edilgen fiillerde).',
      'Nesne: Belirtili Nesne ("Neyi, Kimi?"), Belirtisiz Nesne (Özneyi bulduktan sonra yükleme sorulan "Ne?").',
      'Yer Tamlayıcısı (Dolaylı Tümleç): -e, -de, -den hal eklerini alır ("Nereye, Nerede, Nereden, Kime, Kimde, Kimden?").',
      'Zarf Tamlayıcısı: Yüklemi durum, zaman, miktar, sebep yönünden tamamlar ("Nasıl, Ne zaman, Ne kadar, Neden?").',
      'ALTIN KURAL: İsim tamlamaları, sıfat tamlamaları, deyimler, birleşik fiiller ve fiilimsi grupları ASLA BÖLÜNMEZ, tek bir öge kabul edilir!',
    ],
    mebTraps: [
      'MEB Tuzak 1: Belirtisiz nesne ile özneyi karıştırmak! Yükleme sorulan ilk "Ne?" sorusu ÖZNEYİ verir. Özneyi bulduktan sonra sorulan ikinci "Ne?" sorusu Belirtisiz Nesneyi verir.',
      'MEB Tuzak 2: Deyimleri veya tamlamaları bölmek! "Gözden düşmek" yüklemdir, "gözden" yer tamlayıcısı yapılamaz.',
      'MEB Tuzak 3: "Aşağı, yukarı, içeri, dışarı, ileri, geri" sözcükleri yalınsa ZARF TÜMLECİ, ek alırsa (-ya, -da, -dan: aşağıya, içeride) YER TAMLAYICISI olur!',
    ],
    questionStrategy:
      'Önce yüklemi bul. Yüklem tamlama veya deyim mi diye kontrol et. Yükleme "Yapan kim/ne?" sorusunu sorup özneyi sabitle, ardından nesne ve tümleçleri bul.',
    relatedExamSlug: 'lgs-turkce-unite-5-cumlenin-ogeleri',
    exampleQuestion: {
      questionText: '"Yaşlı adam, elindeki bastonla bahçe kapısını yavaşça araladı." cümlesinin öge dizilişi sırasıyla nasıldır?',
      solutionSteps: [
        '1. Adım: Yüklem: "araladı".',
        '2. Adım: Aralayan kim? -> "Yaşlı adam" (Özne).',
        '3. Adım: Neyi araladı? -> "bahçe kapısını" (Belirtili Nesne).',
        '4. Adım: Neyle araladı? -> "elindeki bastonla" (Zarf Tamlayıcısı).',
        '5. Adım: Nasıl araladı? -> "yavaşça" (Zarf Tamlayıcısı).',
        '6. Diziliş: Özne - Zarf Tamlayıcısı - Belirtili Nesne - Zarf Tamlayıcısı - Yüklem.',
      ],
      keyTakeaway: 'Araç bildiren edat grupları (-le/-la) ve durum bildiren sözcükler cümlede zarf tamlayıcısı görevindedir.',
    },
  },
  {
    topicId: 'turkce-fiilde-cati',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Fiilde Çatı',
    lgsFrequency: 'Her yıl 1 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'ÖZNELERİNE GÖRE FİİLLER:',
      '1. Etken Çatı: İşi yapan özne bellidir (gerçek veya gizli özne vardır). Çatı eki almaz (Örn: "Ali camı kırdı", "Kitap okudum").',
      '2. Edilgen Çatı: İşi yapan özne belli değildir. Fiil "-l" veya "-n" eki alır. Cümlede "Sözde Özne" bulunur (Örn: "Cam kırıldı", "Sınıf temizlendi").',
      'NESNELERİNE GÖRE FİİLLER:',
      '1. Geçişli Fiil: Nesne alabilen fiillerdir. Fiilin başına "ONU" sözcüğü getirildiğinde anlamlı olur (Örn: "(Onu) okudu", "(Onu) bekledi"). Cümlede nesne yazılmasa bile fiil geçişli olabilir!',
      '2. Geçişsiz Fiil: Nesne alamayan fiillerdir. Fiilin başına "ONU" sözcüğü getirilemez (Örn: "(Onu) güldü" OLMAZ, "(Onu) uyudu" OLMAZ).',
      'ALTIN KURAL: Yüklemi İSİM olan cümlelerde ÇATI ÖZELLİĞİ KESİNLİKLE ARANMAZ!',
    ],
    mebTraps: [
      'MEB Tuzak 1: İsim cümlelerinde çatı aramak! Yüklem isimse (Örn: "Hava bugün çok güzeldi") şıklarda çatı özelliği aranmaz.',
      'MEB Tuzak 2: Cümlede açıkça nesne yazılmadı diye fiili geçişsiz sanmak! (Örn: "Dün akşam saatlerce okudu" cümlesinde nesne yoktur ama fiilin başına "onu" geldiği için fiil GEÇİŞLİDİR).',
      'MEB Tuzak 3: "-l, -n" ekini alıp öznesi gerçek olan dönüşlü fiillerle edilgeni karıştırmak (Örn: "Ahmet yıkandı" -> Kendi yıkandı, etkendir).',
    ],
    questionStrategy:
      'Önce yüklemin fiil olduğundan emin ol. Fiilin başına pratik olarak "ONU" koy: Anlamlıysa GEÇİŞLİ, anlamsızsa GEÇİŞSİZDİR. Sonra işi yapan belli mi diye bak: Belliyse ETKEN, başkası tarafından yapılmışsa EDİLGEN.',
    relatedExamSlug: 'lgs-turkce-unite-6-fiilde-cati',
    exampleQuestion: {
      questionText: '"Okul bahçesindeki çöpler görevliler tarafından toplandı." cümlesinin çatı özellikleri nedir?',
      solutionSteps: [
        '1. Adım: Yüklem "toplandı" (toplamak fiili -n edilgenlik eki almıştır).',
        '2. Adım: Çöpler kendi kendine toplanmaz, işi yapan gizlidir ("tarafından" örtülü öznedir, gerçek özne sayılmaz) -> EDİLGEN.',
        '3. Adım: Başına "onu" koy: "Onu toplandı" denemez -> GEÇİŞSİZ.',
        '4. Sonuç: Edilgen - Geçişsiz fiildir.',
      ],
      keyTakeaway: '"Tarafından" veya "-ce/-ca" ifadesi bulunsa bile fiil -l/-n eki almışsa çatı daima EDİLGENDİR.',
    },
  },
  {
    topicId: 'turkce-cumle-turleri',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Cümle Türleri',
    lgsFrequency: 'Her yıl 1 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'YÜKLEMİN TÜRÜNE GÖRE: İsim Cümlesi (Yüklem ek fiil almış isim/isim soylu), Fiil Cümlesi (Yüklem çekimli fiil).',
      'YÜKLEMİN YERİNE GÖRE: Kurallı Cümle (Yüklem sonda), Devrik Cümle (Yüklem başta veya ortada), Eksiltili Cümle (Yüklemi olmayan, sonuna "..." konan).',
      'ANLAMINA GÖRE: Olumlu Cümle (Eylem gerçekleşmiş/gerçekleşecek), Olumsuz Cümle (-ma, -me, -sız, yok, değil ekleri ile eylem gerçekleşmemiş), Soru Cümlesi.',
      'YAPISINA GÖRE CÜMLELER:',
      '1. Tek Yüklemli (Basit) Cümle: Tek yüklem vardır ve içinde HİÇ FİİLİMSİ YOKTUR.',
      '2. Fiilimsisi Olan (Birleşik) Cümle: Tek yüklem vardır ve içinde EN AZ BİR FİİLİMSİ (Yan Cümlecik) bulunur.',
      '3. Birden Çok Yüklemli (Sıralı) Cümle: Birden fazla yüklem VİRGÜL (,) veya NOKTALI VİRGÜL (;) ile bağlanır.',
      '4. Bağlacı Olan (Bağlı) Cümle: Birden fazla yüklem BAĞLAÇ (ve, ama, fakat, çünkü) ile birbirine bağlanır.',
    ],
    mebTraps: [
      'MEB Tuzak 1: Biçimce olumsuz anlamca olumlu cümleler! (Örn: "Seni sevmiyor değilim" -> Seviyorum, yani anlamca olumludur).',
      'MEB Tuzak 2: Sıralı cümle ile bağlı cümleyi karıştırmak! Cümleleri ayıran işaret virgül ise SIRALI, bağlaç ise BAĞLI cümledir.',
      'MEB Tuzak 3: Bağlaç iki yüklemi değil de sadece iki özneyi bağlıyorsa o cümle bağlı cümle DEĞİLDİR (Örn: "Ahmet ve Mehmet geldi" -> Tek yüklemli basit cümledir).',
    ],
    questionStrategy:
      'Cümlenin kaç yüklemi olduğuna bak: 1 yüklem varsa ya basittir ya fiilimsili birleşiktir. 2 veya daha fazla yüklem varsa virgülle ayrılmışsa sıralı, bağlaçla bağlanmışsa bağlı cümledir.',
    relatedExamSlug: 'lgs-turkce-unite-7-cumle-turleri',
    exampleQuestion: {
      questionText: '"Zil çaldığında bütün öğrenciler bahçeye koştu." cümlesinin yapısına göre türü nedir?',
      solutionSteps: [
        '1. Adım: Cümledeki yüklemi bul: "koştu" (1 tane yüklem var).',
        '2. Adım: Cümlede fiilimsi var mı kontrol et: "çaldığında" (-dığında zarf-fiil eki).',
        '3. Adım: Tek yüklem ve fiilimsi içerdiği için bu cümle FİİLİMSİSİ OLAN (BİRLEŞİK) cümledir.',
      ],
      keyTakeaway: 'Tek yüklemli bir cümlede tek bir fiilimsi bile varsa yapıca birleşik cümle olur.',
    },
  },
  {
    topicId: 'turkce-yazim-kurallari',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Yazım Kuralları',
    lgsFrequency: 'Her yıl kesin 1 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      '"de / da" Bağlacı: Cümleden çıkarıldığında cümlenin anlamı bozulmaz, DAİMA AYRI yazılır. "te / ta" şekli ASLA YOKTUR.',
      '"-de / -da" Hâl Eki: Bulunma bildirir, cümleden çıkarılınca anlam bozulur, BİTİŞİK yazılır. Sertleşerek "-te / -ta" olabilir.',
      '"ki" Bağlacı: Ayrı yazılır (İstisnalar SOMBAHÇEMİ: Sanki, Oysaki, Mademki, Belki, Halbuki, Çünkü, Meğerki, İllaki). Sıfat yapan "-ki" ve ilgi zamiri "-ki" bitişik yazılır.',
      '"mi" Soru Eki: Kendinden önceki sözcükten daima AYRI yazılır, üzerine gelen ekler bitişir (Geldin mi? Okuyor musun?).',
      'Büyük Harflerin Yazımı: Akrabalık bildiren kelimeler küçük (Ayşe teyzem), unvan/lakap olunca büyük (Telli Baba, Nene Hatun). Yön isimleri özel isimden önce gelirse BÜYÜK (Kuzey Afrika), sonra gelirse KÜÇÜK (Afrika\'nın kuzeyi).',
      'Kurum, kuruluş adlarının her kelimesi büyük harfle başlar ve GELEN EKLER KESMEYLE AYRILMAZ (Türkiye Büyük Millet Meclisine).',
    ],
    mebTraps: [
      'MEB Tuzak 1: Kurum, kuruluş ve kurul adlarına gelen çekim eklerini kesmeyle ayırmak! (TDK\'den, Ankara Üniversitesine -> Kesme işareti KESİNLİKLE KULLANILMAZ).',
      'MEB Tuzak 2: "Şey" sözcüğü daima ayrı yazılır: "bir şey, her şey, çok şey".',
      'MEB Tuzak 3: İkilemeler daima ayrı yazılır: "el ele, ardı ardına, art arda (art arda dikkat!)".',
    ],
    questionStrategy:
      '"de" için cümleden çıkararak oku: Anlam bozulmuyorsa bağlaçtır ayrı yazılmalı. "ki" için kelimeye "-ler" eki getir: "seninkiler" anlamlıysa bitişik, "duydumkiler" anlamsızsa ayrı yazılır.',
    relatedExamSlug: 'lgs-turkce-unite-8-yazim-kurallari',
    exampleQuestion: {
      questionText: 'Aşağıdaki altı çizili sözcüklerden hangisinin yazımı doğrudur? A) Türk Dil Kurumu\'na B) herşey C) pek çok D) bir çok',
      solutionSteps: [
        '1. Adım: A şıkkı: Kurum adlarına gelen ekler kesmeyle ayrılmaz -> Türk Dil Kurumuna olmalı (Yanlış).',
        '2. Adım: B şıkkı: "şey" daima ayrı yazılır -> her şey olmalı (Yanlış).',
        '3. Adım: D şıkkı: "birçok" bitişik yazılır (Yanlış).',
        '4. Adım: C şıkkı: "pek çok" daima ayrı yazılır (DOĞRU).',
      ],
      keyTakeaway: '"Pek çok" ayrı, "birçok" bitişik yazılır. Bu ikili MEB\'in en sevdiği yazım tuzağıdır!',
    },
  },
  {
    topicId: 'turkce-noktalama',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Noktalama İşaretleri',
    lgsFrequency: 'Her yıl kesin 1 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'Virgül (,): Eş görevli sözcükleri ayırır, sıralı cümleleri ayırır, hitaplardan sonra konur, uzun cümlelerde özneden sonra konur.',
      'VİRGÜLÜN KESİNLİKLE KONMAYACAĞI YERLER (LGS\'nin 1 Numaralı Kuralı): 1) Şart ekinden (-se/-sa) sonra, 2) Tek başına kullanılan zarf-fiil eklerinden (-ip, -erek, -ince) sonra, 3) Bağlaçlardan (ve, veya, ama, hem...hem, ne...ne) önce veya sonra KESİNLİKLE VİRGÜL KONMAZ!',
      'Noktalı Virgül (;): Cümle içinde virgülle ayrılmış tür veya takımları birbirinden ayırmak için veya ögeleri arasında virgül bulunan sıralı cümleleri ayırmak için konur.',
      'İki Nokta (:): Kendisinden sonra açıklama yapılacak veya örnek verilecek cümlenin sonuna konur. İki noktadan sonra cümle geliyorsa büyük harfle, örnekler sıralanıyorsa küçük harfle başlar.',
      'Üç Nokta (...): Tamamlanmamış (eksiltili) cümlelerin sonuna konur.',
      'Kesme İşareti (\'): Özel isimlere gelen çekim eklerini ayırır. Kurum adlarına gelen ekler AYRILMAZ. Özel isme gelen yapım ekleri (-lı, -siz, -ler, -gil) ve ondan sonra gelen hiçbir ek KESMEYLE AYRILMAZ (Örn: Türklük, Ankaralılar, Ahmetlerin).',
    ],
    mebTraps: [
      'MEB Tuzak 1: Metinde bir tane zarf-fiil varken arkasına virgül koymak! (Örn: "Okula gidip, ders çalıştı" YANLIŞTIR; virgül konamaz).',
      'MEB Tuzak 2: Özel ada yapım eki geldiğinde kesmeyle ayırmak! (Örn: "Türk\'çe" veya "Ahmet\'ler" YANLIŞTIR; "Türkçe" ve "Ahmetler" yazılır).',
    ],
    questionStrategy:
      'Boşluktan hemen önceki ve sonraki kelimeye bak. Bağlaç veya zarf-fiil varsa oraya hiçbir noktalama işareti gelemez. İki noktadan sonra cümlenin büyük harfle mi küçük harfle mi başladığını kontrol et.',
    relatedExamSlug: 'lgs-turkce-unite-9-noktalama',
    exampleQuestion: {
      questionText: '"Pazardan elma, armut, portakal; ıspanak, pırasa, lahana aldım." cümlesinde noktalı virgülün (;) kullanılma gerekçesi nedir?',
      solutionSteps: [
        '1. Adım: Cümlede elma, armut, portakal meyve grubudur.',
        '2. Adım: Ispanak, pırasa, lahana sebze grubudur.',
        '3. Adım: Kendi içinde virgülle ayrılmış farklı tür ve takımları ayırmak için noktalı virgül kullanılmıştır.',
      ],
      keyTakeaway: 'Tür ve takım değiştiğinde araya noktalı virgül (;) girer.',
    },
  },
  {
    topicId: 'turkce-metin-turleri-sanatlar',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Metin Türleri ve Söz Sanatları',
    lgsFrequency: 'Her yıl 1-2 soru',
    difficultyLevel: 'Orta',
    summaryBullets: [
      'SÖZ SANATLARI:',
      '1. Teşbih (Benzetme): Aralarında benzerlik ilgisi kurulan varlıklardan zayıf olanın güçlü olana benzetilmesidir (Kömür gibi kara gözler).',
      '2. Teşhis (Kişileştirme): İnsana ait özelliklerin insan dışı varlıklara (hayvan, bitki, eşya) aktarılmasıdır (Rüzgar hüzünle fısıldıyordu).',
      '3. İntak (Konuşturma): İnsan dışındaki varlıkların konuşturulmasıdır. Her intak sanatı aynı zamanda bir kişileştirmedir!',
      '4. Tezat (Karşıtlık): Birbirine zıt duygu, kavram veya durumların bir arada kullanılmasıdır (Ağlarım hatıra geldikçe gülüştüklerimiz).',
      '5. Mübalağa (Abartma): Bir durumun olduğundan çok daha büyük veya küçük gösterilmesidir (Bir ah çeksem dağı taşı eritir).',
      'METİN TÜRLERİ:',
      'Deneme: Yazarın herhangi bir konuda kanıtlama amacı gütmeden kendisiyle konuşur gibi yazdığı içten yazılardır.',
      'Makale: Bilimsel bir tezi kanıtlamak amacıyla nesnel veriler ve istatistiklerle yazılan ciddi yazılardır.',
      'Biyografi (Yaşam Öyküsü): Başkasının hayatını anlatır. Otobiyografi: Kişinin kendi hayatını anlatmasıdır.',
      'Anı (Hatıra): Geçmişte yaşanmış olayların üzerinden zaman geçtikten sonra yazılmasıdır. Günlük: Günü gününe tarih atılarak yazılır.',
    ],
    mebTraps: [
      'MEB Tuzak 1: Her intak (konuşturma) sanatının aynı zamanda bir kişileştirme (teşhis) olduğunu unutmak!',
      'MEB Tuzak 2: Deneme ile makaleyi karıştırmak: Kanıtlama amacı varsa MAKALE, samimi ve kişisel sohbet havasındaysa DENEMEDİR.',
    ],
    questionStrategy:
      'Paragrafta konuşturulan bir hayvan/çiçek varsa doğrudan İNTAK ve KİŞİLEŞTİRME ara. Sayısal veri ve bilimsel araştırma varsa MAKALE şıkkına git.',
    relatedExamSlug: 'lgs-turkce-unite-10-metin-turleri',
    exampleQuestion: {
      questionText: '"Kurnaz tilki, kargaya yaklaşarak \'Ne kadar da tatlı bir sesin var, bir şarkı söylesen de dinlesek!\' dedi." Bu metinde hangi söz sanatları vardır?',
      solutionSteps: [
        '1. Adım: Tilkinin konuşması yer almaktadır -> İNTAK (Konuşturma).',
        '2. Adım: Hayvana konuşma özelliği verilerek insanlaştırılmıştır -> TEŞHİS (Kişileştirme).',
        '3. Sonuç: Metinde Teşhis ve İntak sanatları bir arada kullanılmıştır.',
      ],
      keyTakeaway: 'Hayvanların doğrudan konuştuğu her fabl metninde hem kişileştirme hem konuşturma sanatı bulunur.',
    },
  },
  {
    topicId: 'turkce-gorsel-mantik',
    courseKey: 'turkce',
    courseName: 'Türkçe',
    topicName: 'Görsel Okuma ve Mantık Muhakeme',
    lgsFrequency: 'Her yıl 2-3 soru (En belirleyici Türkçe bölümü)',
    difficultyLevel: 'Belirleyici / Zor',
    summaryBullets: [
      'Sözel Mantık Çözüm Metodu: Soru kökünü oku -> Sabit olan unsurlardan bir TABLO kur -> Verilen öncülleri kesin olanlardan başlayarak tabloya yerleştir.',
      'Kesin Bilgiler vs İhtimaller: Kesin olan verileri doğrudan tabloya yaz; ihtimalli olanları parantez içinde veya okla göster.',
      'Çapraz Eleme: Tabloda bir yere yerleşen kişi veya nesne diğer seçeneklerden hemen elenmelidir.',
      'İnfografik & Grafik Yorumlama: Grafiğin başlığına, eksenlerine ve renk lejantlarına dikkat et.',
      'Görsel Analizi: Karikatür, afiş ve krokilerde en küçük ayrıntılar, tarih ve saatler soru kökünün cevabını gizler.',
    ],
    mebTraps: [
      'MEB Tuzak 1: Kafadan çözmeye çalışmak! Sözel mantık sorusu ASLA kafadan çözülmez; kenara tablo veya çizgi çizmeyen öğrenci %90 yanılır.',
      'MEB Tuzak 2: "Kesinlikle doğrudur / Kesinlikle yanlıştır" sorularında olasılık barındıran şıkkı kesin doğru kabul etmek.',
    ],
    questionStrategy:
      'Hemen küçük bir tablo çiz: Günler (Pzt, Salı, Çarş.) veya Katlar (1, 2, 3, 4). "Hemen önünde", "yanında", "farklı günde" gibi bağlayıcı öncüllerle ihtimalleri ikiye düşür.',
    relatedExamSlug: 'lgs-turkce-unite-11-mantik-muhakeme',
    exampleQuestion: {
      questionText: 'A, B, C, D kişileri bir binanın 1, 2, 3 ve 4. katlarında oturmaktadır. B, A\'nın hemen üst katındadır. D en üst katta oturmamaktadır. 1. katta C oturduğuna göre 4. katta kim oturmaktadır?',
      solutionSteps: [
        '1. Adım: 4 katlı tablo yap: 4. kat, 3. kat, 2. kat, 1. kat.',
        '2. Adım: Kesin bilgi: 1. katta C oturuyor.',
        '3. Adım: Kalan katlar 2, 3, 4. "B, A\'nın hemen üst katındadır" bilgisi peş peşe iki kat gerektirir (2 ve 3 veya 3 ve 4).',
        '4. Adım: D en üst katta (4) oturamıyorsa D mecburen 2. katta oturmalıdır. O halde A 3. katta, B ise 4. katta oturur.',
        '5. Sonuç: 4. katta B oturmaktadır.',
      ],
      keyTakeaway: 'Peş peşe gelen ikilileri tek bir blok kabul ederek boş kalan yerlere yerleştirin.',
    },
  },
];
